### ISSUE TITLE
MySql

### ISSUE THREAD

**Issue by satlavida** [tower-archive/tower#10]
Does it have MySql support ?

**Comment by lancejpollard** [comment]
Not yet, but the [`Tower.Store`](http://towerjs.org/stores) api was setup to make implementing custom database drivers straightforward.  See these for examples:
- https://github.com/viatropos/tower/blob/master/src/tower/store/mongodb.coffee
- https://github.com/viatropos/tower/blob/master/src/tower/store/memory.coffee

Don't plan on personally implementing a MySQL store for a little while, but I would love to merge a pull request with this feature if you or anyone are up to it!  Even if it's only partially implemented that's a start.

**Comment by satlavida** [comment]
Ok thanks.

**Comment by ylluminate** [comment]
Any updates on effort in this direction?  I am curious about the use of JugglingDB with Tower: https://github.com/1602/jugglingdb

I think this would be a very nice addition and would solve this sore spot.
