### ISSUE TITLE
belongsTo is not working in mongoDB

### ISSUE THREAD

**Issue by lumin3000** [tower-archive/tower#100]
model

``` coffeescript
class App.Post extends Tower.Model
  @field "title", type: "String"
  @field "body", type: "String"

  @belongsTo "author", type: "User"
```

try this

``` coffeescript
App.User.create {firstName:"Jean-Baptiste"},(e,r)=>
  r.posts().create {title:"test",body:"testbody"}
```

The "authorId" is "Null" in MongoDB's Post

**Comment by avastou** [comment]
I have the same result when I use the @belongsTo
Any suggestion?

**Comment by avastou** [comment]
//--- lib/Tower/model/relation.js

line 133 - if (relation.targetType === this.ownerType) {
         + if (Tower.namespaced(relation.targetType) === this.ownerType) {

work for me but I do not know the possible consequences ..

**Comment by lancejpollard** [comment]
Working on more robust tests and such for associations, will get back to you.

**Comment by lancejpollard** [comment]
This is working now.
