### ISSUE TITLE
Error when running "tower new demoApp", ember.js

### ISSUE THREAD

**Issue by edubkendo** [tower-archive/tower#103]
When I run "tower new demoApp" everything completes but there is an error output amidst everything else:

Error downloading https://raw.github.com/emberjs/starter-kit/master/js/libs/ember-0.9.6.js

I tried removing the directory and re-running it multiple times, but continue to get this error, and when I visit that url in the broswer I get a 404. 

This did not happen last night, and when I check the directory for the app I generated last night, there were ember.js files in the vendor/javascripts directory. This is missing from the new app.

**Comment by lancejpollard** [comment]
We need to start pointing to specific commits for the js libraries referenced in the generator.
