### ISSUE TITLE
TowerJS redirects break because of hard-coded redirect

### ISSUE THREAD

**Issue by sebastianhoitz** [tower-archive/tower#104]
The changes in the redirector logic cause the normal redirectTo to break.

https://github.com/viatropos/tower/blob/master/src/tower/controller/redirecting.coffee#L22

**Comment by lancejpollard** [comment]
Oops, my bad...

**Comment by edubkendo** [comment]
So it looks like this is taking every redirect and when it goes through the if/else conditional its being sent to either /custom/ or /custom/1 . Under what circumstances are we actually wanting it to redirect to custom and/or custom/1 ?

**Comment by sebastianhoitz** [comment]
This was added for some unit tests I think.

**Comment by edubkendo** [comment]
Hmmm so would something like this work:

``` coffeescript
   if NODE_ENV is 'test'
     if options.action == 'index'
       url = "/custom"
     else
       url = "/custom/1"
```

**Comment by sebastianhoitz** [comment]
Yeah that should work.

On Wed, Apr 25, 2012 at 7:14 PM, edubkendo <
reply@reply.github.com

**Comment by lancejpollard** [comment]
How is this now?

**Comment by edubkendo** [comment]
This is fine on my end. @sebastianhoitz ?
