### ISSUE TITLE
design.io and design.io-javascripts are missing from devDependencies in package.json

### ISSUE THREAD

**Issue by contentfree** [tower-archive/tower#109]
This causes `design.io watch` to appear to hang because the globally installed design.io can't find these modules (it looks in the local directory only, it seems). If these were listed as devDependencies in package.json then they'd be installed and present when design.io tries to watch the project.

**Comment by contentfree** [comment]
My pull request includes design.io-javascripts as a devDependency.

**Comment by lancejpollard** [comment]
Thanks, will merge in a bit.
