### ISSUE TITLE
Intuitively, with a User that belongsTo a Company, user.company() should return the associated Company

### ISSUE THREAD

**Issue by contentfree** [tower-archive/tower#115]
It doesn't seem to work that way. It _seems_ that you have to do `user.company().first()` and this doesn't make much sense. This _would_ make sense if User had many Companies.

Tangentially related: `company = user.buildCompany({})` doesn't return a Company, but an array of Companies it seems. Also strange.

**Comment by lancejpollard** [comment]
It is now `user.get('company')` in 0.4.1.
