### ISSUE TITLE
Coffeekup -> Coffeecup

### ISSUE THREAD

**Issue by vjsingh** [tower-archive/tower#122]
For inserting links into text, 'yield' does not work because of a change to coffeescript (https://github.com/mauricemach/coffeekup/issues/113)

Coffeekup hasn't been updated in 7 months. Tower should use coffeecup instead (https://github.com/gradus/coffeecup).

Partial pull request here: https://github.com/viatropos/tower/pull/91

**Comment by edubkendo** [comment]
+1. The coffeekup author appears to have abandoned his open source projects, at least for the time-being.  Both major projects that I know of have been forked by the community and given proper updates.

**Comment by KingScooty** [comment]
+1

**Comment by vjsingh** [comment]
I'd try and fix my pull request except I can't get design.io working

**Comment by lancejpollard** [comment]
@vjsingh what's your operating system, version, npm version, rvm version, node version, etc.?

What happened to @mauricemach, his online presence stopped like 5 months ago.  I hope he's alright.

There's a few things that we have to rebuild in switching to CoffeeCup, mainly the partials.  That's why the delay, I don't have the time atm to get this in.  Looking forward to getting a pull request!

**Comment by vjsingh** [comment]
mac 10.6.8, npm 1.1.0-beta-4, node 0.6.6

If it helps, I put a console log in the 'write' function in Watchfile, and its never executed

**Comment by lancejpollard** [comment]
@vjsingh hmmm..., yeah can you show me the terminal output when you start it up?

What version of ruby and [RVM](http://beginrescueend.com/) are you using?

Also, try upgrading npm to the latest and reinstalling design.io?  It should work.

It may also be b/c the ruby script in design.io is never loading, perhaps because of an older/sudo-protected version of ruby.  Try running `sudo design.io`?

**Comment by vjsingh** [comment]
ruby 1.8.7 (2010-01-10 patchlevel 249) [universal-darwin10.0]

I don't have RVM installed, and v0.6.6 appears to be the latest for node,
according to brew?

And I re-installed design.io, and it still doesnt work :(

output (no output from design.io watch command):
design.io start

info: socket.io started
info:  Name: design.io-server     hook::listening
 Type: hook            Data: 5000
info:  Name: design.io-server     hook::started
 Type: hook            Data: 5000
info:  Name: design.io-server     hook::ready
 Type: hook            Data:
{"name":"design.io-server","type":"hook","pkginfo" ...
[Mon, 23 Apr 2012 20:44:28 GMT] INFO Design.io started on port 4181

On Mon, Apr 23, 2012 at 4:29 PM, Lance Pollard <
reply@reply.github.com

**Comment by lancejpollard** [comment]
Wait, did you run `design.io start` or `design.io`?  You should run `design.io`.  Here's a breakdown:
- `design.io start` starts up the socket server globally, but it does not compile the files
- `design.io` is an alias to `design.io watch`, which does watch the files in your project.
- `design.io start` should be run in a node project with design.io installed locally (`node_modules/design.io`). this is temporary, but it's needed now b/c the globally installed design.io (which handles the `design.io start` command) tries loading the local design.io to execute.  Again, this is temporary and will be cleaned up later.
- `design.io start` listens for notifications for any totally separate project that has executed the `design.io` (or `design.io watch`) command.  When it gets that notification, it sends it to the appropriate connected clients.
- You only have to run `design.io start` once, and just keep that terminal window open, or run it as a background process.
- Then, for every project, run `design.io` to watch the files.
- `design.io start` runs on port 4181.  That is where a small express app with socket.io is running.
- `design.io` doesn't run on a port, it's just a watch process.
- `design.io` uses ruby to watch files, as the node.js file watcher doesn't fully work yet on all platforms.
- The mac comes with ruby 1.8.7 installed by default, and often requires gems be installed with `sudo gem install x`.  This has been a problem in the past with design.io.  If you are using mac's default ruby version, make sure you install the ruby watcher with `sudo gem install fs-events`.  If you do `sudo npm install design.io`, this will also execute that command.
- A better approach is to install RVM, the Ruby Version Manager.  Then install ruby 1.9.2 (the recommended version in the community) and set it as the default (in the RVM install docs).  Then you can install design.io with `npm install design.io`, and no sudo is necessary.
- Tower executes the `design.io` command _internally_ - just to make it easier, so you don't have to open 2 terminal windows.  So, running `node server` in a generated tower app will run `design.io` (aka `design.io watch`).

Just wanted to get that out in case things weren't clear.

Also, here is a list of Homebrew commands:

https://github.com/mxcl/homebrew/wiki/The-brew-command

To upgrade your version of Node to 0.6.14 (that's what I have, may be higher now), run this:

```
brew upgrade node
```

To update to the latest version of NPM (I have 1.1.16, may be higher now), copy/paste the command from their homepage: http://npmjs.org/

Try that stuff and see if it gets working.  It definitely should be working.  Here's my setup:
- Mac OS X 10.6.7
- Node 0.6.14
- NPM 1.1.16
- RVM 1.9.2
- Ruby 1.9.2 (via RVM)

**Comment by lancejpollard** [comment]
Made the switch in the `development` branch.

**Comment by vjsingh** [comment]
Nice, I missed that. I'll close the issue
