### ISSUE TITLE
ERR! Error: EXDEV, link '/usr/lib/nodejs/node-gyp/legacy/tools/gyp/pylib/gyp/system_test.pyc'

### ISSUE THREAD

**Issue by kane-thornwyrd** [tower-archive/tower#124]
Hi,

I'm out of luck and knowledge, I must admit…
It seems that I can't "npm install", full commands launched, outputs and npm-debug.log here: https://gist.github.com/2497088

Help me figuring out what is the issue, does it come from my install or tower ?
And eventually how to solve this and really start using tower !

Thanks

**Comment by lancejpollard** [comment]
Hey, try clearing your npm cache with and without `sudo` and running again (also try updating your version of npm to >= 1.1.16):

```
[sudo] npm cache clean
npm install
```

That's usually fixed these seemingly random installation problems.  Let me know how that goes.  If it doesn't work, send me your OS and node version and we'll go from there.

**Comment by kane-thornwyrd** [comment]
So,
Fedora 16 Verne
`$ uname -a
Linux lucian3.local 3.3.2-6.fc16.x86_64 #1 SMP Sat Apr 21 12:43:20 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux`
`$ node --version
v0.6.15`
`$ npm -v
1.1.18`

Thanks for the lightningfast reply !

**Comment by lancejpollard** [comment]
No problem. Don't know anything about Fedora, did clearing the cache not work?  If there's a different error message, post that onto a gist too.  Thanks!

**Comment by kane-thornwyrd** [comment]
Strangely 
`$ npm cache clean`
as
`$ sudo npm cache clean`
didn't output anything…
Asserting that's normal I relaunched:
`$ npm install` (still inside myProject folder) and:
https://gist.github.com/2497302

**Comment by lancejpollard** [comment]
I also saw this earlier today, don't know anything about native extensions but if this isn't an npm cache issue it looks like the error is talking about a native extension:

https://twitter.com/#!/TooTallNate/status/194927373387448320

**Comment by kane-thornwyrd** [comment]
I don't have time right now to dig further, it's not officially part of the project I'm on, but I'll look for the solution tonight (in ~10hours) and hope to solve this, if this isn't by the way. I really want to use the almighty Tower goodness !
