### ISSUE TITLE
`tower new projectname` yields node.js:201 -> Error: connect ETIMEDOUT

### ISSUE THREAD

**Issue by ylluminate** [tower-archive/tower#126]
Each time I've attempted to create a new project it yields a `node.js:201 error`.  It seems as though this may be some kind of network error?  It does fail at different points each time in the create process.  

Here's the full error output:

```
node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: connect ETIMEDOUT
    at errnoException (net.js:670:11)
    at Object.afterConnect [as oncomplete] (net.js:661:19)
```

**Comment by edubkendo** [comment]
What versions of Node and npm are using?

I've seen similar errors recently but running:

```
npm cache clean
```

And then re-trying usually seems to clear it up for me right away.

**Comment by ylluminate** [comment]
node `v0.6.15` & npm `1.1.16`

It did eventually finished...  I am guessing that this particular instance was some kind of network unavailability; are files pulled down from some location at this point in the process of creating the project?

So many of these `node.js:201` issues around the web lead me to think that we need some better verbosity or error messages of some kind.

**Comment by lancejpollard** [comment]
Yeah this was most likely because your internet connection was spotty.  We could probably catch these network errors and output a message like `"make sure you have a good internet connection"`.

**Comment by ylluminate** [comment]
Well @viatropos strange thing is that I have a business class connection that's blazing fast and I actually tested it during the issue.  Every other app and network test (I'm also a network admin) came back fine.  So it seems something queer relating to node.js singularly.  <sigh>  

But I seriously believe that there should be stronger error handling on some of these issues, yes.  At least if it would give an indication of the cause of an error it would help in the long run.  Great exception handling and messages go a long way at helping a marvelous framework like you've put together here really gain traction.

**Comment by lancejpollard** [comment]
I'll look into doing this in the next release.  Let me know if you see it again.

**Comment by Zenithar** [comment]
I'm experiencing to same problem, with node 0.8.9, I think it's a http proxy using issue.
