### ISSUE TITLE
memory leak with design.io

### ISSUE THREAD

**Issue by activestylus** [tower-archive/tower#127]
Steps to repeat

```
$ design.io start
$ tower server -p 3000
$ tower console
```

Check out Activity Monitor (/Applications/Utilities) node starts to immediately consume all available RAM (in my case 1.5GB!)

Sometimes it takes a while, and sometimes the memory usage is instant. But it always eats all my RAM

**Comment by activestylus** [comment]
After further poking, the culprit is definitely design.io. It takes up not only all my RAM, but also 94% of my CPU, leaving my OS all wonky. Eventually the process crashes.

Also figured out this happens even when design.io is on its own. Must have some sort of blocking going on in that lib

**Comment by activestylus** [comment]
Okay so its not just design.io - plain old tower server process eventually eats into all available ram/cpu.

**Comment by activestylus** [comment]
Ok so when I start the server, two node processes are fired up. One of them hovers around 35MB memory usage. Here is the one that eats up all the RAM (inspect from Activity Monitor)

```
/Users/homebass/Desktop/Code/node/apps/wordup
/Users/homebass/local/bin/node
/usr/lib/libutil1.0.dylib
/Users/homebass/Desktop/Code/node/apps/wordup/node_modules/forever/node_modules/daemon/lib/daemon.v0.6.13-pre.node
/Users/homebass/Desktop/Code/node/apps/wordup/node_modules/forever/node_modules/node-fork/lib/createpair.v0.6.13-pre.node
/Users/homebass/Desktop/Code/node/apps/wordup/node_modules/forever/node_modules/microtime/build/Release/microtime.node
/Users/homebass/Desktop/Code/node/apps/wordup/node_modules/design.io/node_modules/hook.io/node_modules/weak/build/Release/weakref.node
/usr/lib/dyld
/private/var/db/dyld/dyld_shared_cache_x86_64
->0x0e5b7bc0
->0x0e5b64b4
->0x0e5b5d48
count=1, state=0
->0x0e5b70d0
->0x0e5b62c0
/Users/homebass/.forever/lX2v.log
adobe-dns-4.adobe.com:commplex-main
/Users/homebass/.forever/4D-9.log
/Users/homebass/Desktop/Code/node/apps/wordup/public/stylesheets/app/client/controllers/sitesController.coffee
/Users/homebass/.forever/gMNX.log
/Users/homebass/.forever/sock/worker.1335863482251554.sock
->0x0acfef3c
->0x0e5b56a4
/Users/homebass/Desktop/Code/node/apps/wordup/public/javascripts/app/client/controllers/sitesController.js
->0x08a5b7d8

```

**Comment by lancejpollard** [comment]
Will look into this probably next week.  This is definitely b/c of design.io.  Design.io is basically a wrapper around the pretty cool library [hook.io](https://github.com/hookio/hook.io), so let's also make sure hook.io works as expected (I imagine it does, since it's been around for a while and looks like it's been pretty much perfected).

**Comment by activestylus** [comment]
Interesting - does the tower server itself call design.io or hook.io? Because I had similar issues just running `tower server`

**Comment by lancejpollard** [comment]
It does, `tower server` calls design.io.

https://github.com/viatropos/tower/blob/master/src/tower/server/application/watcher.coffee#L14

**Comment by activestylus** [comment]
Any luck?

**Comment by lancejpollard** [comment]
Haven't had the time lately to check this out :/  Doesn't look like I'll be able to anytime soon, have a bunch of other things before in line.

If you want to take a swing at it I will definitely merge a pull request. If this is preventing you or others from using it at all then I'll move it up in priority, but it seems like there are temporary workarounds at least.

**Comment by activestylus** [comment]
Yeah I have to admit the memory thing has kept me from using this for anything more than a sandbox/playground.

Here's the thing - I have no need whatsoever for design.io (as cool as it is) My current setup leverages LiveReload. Perhaps in the future this should be more of an add-on for tower, rather than integrate it with the server. Ideally I would be able to use it without design.io at all.

**Comment by lancejpollard** [comment]
I agree, it will be an addon. Just wanted to have it in there to demo initially :). A lot has changed since then, I think this stuff will be much easier to do now anyway with the latest version of Node. Will refactor/extract eventually, feel free to give it a shot as well.

**Comment by ylluminate** [comment]
Any luck @activestylus or @viatropos with addressing this one so far on the dev branch?

**Comment by lancejpollard** [comment]
@ylluminate @activestylus Going to start working on this now, need to simplify the getting started process and design.io is a pain. Commented a little here https://github.com/viatropos/tower/issues/206#issuecomment-7913200.

Ideally the asset compilation and "watch" system would have these features:
- Transparent, doesn't require installing a separate app or running a separate command in another window. But, it should [eventually] be able to be run separately/manually if desired, so you can for example keep the watcher constantly running even if your server turns on/off
- Pure node. Remove this ruby business.
- Fast/efficient. Some issues with design.io are that it used some JS AST parser to find the `require` statements, but that's super slow with a large number of files. And also, it used the `fs` async api, which causes a memory explosion on a large number of files (I think).
- Should compile the assets instantly when you start your app (right now you have to wait a few seconds).

What are your guys' thoughts. Have you tried grunt? Are there any other tools?

**Comment by lancejpollard** [comment]
Still not able to get notifications from `fs.watch` on a directory... https://github.com/joyent/node/issues/1986

**Comment by lancejpollard** [comment]
Tower is now no longer using design.io.

Instead, use grunt. In the generated tower app:

```
grunt start --config ./grunt.coffee
```

In the tower source code, an alias to that:

```
make watch
```

**Comment by activestylus** [comment]
Ok just updated tower `npm install tower -g` and generated a new app. CD'd into the app and ran `npm install` and for some reason it still tries to install design.io. (note: errors are because i didnt run it with sudo)

```
> design.io@0.3.1 install /Users/homebass/Desktop/Code/node/apps/skyscraper/node_modules/design.io
> gem install rb-fsevent rb-inotify --no-ri --no-rdoc

Fetching: rb-fsevent-0.9.1.gem (100%)
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions into the /Users/homebass/.rvm/gems/ruby-1.9.3-p194-falcon directory.
npm ERR! error installing design.io@0.3.1
...
npm not ok
```

**Comment by activestylus** [comment]
Running a test app right now. HUGE difference! Currently looking at a memory footprint of about 27MB which is a welcome change from the 3GB it was eating up before. All we need to do now is make sure that design.io is not packaged with tower on install and this issue can be closed. Nice work!

btw - I love how you've tweaked the logger so we can see memory usage for each request. Very useful

**Comment by lancejpollard** [comment]
Awesome! Going to push this to npm in the next few days.

Hey so how do you measure the memory usage of the program? I'm no master at system-level commands lol.

**Comment by activestylus** [comment]
I used to just run `ps aux` but nowadays I opt for OS X's Activity Monitor (in the Applications/Utility folder) I like being able to sort the list and pole around at the processes.

**Comment by lancejpollard** [comment]
cool, I'm using the activity monitor as well, just wondered how you might do it in the terminal, will checkout `ps aux`, thanks.
