### ISSUE TITLE
[Error: Target script does not exist: node_modules/design.io/bin/design.io]

### ISSUE THREAD

**Issue by mauromarano** [tower-archive/tower#132]
Using the last version of tower, node and npm.

When I try to start the server I got this error: [Error: Target script does not exist: node_modules/design.io/bin/design.io]

And when I open up my broweser it does not load any static file (css, js ecc.).

Mongodb is up and running

**Comment by lancejpollard** [comment]
Make sure you've run `npm install` to install the dependencies in a new app.  If you did that, also make sure you've installed design.io:

```
npm install design.io
```

Let me know if that helps.

**Comment by mauromarano** [comment]
I dont know what went wrong, but after creating a new project everything is working fine.
Thank you
