### ISSUE TITLE
can't run sample application

### ISSUE THREAD

**Issue by gsscoder** [tower-archive/tower#133]
I've created a sample application following http://towerjs.org/screencasts.

I've installed all deps with npm and I've also a local mongodb instance up and running.

Anyway every url I try to access like

http://localhost:3000/posts/
http://localhost:3000/posts/index
...
I got

No path matches /posts/
No path matches /posts/index
...
Here my sources: http://dl.dropbox.com/u/50740523/tower-app.zip

Regards, Giacomo

P.S.: on SO -> http://stackoverflow.com/questions/10333767/towerjs-running-a-sample-application#comment13372067_10333767

**Comment by lancejpollard** [comment]
A lot has been changed since this. Try again with tower 0.4.1 and reopen if there are any issues. Thanks!
