### ISSUE TITLE
Root Cakefile of generated project

### ISSUE THREAD

**Issue by Voronchuk** [tower-archive/tower#136]
For some reason on _client  = knox.createClient Tower.secrets.s3_  **Tower.secrets** is undefined. Had to put hack like 
_Tower.secrets = {}_
_Tower.secrets.s3 = Tower.config.credentials.s3_

One line before, to make cake assets:upload:s3 work properly

**Comment by lancejpollard** [comment]
This is a bug, thanks for pointing out.  If you want you can submit a pull request with the fix and I'll merge it in, otherwise I'll get to this tonight or tomorrow.

**Comment by Voronchuk** [comment]
Done

**Comment by lancejpollard** [comment]
Nice
