### ISSUE TITLE
Wrong paths

### ISSUE THREAD

**Issue by Voronchuk** [tower-archive/tower#138]
Assets uploaded with _cake assets:upload:s3_ have URLs like: 
https://s3.amazonaws.com/[BUCKET]/stylesheets/application-[HASH].css

But after you define _Tower.assetHost = 'https://s3.amazonaws.com/[BUCKET]'_ like that. Links will be:
https://s3.amazonaws.com/[BUCKET]/assets/application-[HASH].css
Which is not correct.

The actual path is defined here: tower/lib/tower/view/helpers/assetHelper.js line 64. 

Will try to fix it myself.

**Comment by Voronchuk** [comment]
Sent a pull request with quick fix for that, through this issue need some discussion to resolve it fully.

Another trouble now is with actual assets stored on S3, it seem that browser can't decode them properly:
https://s3.amazonaws.com/igt/stylesheets/vendor-25398bb2e46ea86597e5e6d5a29f5457.css

I gues it's smth with their gzip encoder or s3 settings, not sure that I can fix that myself, need help. Don't wish to disable gzip alltogather.

**Comment by Voronchuk** [comment]
https://forums.aws.amazon.com/thread.jspa?messageID=276427

It seem that files shouldn't be stored in gzipped form. Their server should do the work himself by Content-Encoding header. Will try to test that and post my results.

**Comment by Voronchuk** [comment]
Ok. On my side I fixed S3 issues, and now deploy work as intended. Made a pull request with fixes, review if you need them.

**Comment by lancejpollard** [comment]
Updated a lot of this recently, we need to check if it's still broken (and write some tests).
