### ISSUE TITLE
cluster implementation

### ISSUE THREAD

**Issue by avastou** [tower-archive/tower#145]
Hi,

I search an example for implement the cluster plugin (https://github.com/learnboost/cluster)
Any suggestion ? thank.

A

**Comment by lancejpollard** [comment]
I have had my eye on this but haven't gotten to it yet. Probably wont get to this for a few months. Feel free to hack on it and try to integrate it, that would be super awesome :)

**Comment by lancejpollard** [comment]
Cluster support in 0.5.0.
