### ISSUE TITLE
In generated apps, "forever" module in devDependencies.

### ISSUE THREAD

**Issue by edubkendo** [tower-archive/tower#149]
'forever' is required by /server/application/watcher.coffee which gets called in turn by /server/application.coffee, which of course runs the server and listen functions when running Tower apps.  I think normally npm installs devDependencies into node_modules, it just doesn't install THEIR dependents (could be wrong on this), however, apparently heroku does not install devDependencies at all.  In order to get an app running on heroku ( https://github.com/edubkendo/firstApp ) I had to manually move forever in the package.json into "Dependencies" before pushing it.  Otherwise the app would start the server and then immediately crash because forever was not installed.  Either way, since forever is being used directly by production apps, it is technically a direct dependency and not used only for development. Thanks.

**Comment by lancejpollard** [comment]
Going to change the way this works in the next release, you shouldn't need forever in production. Stay tuned.

**Comment by edubkendo** [comment]
dope. sounds like that will be better then. at the time I wrote this, it was one of the major frustrations I encountered in trying to get an app on heroku.

**Comment by lancejpollard** [comment]
_for reference_ this is no longer the case in 0.4.1
