### ISSUE TITLE
Flash messages

### ISSUE THREAD

**Issue by edubkendo** [tower-archive/tower#151]
Was going to give implementing these a shot.  Wondered if there were any suggestions as the best place to put the method?  I was thinking tower/controller/instrumentation.coffee seemed like the most natural home for it.

**Comment by lancejpollard** [comment]
Awesome.  I would create a separate file, like `Tower.Controller.Flash`:

https://github.com/rails/rails/blob/master/actionpack/lib/action_controller/metal/flash.rb

Whenever you're adding a set of functionality that has more than 1 method I'd just put it into a separate module.  Unless it's just an extension of something that we've already created a module for.

**Comment by edubkendo** [comment]
These are just about done. Should have a pull request up this weekend.

**Comment by edubkendo** [comment]
Done.
