### ISSUE TITLE
Has-One association: Are there any unit tests or examples?

### ISSUE THREAD

**Issue by sebastianhoitz** [tower-archive/tower#153]
In the documentation for Tower it says that there can be @hasOne relationships.

But I can't find any examples in the documentation or in the unit tests on how to do these. Are these actually already implemented or is there something missing?

**Comment by edubkendo** [comment]
@sebastianhoitz Did you check out https://github.com/viatropos/tower/wiki/1-1 ? That has examples of the @hasOne relationship. Also, @viatropos response to my question about hasMany/belongsTo on SO might be helpful: http://stackoverflow.com/questions/10749758/how-do-i-use-one-to-many-relationships-in-tower-js .

**Comment by sebastianhoitz** [comment]
Thanks! Ok I think I might have skipped some things then. I will try again.

**Comment by marcinrogacki** [comment]
I noticed that [Wiki Has-one](https://github.com/viatropos/tower/wiki/1-1) looks outdated so I tried example from [model/relations.coffee#L14](https://github.com/viatropos/tower/blob/master/src/tower/model/relations.coffee#L14)
But it also does not works, giving error:

```
TypeError: Object #<error> has no method 'createFacebookUser'
```

So I tried method from Has-Many [model/relations.coffee#L35](https://github.com/viatropos/tower/blob/master/src/tower/model/relations.coffee#L35):

```
user.facebookUser().create()
```

It saves record, but without id reference (userId: null):

```
# mongo query
db.facebookUsers.find({})
{ "fbId" : <someide>, "userId" : null, ...snip....  }
```

Someone uses it with successful? I'll be grateful for answer.

**Comment by edubkendo** [comment]
@robak1987 first, read through the stackoverflow link I posted above, then checkout https://github.com/edubkendo/demoApp for a step-by-step on how I setup hasMany/belongsTo

**Comment by marcinrogacki** [comment]
Thank you for answer and app demo :)
I also set up **hasMany** feature, but I have problem with **hasOne**. **HasMany** creates id reference, but **hasOne** doesn't.  I have checked towerjs source and it looks like hasOne is unimplemented: [hasOne](https://github.com/viatropos/tower/blob/master/src/tower/model/relation/hasOne.coffee) vs [hasMany](https://github.com/viatropos/tower/blob/master/src/tower/model/relation/hasMany.coffee)

**Comment by edubkendo** [comment]
I see what you mean now. Yes, looking at the source, it looks like hasOne is still incomplete. Also, I noticed that in relations.coffee, hasOne, hasMany and belongsTo all have class methods, while hasManyThrough does not. Dunno if it doesn't because it is different or if it is just incomplete also, but wanted to mention that here for reference.

**Comment by lancejpollard** [comment]
The associations are much more robust in the development branch, check it out. Docs coming in the next month or so.
