### ISSUE TITLE
Model.includes() not working?

### ISSUE THREAD

**Issue by sebastianhoitz** [tower-archive/tower#154]
I've tried specifying to eager load an associated collection, but for some reason tower does not seem to consider this.

This is what I've tried:

``` coffeescript
App.Cart.includes "items"
App.Cart.all (error, data) =>
  console.log data[0].items() # just gives me an object with a reference to the model and zero records
```

Do I miss something here?

**Comment by sebastianhoitz** [comment]
Ah... just noticed: This is still on the roadmap.
Could we maybe point those things that are still on the roadmap and not ready yet out in the documentation?

---

And when we are already on this: What would be the best way to implement this? I can help out with this if wanted. @viatropos What do you think?

**Comment by lancejpollard** [comment]
Yeah once we clean up development branch and merge it to master I'm going to go through all the documentation and update everything and I'll start marking things as todo or having a more obvious todo section.

This would be great to get some help on.  There's a couple things not yet done for the - what's now becoming - "cursor" (the 0.4.0 scopes and criteria):
- includes (eager loading)
- except/without (specific fields, not sure on naming yet)
- explain
- select/with (specific fields, not sure on naming yet)
- nested paths (`where('address.city': 'San Francisco')`)

I'm finishing up a bunch of pagination stuff for that right now.

The best way to implement `includes` is probably just to see how they did it in Rails and go from there.  I haven't looked much into this lately.  It should be able to handle most of the same arguments as Rails:

``` coffeescript
App.Cart.includes('items').first (error, cart) =>
  cart.get('items').all # no database call

# where orderItem belongsTo product and you want both:
App.Cart.includes(orderItems: 'product').all
```

I remember Rails was using an "IdentityMap" class, but I think we can get away with using `Tower.Store.Memory` somehow.  But, keeping a global store of the instantiated models might just be by `id`, so it might just be a hash.  We're also going to have to think about keeping _any_ instantiated model in a global "identity map", but depending on the complexity we should probably save that for later (at least building with that in mind).

**Comment by sebastianhoitz** [comment]
Ok, I'll try to have a shot at this. Mostly the includes functionality first, because that is one part that we need in our own app with tower soon.

**Comment by lancejpollard** [comment]
Sweet, I'll be IRC #towerjs most of this week.

**Comment by sebastianhoitz** [comment]
Ok, awesome. Will definitely hit you up then.

Just for the record, this is where rails handles the eager loading: https://github.com/rails/rails/tree/master/activerecord/lib/active_record/associations/preloader

I'll try to model my implementation close to theirs.

**Comment by lancejpollard** [comment]
Started to implement this in the development branch but I think it's broken now - doing some work on embedded documents and keeping the associations on the client bound to each other (parent.child == child.parent). It's hard to do on the server and haven't figured out how to do it properly yet (since it's async and dependent on the request, while Rails is sync). This is kind of what I'm thinking for an IdentityMap: https://github.com/viatropos/tower/commit/b996599e4e8069f793a7402d6a78430650e43887

Going to work on embedded docs this week, will try and handle this as well.
