### ISSUE TITLE
Controller @params can not handle boolean values

### ISSUE THREAD

**Issue by sebastianhoitz** [tower-archive/tower#155]
I have a model that has a boolean value.

Sadly, the `@params` method in the controller only seems to be able to filter by every type _but_ boolean values ;)

**Comment by sebastianhoitz** [comment]
I came up with a solution for this.

I created a new Boolean param class:

``` coffeescript
class Tower.HTTP.Param.Boolean extends Tower.HTTP.Param
  parse: (value) ->
    values  = []
    array   = value.toString().split(/[,\|]/)

    for string in array
      string    = string.replace(/^\^/, "")

      values.push [@parseValue(string, ["$eq"])]

    values

  parseValue: (value, operators) ->
    super((/^(true|1)$/i).test(value), operators)
    # super(parseFloat(value), operators)

module.exports = Tower.HTTP.Param.Boolean
```

You can use it like this in your controller:

``` coffeescript
@param "isPublished", type: "Boolean"
```

It allows queries containing 1 and true:

?isPublished=true
?isPublished=1

**Comment by lancejpollard** [comment]
Copy-pasting into dev, thanks! Unless you want to make it a pull request, let me know :)
