### ISSUE TITLE
Scaffold generating all field as string

### ISSUE THREAD

**Issue by amacgregor** [tower-archive/tower#162]
Using Tower.js 0.4.0-13 scaffold command all fields and model attribute types where generated as string no matter if they where specified as text, integer or other type of value

**Comment by edubkendo** [comment]
What does the command you are entering in the terminal look like?  I know that 

```
tower generate scaffold Post title:string body:text userId:integer
```

works correctly for me.

**Comment by amacgregor** [comment]
I deleted the VM that I was using for testing tower and reacreated, working properly now.
