### ISSUE TITLE
Server hangs when trying to create a resource, returns no data

### ISSUE THREAD

**Issue by mhuggins** [tower-archive/tower#164]
I just created my first Tower.js app, and I used the scaffold generate to create a User model, controller, etc.  The only custom code I added is some validations into my `User` model.

Before adding any validations, I was able to create users via `UsersController#create`.  After adding any validations, posting to the same action results in no response.  I could see that the params were successfully posted to the controller, and the browser sat and waited for a response until it finally gave up with a "no data" error response.

I posted my code here: https://github.com/mhuggins/unresponsive-tower

Is something wrong with my validation code (or any other bit of code) that I added to my User model?  I don't think I edited any files with the exception of my model.

**Comment by mhuggins** [comment]
I realized I did edit the user views and controller a bit.  The views were edited to display only `encrypted_password` (not `password` or `password_confirmation`), and the controller does not accept `encrypted_password` as a parameter.  So I suppose I could have messed something up there too, but it doesn't seem likely.

**Comment by edubkendo** [comment]
See Issue #157 , there are known issues with the model validations.

**Comment by lancejpollard** [comment]
This isn't an issue anymore I don't think. If validations do fail, it will respond with an error code. Reopen if it's still an issue.
