### ISSUE TITLE
Use partials with ECO(or other template engines)

### ISSUE THREAD

**Issue by rafaelmotta** [tower-archive/tower#165]
I did some tests with Jade and Coffekup, but I did not like this engines. I prefer the basic HTML. So, I decided to use ECO or EJS. ECO is nice, it's like EJS, but you write Coffescript.

I tried to change the engine to ECO and EJS, but when I use some partial nothing is printed.

I tried a lot of variations, and Tower found the file, but how I said, nothing is printed.

I tried something like this:

<%- @partial 'shared/header' %>

Using the same code on Express, works fine.

**Comment by lancejpollard** [comment]
Hey, the `partial` method is tailored to Coffeecup currently. We need to add support for the other template engines (or hook into the built in express version). If you'd like to do this I will definitely merge a pull request, otherwise I'll be getting to this in a few weeks.

**Comment by lancejpollard** [comment]
Everything is going to be in handlebars in 0.5.0.
