### ISSUE TITLE
Issue creating new application

### ISSUE THREAD

**Issue by eoliphan** [tower-archive/tower#167]
Hi, running on OS X Lion, just installed tower via npm.  Created a new app and got the following:

```
 create : joinword/vendor/stylesheets/prettify.css

http.js:1202
  var socket = req.socket;
                  ^
TypeError: Cannot read property 'socket' of undefined
    at Stream.responseOnEnd (http.js:1202:19)
    at Stream.emit (events.js:88:20)
    at Unzip.<anonymous> (/usr/local/lib/node_modules/tower/node_modules/superagent/lib/node/utils.js:112:19)
    at Unzip.emit (events.js:88:20)
    at zlib.js:358:10
    at Zlib.callback (zlib.js:448:13)
```

Any ideas?

**Comment by lancejpollard** [comment]
Not sure... what version of NPM and node are you using? I haven't tested it myself on Lion yet either.

**Comment by eoliphan** [comment]
Pretty current, Here ya go:
erich-oliphants-MacBook-Pro:projects eoliphan$ npm -v
1.1.24
erich-oliphants-MacBook-Pro:projects eoliphan$ node -v
v0.6.19

**Comment by lancejpollard** [comment]
Can't tell from the error message, can you paste any more (such as node-debug.log if there is one)? Try generating again?

**Comment by eoliphan** [comment]
ACtually I just noticed some weirdness with my node install, redoing it from scratch then will try again.,

**Comment by eoliphan** [comment]
lol, well I've upgraded everything:
erich-oliphants-MacBook-Pro:projects eoliphan$ node -v
v0.8.1
erich-oliphants-MacBook-Pro:projects eoliphan$ npm -v
1.1.36

But still have the same problem.

I've regenerated from scratch a few times, I get the issue consistently.

No log was generated.  Is there a switch or  something I can turn on?

FYI, the http.js error occurs on a different line since the upgrade:

```
 create : tapp/Watchfile
   create : tapp/vendor/stylesheets/prettify.css

http.js:1457
  var socket = req.socket;
                  ^
TypeError: Cannot read property 'socket' of undefined
    at Stream.responseOnEnd (http.js:1457:19)
    at Stream.EventEmitter.emit (events.js:115:20)
    at Unzip.exports.unzip._on (/opt/local/lib/node_modules/tower/node_modules/superagent/lib/node/utils.js:112:19)
    at Unzip.EventEmitter.emit (events.js:115:20)
    at zlib.js:349:10
    at Zlib.callback (zlib.js:439:13)
```

**Comment by lancejpollard** [comment]
Can you list out all of the versions of your NPM modules you have installed, both locally and globally?

```
npm list
npm list -g
```

Here are mine for `npm list`: https://gist.github.com/2b377dbb7e53dad322e0 (I'm using "tower 0.4.1", which is the dev branch, but the dependencies are still the same).

**Comment by eoliphan** [comment]
Here's mine looking at yours

npm list:

erich-oliphants-MacBook-Pro:projects eoliphan$ npm list
/Users/eoliphan
├─┬ bogart@0.3.38 
│ ├── commander@1.0.0 
│ ├── jsgi@0.2.4ssl 
│ ├── mkdirp@0.3.3 
│ ├── mustache@0.3.1-dev 
│ ├── node-uuid@1.3.3 
│ ├── oauth@0.9.5 
│ ├─┬ parted@0.0.8 
│ │ └── qs@0.5.0 
│ ├── promised-io@0.2.3 
│ ├── request@2.2.9 
│ └── underscore@1.3.3 
├─┬ connect@2.3.6 
│ ├── bytes@0.0.1 
│ ├── cookie@0.0.4 
│ ├── crc@0.2.0 
│ ├── debug@0.7.0 
│ ├── formidable@1.0.11 
│ ├── fresh@0.0.1 
│ ├── mime@1.2.4 
│ ├── qs@0.4.2 
│ └── range-parser@0.0.4 
└─┬ express@2.5.11 
  ├─┬ connect@1.9.1 
  │ └── formidable@1.0.11 
  ├── mime@1.2.4 
  ├── mkdirp@0.3.0 
  └── qs@0.4.2 

npm list -g:

├─┬ npm@1.1.36 
│ ├── abbrev@1.0.3 
│ ├── ansi@0.1.2 
│ ├── archy@0.0.2 
│ ├── block-stream@0.0.5 
│ ├── chownr@0.0.1 
│ ├── fstream@0.1.18 
│ ├─┬ fstream-npm@0.1.0 
│ │ └── fstream-ignore@0.0.5 
│ ├── glob@3.1.10 
│ ├── graceful-fs@1.1.8 
│ ├── inherits@1.0.0 
│ ├── ini@1.0.2 
│ ├─┬ init-package-json@0.0.4 
│ │ └── promzard@0.1.5 
│ ├── lockfile@0.2.1 
│ ├── lru-cache@1.1.0 
│ ├── minimatch@0.2.5 
│ ├── mkdirp@0.3.3 
│ ├── node-gyp@0.5.2 
│ ├── node-uuid@1.3.3 
│ ├── nopt@1.0.10 
│ ├── npm-registry-client@0.0.8 
│ ├── npmlog@0.0.2 
│ ├── osenv@0.0.3 
│ ├── proto-list@1.0.0 
│ ├── read@0.1.0 
│ ├── read-installed@0.0.1 
│ ├── read-package-json@0.0.12 
│ ├── request@2.9.203 
│ ├── retry@0.6.0 
│ ├── rimraf@2.0.2 
│ ├── semver@1.0.14 
│ ├── slide@1.1.3 
│ ├── tar@0.1.13 
│ ├── uid-number@0.0.3 
│ └── which@1.0.5 
└─┬ tower@0.4.0-13 
  ├── accounting@0.3.2 
  ├── async@0.1.22 
  ├── coffee-script@1.3.3 
  ├── coffeekup@0.3.1 
  ├── commander@1.0.0 
  ├── ejs@0.7.2 
  ├── ember-metal@0.9.2 
  ├── ember-runtime@0.9.2 
  ├─┬ express@2.5.11 
  │ ├─┬ connect@1.9.1 
  │ │ └── formidable@1.0.11 
  │ ├── mime@1.2.4 
  │ ├── mkdirp@0.3.0 
  │ └── qs@0.4.2 
  ├── geolib@1.1.7 
  ├── inflection@1.2.1 
  ├── mime@1.2.6 
  ├── mint@0.3.5 
  ├── moment@1.6.2 
  ├── node-uuid@1.3.3 
  ├─┬ pathfinder@0.3.0-1 
  │ ├─┬ detective@0.1.1 
  │ │ └── uglify-js@1.2.6 
  │ ├─┬ findit@0.1.2 
  │ │ └─┬ seq@0.3.5 
  │ │   ├─┬ chainsaw@0.0.9 
  │ │   │ └── traverse@0.3.9 
  │ │   └─┬ hashish@0.0.4 
  │ │     └── traverse@0.6.3 
  │ └── mkdirp@0.3.3 
  ├── qs@0.5.0 
  ├─┬ socket.io@0.9.6 
  │ ├── policyfile@0.0.4 
  │ ├── redis@0.6.7 
  │ └─┬ socket.io-client@0.9.6 
  │   ├─┬ active-x-obfuscator@0.0.1 
  │   │ └── zeparser@0.0.5 
  │   ├── uglify-js@1.2.5 
  │   ├─┬ ws@0.4.20 
  │   │ ├── commander@0.6.1 
  │   │ ├── options@0.0.3 
  │   │ └── tinycolor@0.0.1 
  │   └── xmlhttprequest@1.2.2 
  ├─┬ superagent@0.5.0 
  │ ├── emitter-component@0.0.1 
  │ ├── formidable@1.0.9 
  │ ├── mime@1.2.5 
  │ └── qs@0.4.2 
  ├── underscore@1.3.3 
  ├── underscore.logger@0.3.1 
  ├── underscore.string@2.2.0rc 
  ├── URIjs@1.4.2 
  ├─┬ useragent@1.1.0 
  │ ├── request@2.9.202 
  │ ├── semver@1.0.14 
  │ └── yamlparser@0.0.2 
  ├── validator@0.4.9 
  └── wrench@1.3.9

**Comment by eoliphan** [comment]
I definitely have some newer versions of modules (async, etc)

**Comment by lancejpollard** [comment]
I think it probably has to do with that. I recommend trying to install specific versions of modules until it works :/ this will be simplified/fixed in a little while when dev is merged into master. But for now, try doing things like:

```
npm install superagent@0.4.1 --force
```

If you find the solution please post. Hope that helps.

**Comment by lancejpollard** [comment]
Anything in particular fix this? Going to close this unless you're still having issues.
