### ISSUE TITLE
ember 0.9.8.1 breaks routing

### ISSUE THREAD

**Issue by scottkf** [tower-archive/tower#168]
`Uncaught TypeError: Object history has no method 'setURL'`

The ember routing API was changed, see here: 

https://gist.github.com/2728699

and this fiddle (from the gist) http://jsfiddle.net/C7LrM/86/

**Comment by scottkf** [comment]
This has actually been happening intermittently and I haven't discovered the cause yet

**Comment by lancejpollard** [comment]
Ember is just about to release 1.0: [packages/ember/package.json](https://github.com/emberjs/ember.js/blob/c27a3101ae5c5fb7e725921a75415909fad6933e/packages/ember/package.json#L7).

I've been working on file uploading and authentication and am just about finished with that (doing embedded documents this week), in the dev branch. After that I am going to update Ember on Node to use the latest (and try and get them to merge the npm/ember pull requests), and update Ember on the client. Then dev will be in master. I'd say in the next month or so this will all be updated.

**Comment by lancejpollard** [comment]
This is fixed in dev. It's all working, try it out and let me know!
