### ISSUE TITLE
@scope doesn't work when drawing routes

### ISSUE THREAD

**Issue by scottkf** [tower-archive/tower#175]
``` javascript
@scope '(:locale)', ->
  @resources "articles"
```

The routes are drawn ignoring the scope, I haven't looked into it yet, though I will

**Comment by juanpaco** [comment]
I was looking into this one today.  When a route is ultimately drawn in tower-net/route/dsl.coffee, it checks for the current scope's path member.  Only that member is never set anywhere in the file.  You can fake it by doing something like:

@scope path: "api"

but then nesting becomes a problem.  There's also code in the dsl file checking @_scope.name, but that member is also never set.

I mean, it _looks_ like it could be as simple as modifying that scope function to build the scope properly, but as I've spent all of 1 hour looking at the code, there may be ramifications I'm missing.

Has anyone else done any work on this issue?  I'm happy to look into it some.  I really don't want to have to define all of my scope manually.
