### ISSUE TITLE
Re-Using views on the client/server

### ISSUE THREAD

**Issue by scottkf** [tower-archive/tower#176]
Per that stackoverflow question about railway/tower, do you have an example of re-using a template on the client and the server?

**Comment by lancejpollard** [comment]
I haven't checked in a while (gearing up for merging dev into master, and things are somewhat different), but there is a `public/javascripts/app/views/templates.js` that gets generated with all of your views compiled in there. They can be used in a controllers render method like you would on the server, just make sure templates.js is loaded in a script tag (or add to config/assets.coffee, /app/views/templates.js). You can use it with render like:

``` coffeescript
class App.PostsController extends Tower.Controller
  index: ->
    App.Post.all (error, posts) =>
      @render 'index', locals: {posts}
      # also may want to try these:
      # @render 'posts/index', locals: {posts}
      # @render 'app/views/posts/index', locals: {posts}
      # @render 'index', locals: {posts}, (error, body) => $('#container').append(body)
```

The templates are all stored in `Tower.View.cache`.

**Comment by scottkf** [comment]
I'll give this a try if I can get routing working temporarily, or when you get it working. Thanks!

**Comment by lancejpollard** [comment]
Just pushed a lot of new stuff to dev, rendering now works pretty differently (same API, but I don't think this issue is relevant with the new code). If you're still having issues with this let me know. Closing for now.

**Comment by scottkf** [comment]
The only issue I've seen with a new project is the root view won't display, does it need a view?

``` coffeescript
App.IndexView = Ember.View.extend
  templateName: 'welcome'
```

Variations of that didn't really work
