### ISSUE TITLE
can't get "@request.user" using everyauth

### ISSUE THREAD

**Issue by lumin3000** [tower-archive/tower#18]
after login from login page,  the controller cant get "@request.user" when redirecting.

I don't know is there any conflict with this “@use Tower.Middleware.Router” ?
since everyauth has this warning:   (https://github.com/bnoguchi/everyauth)

 // IMPORTANT!!!!!!! Do not add app.router, to your middleware chain 
        // explicitly, or you will run into problems accessing `req.user`
        // i.e., do not use app.use(app.router). Let express do this for you
        // automatically for you upon your first app.get or app.post.

still work on this problem, any suggestion welcome.

**Comment by lancejpollard** [comment]
Can you paste me the code you're using to integrate everyauth into Tower?

We are actually using everyauth in a project with Tower, here's how it's been integrated:

``` coffeescript
class App extends Tower.Application
  @configure ->
    @use "favicon", Tower.publicPath + "/favicon.ico"
    @use "static", Tower.publicPath, maxAge: Tower.publicCacheDuration
    @use "profiler" if Tower.env != "production"
    @use "logger"
    @use "query"
    @use "cookieParser", Tower.cookieSecret

    @use "session",
      secret: Tower.sessionSecret
      cookie:
        domain: ".#{Tower.cookieDomain}"
      store: new (require('connect-mongo')(Tower.Store.MongoDB.config[Tower.env]))

    @use "bodyParser"
    # @use "csrf"
    @use "methodOverride", "_method"
    @use Tower.Middleware.Agent
    @use Tower.Middleware.Location

    #if Tower.httpCredentials && Tower.branch != "development"
    #  @use "basicAuth", Tower.httpCredentials.username, Tower.httpCredentials.password

    @use everyauth.middleware()
    @use Tower.Middleware.Router
```

Then I have this code in `config/initializers/authentication.coffee` (all files from `config/initializers` are loaded before the `App.configure` block is executed:

``` coffeescript
everyauth.everymodule.findUserById (userId, callback) ->
  App.User.find userId, callback

everyauth.everymodule.handleLogout (request, response) ->
  # Put you extra logic here
  request.logout() # The logout method is added for you by everyauth, too

  # And/or put your extra logic here

  response.writeHead 303, 'Location': @logoutRedirectPath()
  response.end()

everyauth.everymodule.logoutPath('/logout')
everyauth.everymodule.logoutRedirectPath('/')

everyauth.facebook
  .appId(Tower.secrets.facebook.key)
  .appSecret(Tower.secrets.facebook.secret)
  .handleAuthCallbackError((request, response) ->
    # If a user denies your app, Facebook will redirect the user to
    # /auth/facebook/callback?error_reason=user_denied&error=access_denied&error_description=The+user+denied+your+request.
    # This configurable route handler defines how you want to respond to
    # that.
    # If you do not configure this, everyauth renders a default fallback
    # view notifying the user that their authentication failed and why.
  ).findOrCreateUser((session, accessToken, accessTokExtra, fbUserMetadata) ->
    # find or create user logic goes here
    promise = new everyauth.Promise
    App.User.findOrCreateFromFacebook(fbUserMetadata, promise)
    promise
  ).redirectPath('/')
```

In short, I think you just need to add the middleware `everyauth.middleware()` just before `Tower.Middleware.Router`.  Tower does not use express' `app.router` code.

Let me know if that helps.

**Comment by lumin3000** [comment]
I am transfering my old code to tower. mongoose-auth is the mongoose version everyauth also from @bnoguchi 

here is the app/auth.coffee:

``` coffeescript
mongoose= require "mongoose"
db = require('../config/databases.coffee').mongodb[Tower.env]
mongoose.connect "mongodb://#{db.host}/#{db.name}"
Schema = mongoose.Schema
mongooseAuth = require "mongoose-auth"
UserSchema = new Schema {}
UserSchema.plugin mongooseAuth,
  everymodule:
    everyauth:
      User: ->User
  password:
    loginWith: "email"
    extraParams:
      name: String
    everyauth:
      getLoginPath: "/login"
      postLoginPath: "/login"
      loginView: "login.jade"
      getRegisterPath: "/register"
      postRegisterPath: "/register"
      registerView: "register.jade"
      loginSuccessRedirect: "/loggedin"
      registerSuccessRedirect: "/registed"

mongoose.model "User", UserSchema
User = mongoose.model "User"
exports.mongooseAuth = mongooseAuth
```

and the config/application.coffee

``` coffeescript
auth = require('../app/auth')
mongooseAuth = auth.mongooseAuth
class Market extends Tower.Application
  @configure ->
    @server.set 'views', './app/views' 
    @use "static",  Tower.publicPath, maxAge: Tower.publicCacheDuration
    @use "profiler" if Tower.env != "production"
    @use "logger"
    @use "query"
    @use "cookieParser", Tower.cookieSecret
    @use "session", secret: Tower.sessionSecret, cookie: {domain: ".#{Tower.cookieDomain}"}
    @use "bodyParser"
    @use "methodOverride", "_method"
    @use Tower.Middleware.Agent
    @use Tower.Middleware.Location
    @use mongooseAuth.middleware()
    @use Tower.Middleware.Router
```

and the router:

``` coffeescript
  @match "/loggedin",to: "application#loggedin"
  @match "/registed",to: "application#registed"
  @match "(/*path)", to: "application#index"
```

everything fine with the /login until i can not get @request.user or @session.auth at applicationController.coffee

``` coffeescript

class Market.ApplicationController extends Tower.Controller
  @layout "application"
  loggedin: ()->
    console.log @request.user
    console.log @session
    Market.createSession @request,@response,()=>
      @redirect "/"

```

**Comment by lancejpollard** [comment]
Hmm… I'm not sure without seeing the full app.  It seems like it's probably because the session/secret key that everyauth sets in the session isn't being properly carried between requests, that's my guess.

I'd just console.log the request at every stage and make sure the cookies/session/headers/request are all what you'd expect, and that the proper secret token is carried between requests (I haven't messed with everyauth in a couple months, but I think they're setting some session variable here, and I've had trouble with that before).

Along those lines, mess around with `@use "session", secret: Tower.sessionSecret, cookie: {domain: ".#{Tower.cookieDomain}"}` because that's where the something could start going wrong with session.

I don't think this is a problem with tower, it doesn't do anything with a `request.user` variable.  But I'll keep this in mind and get back to you if I find anything.

**Comment by lumin3000** [comment]
I am testing tower since i do this with other express kind framework:
Is that I cant set value to @request or @session like this? or what I am doing is something wrong?

a "Tower new app" and do this:

``` coffeescript
class Towertest.ApplicationController extends Tower.Controller
  @layout "application"

  test: ->
    console.log @request.user #undefined
    console.log @session #auth undefined
    @render template: "index"
  index: ->
    @session.auth=100
    @request.user = 'sjerrys'
    console.log @request.user #ok
    console.log require('util').inspect @session #ok
    console.log "done"
    @response.redirect '/test'
```

**Comment by lancejpollard** [comment]
Yeah you can't do that because when you do a redirect, the current action is completed - the browser gets a 302 redirect response, and changes the url.  Since the url is changed, it's going to run through the middleware all over again and go to the new controller action for that url.

The [connect session](http://www.senchalabs.org/connect/middleware-session.html) parses the session and cookies for each request from the raw request.  So the only thing that will persist after a redirect is the raw session and cookie data, which you can set like this:

``` coffeescript
@session.cookie.expires = new Date(Date.now() + 3600)
```

Looks like you then have to save the session data (I haven't used this in a while, but from [http://www.senchalabs.org/connect/middleware-session.html](http://www.senchalabs.org/connect/middleware-session.html)):

```
@session.save()
```

That will save any custom properties on your session.

**Comment by lumin3000** [comment]
I found the reason why the session and everyauth is not working:

in config/application.coffee

``` coffeescript
@use "session", secret: Tower.sessionSecret, cookie: {domain: ".#{Tower.cookieDomain}"}
```

if I didn't set a right value for domain, the session cookie will fail to set.

everything goes great after I set the domain OR just delete cookie: {domain: ".#{Tower.cookieDomain}

**Comment by kristianmandrup** [comment]
Would be nice with a complete example on setting up authentication with Tower.
