### ISSUE TITLE
Reduced install overhead

### ISSUE THREAD

**Issue by krainboltgreene** [tower-archive/tower#182]
Is there someway to reduce the time required to install tower.js via npm? Does it really need all of those dependencies?

**Comment by lancejpollard** [comment]
Yeah we need to work on this. One of the big things is forever/hook.io/design.io, I think forever or one of those installs a ton of things.

Also, the after hook for the custom coffeescript installation takes a while, not sure why (I think it may be compiling or something). We can fix this by making it so the npm version of tower is pure JS (compiled coffeescript).

Will work on this in the next few weeks, let me know if you find anything.

**Comment by krainboltgreene** [comment]
Yeah, this is directly related to #187. I'll see what I can't chop out.
