### ISSUE TITLE
Sugar.js release

### ISSUE THREAD

**Issue by krainboltgreene** [tower-archive/tower#184]
Sugar.js just released, and it has some pretty awesome helper functions that would probably work really well in Tower.js:

http://sugarjs.com/

Perhaps consider including it in the package?

**Comment by lancejpollard** [comment]
Sugar.js is pretty cool (especially since it basically brings Ruby's ActiveSupport to JavaScript), but I don't think Tower should advocate extending core objects since it's generally not accepted best-practice in the JavaScript community. Instead we should make this all available as underscore helpers.

I got into trouble with extending core objects in Ember and found jQuery has decided as a team they won't help with bugs that arise from that:
- https://github.com/emberjs/ember.js/issues/1169
- http://docs.jquery.com/Won't_Fix#Object.prototype_Issues
- http://erik.eae.net/archives/2005/06/06/22.13.54/

Instead, we should have a page on the website/wiki for "useful" plugins/modules that includes this one.

**Comment by krainboltgreene** [comment]
Apparently the core maintainer of Sugar.js has found a way to avoid problems with JQuery and Ember. He/she seems highly certain it won't make problems. That said, I'll give i a shot and make a PR to see how it works out later.

**Comment by lancejpollard** [comment]
Sounds good.

**Comment by edubkendo** [comment]
@viatropos @krainboltgreene have you guys seen https://github.com/epeli/underscore.string ? While it doesn't provide nearly the range of awesomeness that sugar.js provides, it does extend underscore quite a bit, and could be a good start on building TowerSupport ＼(^o^)／ , without fooling around with core objects. For what its worth, sugar seems to be about as safe as you can get, as far as extending these go.  That said, I think we should be extremely careful of adding anything to Tower that would be a majorly divisive issue within the community, fly in the face of established best practices, etc. What we don't want to create is a situation where people say of Tower something like, "Yeah, it looks cool but it extends core objects so..." without having very good reasons for doing so (ie. it adds some enormous benefit that can't be gotten any other way). It seems to me that the way to move forward would be A) create a plugin/module that makes it easy for people to add sugar.js to their tower projects, without putting sugar.js in tower itself B) begin/continue work on building Tower.Support through extending the _ object.

**Comment by krainboltgreene** [comment]
I agree and disagree. On one hand I say, "fuck em, sugar makes JavaScript less of a supreme pain." and on the other...adoptability Is paramount for Tower right now.  

## 

Kurtis Rainbolt-Greene
Difference Engineers
643 Magazine St STE #102,
New Orleans, LA 70130
202-643-2263

**Comment by lancejpollard** [comment]
For the record I personally don't mind extending core objects, that's commonplace in Ruby and a big reason why you can create such clean apis in it. The main reason (from that old [link](http://erik.eae.net/archives/2005/06/06/22.13.54/) above, and others), is in certain edge cases you ultimately run into, it causes JavaScript not to work like you'd expect, and some plugins/modules might have been built upon that edge case working a certain way.

I'll take a look at how Sugar.js avoids this in a few days, would be interesting to see how they avoid problems. 

But the main thing is that, while they may have figured out ways to prevent problems, if we were to advocate extending core objects, people would eventually write code that causes problems. I'm going with the jQuery (and "JavaScript community in general"'s) decision to not do this, b/c you know they probably debated about it for years and thought about implications in a ton of different browsers. We should definitely have a good reason why ourselves as well, and create a page in the docs/site that outlines why we came to this decision.

Ideally the docs will have clear descriptions of all the ways we thought about how to implement something and the pros and cons of each and why we chose what we did in the end. This is one thing I would have loved to have while learning to code, it would have saved a ton of time.

In terms of finding the cleanest API, there's no doubt that sugar has a better api than underscore. I was going to use sugar when tower first started b/c of that. But sticking to the principle "never extend core objects" left me to try and get the same API joy out of underscore, and I have. The API is not that much different:

```
2.days().ago()
_(2).days().ago()
```

Plus you know "all helper methods are on the `_` object". It's clean, and it keeps the code super organized.

Maybe down the road, after everything else is working well and we've had a lot of time to write down the pros and cons of extending core objects, we can make a module that extends prototypes that you can opt into (someone will eventually make this anyway). But for now let's go by the principle "no extending core objects", just do underscore helpers.

@edubkendo we're using that underscore.string library in tower already! :) so happy somebody made that.

There's a ton of string and other helpers in here as well (and plenty of room for optimization). Check it out:
- a bunch of helpers for dates, checking if strings match common formats, formatting currencies and numbers, sanitizing strings (xss), and inflection... and soon some sort of string masking functions (to aid in form [input masking](http://digitalbush.com/projects/masked-input-plugin/)): https://github.com/viatropos/tower/blob/master/src/tower/support/format.coffee (added with `_.mixin` at the bottom)
- and underscore.string! https://github.com/viatropos/tower/blob/master/src/tower/server.coffee#L4
- side note, all the other ./support/*.coffee code (also underscore helpers) is in need of refactoring as well

There's a lot that needs to be done with those, simple stuff such as I think you can only use `days` on dates, but we need to add:

``` javascript
_(2).seconds().ago()
_(2).minutes().ago()
// hours, weeks, months, years, beginningOfSecond, endOfSecond, beginningOfMinute, etc...
// and a lot of other nice things from active_support/core_ext
```
