### ISSUE TITLE
Twitter Bootstrap, Underscore, ect

### ISSUE THREAD

**Issue by krainboltgreene** [tower-archive/tower#187]
While I like having all of these things built in I think it might be better to build a Javascript version of Vendorer and then have a premade Vendorfile that downloads them correctly. Reduce the overhead on install/new, reduce code in source.

**Comment by lancejpollard** [comment]
Yeah, we definitely should reduce the amount of code downloaded for a new app, what's there now is temporary. Haven't seen [Vendorer](https://github.com/grosser/vendorer) before, interesting idea. I'm down for that.

I've also been thinking about moving something like [cached-commons](https://github.com/viatropos/cached-commons) to node, making it work like the NPM registry or rubygems.org, so in the end there's a standard way of pushing your (any) JavaScript library to this CDN ([cdnjs](http://cdnjs.com/) is doing a similar thing). The issue with those two now are they require manual intervention - they should work like `gem` or `npm`, e.g.:

```
cdn install jquery # install jquery
cdn publish # publish the library the current directory
cdn list
...
```

It can work off of package.json. It should be straightforward (and fun) to implement, really want to see this implemented at some point. It can use [cloudflare](https://www.cloudflare.com/overview) to freely cache the libraries.

In the end, this would mean you really can do without downloading any libraries, making your source code that much more lean (the same way most people I think don't download jQuery, just point to google's hosted version).

The vendorer solution might be easier/faster to implement, maybe we should create a roadmap?

**Comment by krainboltgreene** [comment]
First iteration like vendorer, second iteration like you describe? Sounds good to me. Wiki the roadmap?

**Comment by lancejpollard** [comment]
Sounds good! An older roadmap is in the docs: https://github.com/viatropos/tower-docs/blob/master/en/roadmap.md, will move that back to the wiki soon.

**Comment by lancejpollard** [comment]
Bower is now taking care of this: http://twitter.github.com/bower/

**Comment by krainboltgreene** [comment]
Aweeesome!

On Tue, Sep 25, 2012 at 9:19 PM, Lance Pollard notifications@github.comwrote:

> Bower is now taking care of this: http://twitter.github.com/bower/
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/viatropos/tower/issues/187#issuecomment-8876900.

## 

Kurtis Rainbolt-Greene, Hacker
Difference Engineers, LLC
1631 8th Street
New Orleans, LA 70115
