### ISSUE TITLE
Scaffold not working. 

### ISSUE THREAD

**Issue by manaberg** [tower-archive/tower#188]
http://localhost:3000/officers/501610d9c34d145610000001

That's the URL my browser points to when I try to Destroy a Officer.

I generated officers through tower generate scaffold name:string rank:integer

The routes have been generated by the resources in config/routes.

The line makes sense: 
<code>linkTo 'Destroy', urlFor(officer), "data-method": "delete"</code>

But for some reason it is not working. It ends up in the URL I posted at the beggining of the post and also displays the officer data.

**Comment by edubkendo** [comment]
I've used scaffolding successfully, with some instructions here: https://github.com/edubkendo/demoApp and destroy has always worked. Of course, destroy/delete is handled by javascript on the client side . Your client side controller should look something like this: 

``` cofeescript

class App.PostsController extends Tower.Controller
  @on "click .post a[data-method='delete']", "destroy"

  # example
  destroy: (event) ->
    row       = $(event.target).closest('[data-id]')
    id        = row.attr('data-id')

    try
      @resourceKlass().destroy id, (error, resource) =>
        row.remove()
    catch error
      console.log error

    false
```

Did you alter the client-side controllers, also, what did you type in the terminal to generate your scaffold? Correct syntax is something like:

```
tower generate scaffold User email:string firstName:string lastName:string hasMany:posts
```

Anyways, those are the first two things I can think of, also, is javascript enabled in your browser? I feel like that's an obvious question but thought I'd ask anyways.

Edited to clarify: That client-side code is what the scaffold should have generated, and that is what actually handles the deletion.  If you didn't alter it, verify that it was generated by the scaffold generator.

**Comment by lancejpollard** [comment]
+1 what @edubkendo wrote

**Comment by edubkendo** [comment]
@viatropos using the development branch of tower, I run into this same issue. When I looked into it, for whatever reason, the client side controller code was not generated by the scaffold, only 

``` coffeescript
class App.UsersController extends Tower.Controller
  @scope 'all'
```

When I copy the above-referenced code into the controller then it works as expected.

**Comment by manaberg** [comment]
That is what happened to me.  regenerating the scaffold was the only solution.

**Comment by lancejpollard** [comment]
The generator has been updated and is using ember, a lot of this has changed. Try it out and let me know if this is still an issue.

**Comment by manaberg** [comment]
Just to clarify this is no longer an issue :)
