### ISSUE TITLE
App generator should apply application name to database config by default

### ISSUE THREAD

**Issue by activestylus** [tower-archive/tower#19]
Small detail but I find its a sensible default: "undefined-production", "undefined-development", etc should be "myappname-production"

**Comment by winfred** [comment]
Hmm, I can't replicate this with the most recent code. I dunno about the npm package, but it's probably best to use dev code and help out while the project is still still <1.0.

Do you still see this after npm linking to a local tower dev branch?

**Comment by activestylus** [comment]
Running this on edge does indeed fix the issue. Cheers!
