### ISSUE TITLE
Select element on form 

### ISSUE THREAD

**Issue by DavidDufresne** [tower-archive/tower#191]
I tried to create a select form element as in the example on http://towerjs.org/views#forms , but selectInput is not defined in src/tower/view/form/field.coffee .  Is the the documentation incorrect?

**Comment by lancejpollard** [comment]
Yes I think the documentation for views is out of date. A lot of the view stuff is going to be changing in the weeks ahead, stay tuned. For now I recommend just using plain tag helpers for coffeecup (or ECO/EJS).
