### ISSUE TITLE
anyIn against a `string` field

### ISSUE THREAD

**Issue by scottkf** [tower-archive/tower#192]
This may be user error, but, lets say we have a model called `Test` with a `@field 'example', type: 'String'`

``` coffeescript
t = App.Test.create(example: 'test')
App.Test.anyIn(example: ['test', 'fail']).all() # 0 results, whereas the following yields the correct results
App.Test.anyIn(example: ['test']).all() # 1 result, t from above
```

Is that not the correct way to use anyIn? What's happening is that the array of conditions is getting cast to a string here: https://github.com/viatropos/tower/blob/development/packages/tower-store/server/mongodb/serialization.coffee#L134-149

**Comment by scottkf** [comment]
To fix it the encode method would have to be something like this: 

``` coffeescript
  encode: (field, value, operation) ->
    return value unless field

    method = @["encode#{field.encodingType}"]
    if _.isArray(value)
      value = (method.call(@, v, operation) for v in value)
    else if method
      value = method.call(@, value, operation)
    value = [value] if operation == '$in' && !_.isArray(value)
```

**Comment by lancejpollard** [comment]
Yeah, I don't think we have landed on a clear set of cases this method should support, we should do that. What do you think?

**Comment by scottkf** [comment]
Sounds good, but wouldn't this only come up where the value (the function parameter) was an array? Mongo doesn't really expect any other values, right? Only an array, a hash, or a value? And it looks like the hashes get ripped apart and encoded separately

**Comment by lancejpollard** [comment]
Yeah, but we don't necessarily have to stick to mongo's api since tower's api will be the same for every database (once they are supported). We can add those extra things that make intuitive sense.

**Comment by scottkf** [comment]
Good point, as I use tower more I'm sure I will come across things

**Comment by lancejpollard** [comment]
Hey @scottkf if you get a chance (and you're not already) checkout the development branch and test it out, I'm planning on merging it this week or the next and publishing all the new stuff. Thanks man.
