### ISSUE TITLE
Github image link on Towerjs.org is broken

### ISSUE THREAD

**Issue by eranation** [tower-archive/tower#197]
This image is a broken link (on the front page of Towerjs.org)

https://a248.e.akamai.net/assets.github.com/img/4c7dc970b89fd04b81c8e221ba88ff99a06c6b61/687474703a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f72696768745f77686974655f6666666666662e706e67

**Comment by Zearin** [comment]
:+1: Yup. For a while now.
