### ISSUE TITLE
Enhancement request: Towerjs.org - add example how to start a tower.js server

### ISSUE THREAD

**Issue by eranation** [tower-archive/tower#198]
Is it 

node server.js? 
tower server? 

it's not written (in laymen terms) anywhere I could find

**Comment by lancejpollard** [comment]
Thanks for pointing out, updating the docs for the next release. Use:

```
node server.js
```

**Comment by maedi** [comment]
Is it possible to create an alias "tower server" too? Coming from Rails, was my main point of confusion when first trying Tower.

By the way "node server" also works for me.
