### ISSUE TITLE
Cake not working: Tower module not found

### ISSUE THREAD

**Issue by activestylus** [tower-archive/tower#20]
For some reason I cannot run any of the cake commands:

```
> cake coffee
node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: Cannot find module 'tower'
    at Function._resolveFilename (module.js:334:11)
    at Function._load (module.js:279:25)
    at Module.require (module.js:357:17)
    at require (module.js:368:17)
    at Object.<anonymous> (/Users/me/Desktop/Code/node/apps/wordup/Cakefile:4:3)
    at Object.<anonymous> (/Users/me/Desktop/Code/node/apps/wordup/Cakefile:44:4)
    at Module._compile (module.js:432:26)
    at Object.run (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/coffee-script.js:68:25)
    at Object.run (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/cake.js:48:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/coffee-script/bin/cake:7:38)
```

I can create apps and generate scaffolds with no problem. I can also start the server.

Note: I also checked out the towerjs website demo app and experienced the same error. I reinstalled both towerjs and coffeescript via NPM but no luck

**Comment by activestylus** [comment]
I fixed this error by installing npm package within my app. It is worth mentioning that the first time failed because the generated app did not include knox in the package.json

Now I am facing the problem of missing cake task. I had assumed that the coffee an spec tasks were included in core but when I try to run them cake complains

```
cake coffee
No such task: coffee
```

Was looking at the towerjs demo app and the Cakefile is the same as mine. What am I missing?

**Comment by CoderBounty** [comment]
A bounty has been placed on this issue, check it out at Coder Bounty! http://coderbounty.com/#14

**Comment by lancejpollard** [comment]
Are you trying to compile the coffee-script files for tower itself (for developing/testing the tower source)?

Those tasks are included here:

https://github.com/viatropos/tower/blob/master/Cakefile#L189

I am not using those anymore though, I'm just using [design.io](https://github.com/viatropos/design.io) to compile everything (coffeescript, css, etc.).

If you are trying to compile the assets for a generated tower app, then this is out of date (I will update the docs and towerjs.org with this).  There is no task named `coffee` anymore, that was the old way of compiling assets.

To compile the assets, you need to use design.io, or write your own watch script (something like `coffee --watch --compile --output public/ ./`).  The design.io readme tells you how it works.

In the latest push of tower, design.io should be running by default when you run:

```
node server
```

Let me know if that helps.

**Comment by activestylus** [comment]
Yes running `node server` does indeed fire up design.io. I can even see my changes taking place in realtime in the console. The only problem is that I dont see these changes when I look at the browser, no matter how many times I reload or clear the cache. Here's what happens when I edit a page title from "New Site" to "New Sitez"

```

[Sat, 03 Mar 2012 12:06:47 GMT] INFO updated app/views/sites/new.coffee
info:  Name: design.io-watcher::wordup exec                                     Type: hook            Data: {"body":"contentFor \"title\", \"New Sitez\"\n\npa ... 
info:  Name: design.io-watcher::wordup-0 design.io-watcher::wordup-0::exec        Type: hook            Data: {"body":"contentFor \"title\", \"New Sitez\"\n\npa ... 
[Sat, 03 Mar 2012 12:06:48 GMT] INFO updated public/javascripts/app/views/templates.js
  Processing by SitesController#new as HTML
  Parameters:
{ format: null, action: 'new' }

  GET /sites/new
  response time: 42ms
  memory rss: 3.94mb
  memory vsize: NaNgb
  heap before: 16.09mb / 18.12mb
  heap after: 18.51mb / 22.22mb
```

**Comment by activestylus** [comment]
I've pushed a copy of my test app to github so you can have a poke at it: https://github.com/activestylus/towerjs-test

**Comment by activestylus** [comment]
I neglected to add that if I restart the tower server, I can see my changes in the browser. Let me know if you need any other info

**Comment by activestylus** [comment]
I am closing this issue and starting a new one to address the current problem since the original issue has been resolved

**Comment by CoderBounty** [comment]
activestylus, you have won a bounty at Coder Bounty!  Login and verify your Github username to claim it.  http://coderbounty.com
