### ISSUE TITLE
Using ember: computed property within model doesn't properly resolve

### ISSUE THREAD

**Issue by scottkf** [tower-archive/tower#200]
``` coffeescript
class App.Profile extends Tower.Model
  @hasMany 'ownerships'#, embed: true
  @field 'name', type: 'String'

  playedCount: Ember.computed ->
    @get('ownerships').count()
  .property('ownerships')

script type:'text/x-handlebars', 'data-template-name': 'profileStatsView', ->
  text '{{#with App.profilesController}}'
  dt 'name'
  dd '{{unbound profile.name}}' 
  dt  'Count'
  dd '{{unbound profile.playedCount}}

```

Name correctly shows up, but, playedCount shows up as [object Object]. It seems like ember is just taking the function and not evaluating it. Even if I remove the `@get ownerships` and just change it to `return "hello"`, it still doesn't evaluated. Any ideas offhand?

**Comment by scottkf** [comment]
If instead of defining playedCount as a function, I do this:

``` coffeescript
@field 'playedCount',
  get: (value) ->
    return @get('ownerships').count()
```

I receive the correct results, so there must be a bug in [class.coffee](https://github.com/viatropos/tower/blob/master/src/tower/support/class.coffee)? Or maybe something else weird with the installation

**Comment by edubkendo** [comment]
@scottkf if I do:

``` coffeescript
class App.Message extends Tower.Model
  @field 'user', type: 'String'
  @field 'body', type: 'String'

  userAndBody: Ember.computed(->
    user = @get('user')
    body = @get('body')
    return "#{user}: #{body}"
  ).property('user', 'body')
```

Then go to the console and do:

``` javascript
messages = App.Message.find()

message = messages.objectAt(0)

message.toJSON()

/* body: "Hello there how are you today?"
createdAt: "2012-08-20T16:11:50.414Z"
gistId: undefined
id: "503261c67c7a2e8e22000002"
updatedAt: "2012-08-20T16:11:50.413Z"
user: "e_dub"
__proto__: Object */

message.get('userAndBody')

// "e_dub: Hello there how are you today?"
```

As you can see, it works, but it only shows up when I specifically call it. It doesn't seem to exist as part of the object, at least represented as JSON, I guess because its a function?

Also, notice I wrap the function that I pass to Ember.computed in parens. Not sure why, or whether this matters here, but in my current rails/ember project I get errors if I don't, so I went ahead and did that here. Might be worth a try.

**Comment by edubkendo** [comment]
Just realized what you are doing is a bit more complex, involving counts on relationships. Going to play with this a bit more and see if it holds up or fails on me.

Edit:
Nope, still working for me. If I do:

``` coffeescript
class App.User extends Tower.Model
  @field 'email', type: 'String'
  @field 'firstName', type: 'String'
  @field 'lastName', type: 'String'

  @hasMany 'posts'

  postcount: Ember.computed(->
    return @get('posts').count()
  ).property('posts')
```

And in the browser console:

``` javascript

users = App.User.find()

user = users.objectAt(1)

user.toJSON()

/* createdAt: "2012-08-20T16:34:12.353Z"
email: "bob@bob.com"
firstName: "bob"
id: "503267041de1182223000001"
lastName: "bob"
updatedAt: "2012-08-20T16:34:12.353Z"
__proto__: Object */

user.get('postcount')

// 2
```

Still works. Not sure why you are having troubles. I'm running the development branch of tower, though, and just realized I'm not sure if you are or not.

Edited Again:
Ok, so I modified show.coffee to see if it would render properly in the browser... nope. Nothing shows up. Obviously the variable is available, so this may be something you hack in to make available in the view. Going to experiment some more to see what's up.  Seems pretty odd to me.  If this is what you were getting at all along, sorry.

**Comment by scottkf** [comment]
Yes, I could've been a little more detailed, but essentially it's not showing up in the browser, I haven't looked into it more yet. This is on the development branch

**Comment by lancejpollard** [comment]
@scottkf Not sure what this is, but it seems like it's one of these:
- What's your Ember version for the client? Maybe this is out of date
- What does the generated JavaScript look like for profile.coffee? It may be the coffee-script branch is off.
- I haven't tested computable properties that observe associations (i.e. `.property('posts')`), so there may be some issue with that. Maybe try changing that to `property('name')` or some other "simple" property and see what happens.
- Just to make sure, you're using the generated tower@0.4.1 in `./dist/tower.js` from `cake build`?

That's all I can think of off the top of my head. Let me know if you figure it out.

**Comment by scottkf** [comment]
Ember's version is 1.0.pre, and javascript was correct, I checked a couple times to be sure :) tower.js is the latest as well, and checking to a simpler property had no effect as well. When creating a prototype function for a model in towerjs, it gets translated to

``` javascript
    Profile.prototype.playedCount = Ember.computed(function() {
      return this.get('ownerships').count()
    }).property('ownerships');
```

Where when using field, field gets all this fancy stuff: from `ModelAttribute`s constructor: 

``` coffeescript
    @_setDefault(options)
    @_defineAccessors(options)
    @_defineAttribute(options)
    @_addValidations(options)
    @_addIndex(options)
```

I'm going to guess it's somewhere there

**Comment by lancejpollard** [comment]
I see, so the generated code is this?

``` javascript
Profile.prototype.playedCount = Ember.computed(function() {
  return this.get('ownerships').count()
}).property('ownerships');
```

If so, that's the issue. It means it's not using the custom coffee-script fork. Try running:

```
npm install git://github.com/viatropos/coffeecup.git --force
npm install git://github.com/viatropos/coffee-script.git --force
node server
```

The generated code should look like this:

``` javascript
__defineProperty(Profile,  "playedCount", Ember.computed(function() {
  return this.get('ownerships').count();
}).property('ownerships'));
```

**Comment by scottkf** [comment]
This corrected the behavior assuming I use the following definition:

``` coffeescript

  playedCount: Ember.computed ->
    return @get('ownerships').count()
  .property('ownerships')
```

Though it would be convenient, for people new with ember and tower, for Tower to be able to use the simple definition without using Ember.computed and .property. Or maybe just document that you need to use @field or Ember.computed when dealing with views.

**Comment by lancejpollard** [comment]
> Though it would be convenient, for people new with ember and tower, for Tower to be able to use the simple definition without using Ember.computed and .property.

What did you mean by this? Not quite sure...

On another note, we are going to start having a new api for defining models that works similar in convention to ember and other javascript libraries. It's going to be the default API, and you can opt-into the coffeescript/executable-class-bodies version if you'd like.

So something like this will be the API:

``` coffeescript
App.User =  Tower.Model.extend
  email:    Tower.field('string')
  posts:    Tower.relation('hasMany')

# the above will be equivalent to this:
class App.User extends Tower.Model
  @field 'email'

  @hasMany 'posts'
```

The two main reasons for this are:
- it will be usable purely in JavaScript (executable class bodies are tedious to write without coffeescript)
- you won't be required to use the custom fork of coffeescript

The full "JavaScript API" needs to be fleshed out (defining validations, callbacks, etc.), but it should be straightforward. Note though, the coffeescript api will still exist, but it is probably going to require a command line flag when generating a new app, such as `tower new app --coffee-classes` or something.

If you guys would like to help I have started hacking away on this in the `javascript-api` branch.
