### ISSUE TITLE
Sort REST API results

### ISSUE THREAD

**Issue by vegarituwall** [tower-archive/tower#201]
Executing:

.json?sort=createdAt- and .json?sort=createdAt+ return the same results.

**Comment by lancejpollard** [comment]
This works if you send the data as JSON:

``` javascript
// the serialized version of this:
'/posts.json?{sort: ["createdAt", "desc"]}'
// this is done using something like this:
encodeURI(JSON.stringify({sort: ["createdAt", "desc"]}))
// which looks like this:
"%7B%22sort%22:%5B%22createdAt%22,%22desc%22%5D%7D"
```

Need to handle the case where it's a human-readable url.

**Comment by vegarituwall** [comment]
Hi Lance,

I have been trying to get the sorted list and I get random errors, for 
example when I try the encoded version of:

/posts.json?{%22sort%22:[%22createdAt%22,%22desc%22]}

it redirects me to:

/posts.json?{%22sort%22:[%22createdAt%22,%22desc%22]}

Any clues of what is going on?

## 

JV

**Comment by lancejpollard** [comment]
I just posted that from memory (pseudocode). You can see the actual queries generated in the web inspector's "Network" tab (in Chrome), when you do things like this:

``` javascript
App.Post.where('title', 'Y').desc('createdAt').fetch()
```

The network tab is saying the `/posts` url is this:

```
http://localhost:3000/posts?sort%5B0%5D%5B%5D=createdAt&sort%5B0%5D%5B%5D=desc&conditions%5Btitle%5D=Y&format=json
```

Not sure how this is serializing exactly, it's done by jQuery.
