### ISSUE TITLE
Lazily connect web sockets so it's non-blocking

### ISSUE THREAD

**Issue by lancejpollard** [tower-archive/tower#206]
Right now it sometimes causes the page to feel like it's taking a while to load, when it's really just trying to establish a socket connection. This should not be affecting page load/rendering performance.

**Comment by d4tocchini** [comment]
Unless the cure is trivial, could be a use case for Web workers so waiting for connection doesn't block main thread

**Comment by edubkendo** [comment]
I am just guessing this is related, but on most page-loads, using Chrome, I get:

```
http://localhost:4181/socket.io/1/?t=1345548330232

Failed to load resource
```

**Comment by lancejpollard** [comment]
Yeah this is actually the real issue. That means you need to run `design.io start` in some other terminal window, which will start the socket server for live updates.

But... design.io is bulky and old school, we made it before the node watcher really worked, and before tools like Grunt.js, etc. We need to get rid of it and build/integrate something simpler/faster. I think design.io was one of my first node modules, and I've learned a lot since then.

We should try out grunt. But to get live updates, I think the easiest thing will be to refactor design.io so it:
1. doesn't use ruby, just node
2. works on windows (in addition to mac/linux)
3. doesn't use a separate server, has access to the same environment as your running tower app.

We were trying to be too ambitious with it up front, making it so you could have 1 global socket server and could register any number of "projects" (directories) to be watched which could reuse the same socket server. It requires too much magic, and in order to make it be performant, it would require a lot more time and effort. Eventually we may end up there, but for now we need to simplify this a lot. Design.io is one of the main things causing problems getting started.

I want to work on this as soon as possible.

**Comment by activestylus** [comment]
Hey Lance, glad to hear you are moving on this.

It is hard for me to comment on node based build systems as I rely on Sprockets + LiveReload

I do agree that keeping it all js based is the smart thing to do, and YES you should minimize any dependencies.

What I can do this week is play around with grunt and a few others and give you some feedback.

**Comment by activestylus** [comment]
A little inspiration for you - yes its Ruby but it appears to implement a simple middlewear which injects the free version of LiveReload into your scripts. It has worked pretty well for me - the memory usage is practically nil too.

https://github.com/guard/guard-livereload

**Comment by lancejpollard** [comment]
Man, grunt is awesome. Really enjoying it @activestylus. I just got the tower source working without design.io: 

https://github.com/viatropos/tower/blob/grunt/grunt.coffee

Going to try and get the whole build process down today, then see what it would take to make the generated apps use it too.

**Comment by edubkendo** [comment]
Whoa so I had completely forgotten about "design.io start" . Anyways, as far as grunt goes, +1 from me. This seems like it will reduce complexity and make it easier for people to get started using tower, which is great.

Anyways, the error I'm getting now is:

```
XMLHttpRequest cannot load http://localhost:4181/socket.io/1/?t=1345595074171. 

Origin http://localhost:3000 is not allowed by Access-Control-Allow-Origin.
```

**Comment by edubkendo** [comment]
Using the recent build of Tower with grunt upgrade, I'm not getting that error so that's awesome.

**Comment by lancejpollard** [comment]
Sweet!
