### ISSUE TITLE
SyntaxError: In /Volumes/FAT/Documents/development/tower/packages/tower-model/shared/locale/en.coffee, multiple object literal properties named "uniqueness"

### ISSUE THREAD

**Issue by scottkf** [tower-archive/tower#209]
In master, not sure which one you want to keep:

https://github.com/viatropos/tower/blob/master/packages/tower-model/shared/locale/en.coffee#L28-30

**Comment by edubkendo** [comment]
Similar error about the multiple "uniqueness" properties, this was when running "cake build": https://gist.github.com/3414073

**Comment by lancejpollard** [comment]
Let's keep the last one.
