### ISSUE TITLE
tower --port option not recognized

### ISSUE THREAD

**Issue by activestylus** [tower-archive/tower#21]
I used to be able to boot up my app like so: `tower --port 3000`

I have not touched my install or config at all, but now it just wont boot

```
error: unknown option `--port'
```

So I did the drastic thing and completely nuked my nodejs/npm install and started over. This time I installed v0.6.12 in my local dir and I can happily install modules without sudo, however I still cannot boot the tower server.

Sidenote: In the --help option for the tower command there is no mention of server or port. Pretty big thing to omit

**Comment by lancejpollard** [comment]
To boot the tower server, all you need to do is:

```
node server
```

You can also type (which is going to do the same thing as the above command, it's just here for consistency):

```
tower server -p 3000
```

Let me know if that works.

**Comment by activestylus** [comment]
Working. Thanks!
