### ISSUE TITLE
Custom routes aren't properly created within the client

### ISSUE THREAD

**Issue by scottkf** [tower-archive/tower#210]
`@match '/auth/:provider', to: 'oauth#provider', as: 'login'` for example is translated as:

``` json
:providerOauth: function (b,d){if(c&&d instanceof c){if(!d.hasOwnProperty("context"))return b.transitionTo(a);d=d.context}b.transitionTo(a,d)}
arguments: null
caller: null
length: 2
name: ""
prototype: Object
transitionTarget: "auth.:provider.callback"
```

I'm not sure if you're already aware of these issues, or are working on them, but I'll stop posting them if you do!

**Comment by lancejpollard** [comment]
No this is good, keep posting! Send pull requests as well, that would be super helpful. Thanks man.
