### ISSUE TITLE
A synchronous option for the console

### ISSUE THREAD

**Issue by scottkf** [tower-archive/tower#212]
Using async, node-fibers or a wrapper for it, like node-sync. Someone might have already implemented it with the REPL or commanderjs. Seems easy enough to wrap all commands in a fiber though. I'll look into it unless someone already has this implemented

**Comment by lancejpollard** [comment]
If you could do this that would be fantastic. All that really needs to happen is to wrap the core mongodb async calls in a fiber/future, the code in tower-store/server/mongodb. There's probably a few other filesystem/http async calls, but not much. Should be straightforward once node fibers are understood, let me know if you figure it out I'm interested.

**Comment by scottkf** [comment]
After wrapping the mongodbfinders calls in a future, how would you notify all of the models to use the new find method, do you have to reopen it? Or..

Something like this should work:

``` coffeescript
Future = require('fibers/future')
wait = Future.wait
Tower.StoreMongodb.wrappedFind = Future.wrap(Tower.StoreMongodb.find, 1)
Tower.StoreMongodb.find = -> Fiber(-> return Tower.StoreMongodb.wrappedFind.call(Tower.StoreMongodb, arguments[0]).wait()).run()
```

**Comment by edubkendo** [comment]
+1
this would make the console much easier to use. would love to see this happen.

**Comment by scottkf** [comment]
So, it's not really as simple as I thought above. For this to work the entire callback chain would have to be enclosed in a fiber. But, it might be possible to make the console run in a fiber and share the fiber with the console and just call the synchronous versions

**Comment by lancejpollard** [comment]
To make the callback chain run in a fiber can you just put the fiber wrapping code in the `runCallback` method?

[packages/tower-support/shared/callbacks.coffee#L61](https://github.com/viatropos/tower/blob/0281496c802930d8e838c377210266fc5b7c8b11/packages/tower-support/shared/callbacks.coffee#L61)

@scottkf if you get started on anything send me a link I'd love to help out.

**Comment by scottkf** [comment]
Possibly, but even then, the fiber is only blocking within the fiber
itself, so the console would have to be run in a fiber as well, which I was
able to do by wrapping find in the cursor, but the context was lost each
time.

Will the runCallback method return execution callback to the console, or
the finder functions?

I'll work on this some more tomorrow now that I have a better understanding of how the fiber implementation works. I'll push it to my repo.

**Comment by lancejpollard** [comment]
Let me know when you push your stuff, it will be easier for me to see what you're describing.

**Comment by scottkf** [comment]
https://github.com/scottkf/tower/tree/sync

You can do this, then the context gets polluted:

``` coffeescript
c = App.Ownership.count()
return c
```

The context is crazy because REPL doesn't seem to want to run in a fiber, so the code has to be eval'd within a fiber (or a Sync). For example, this doesn't want to work:

``` coffeescript
Sync =>
    repl    = repl.start
      prompt:"tower> "
      useGlobal: true
      context: @
```

If I can get the context right it would work

**Comment by lancejpollard** [comment]
Interesting, I can see the REPL context part being complicated. I'll check this out in a bit, keep moving though it looks like you're gonna get there pretty quick.

**Comment by lancejpollard** [comment]
@scottkf started messing around with your code, thanks for plowing through that eval stuff, was super helpful. got this working:

``` coffeescript
# model/cursor/finders.coffee
  find: (callback) ->
    Future = require('fibers/future')
    future = new Future
    @_find (error, result) =>
      future.return([error, result])

    [error, result] = future.wait()
    throw error if error
    result
```

``` coffeescript
# command/console.coffee
  run: ->
    repl    = require("repl")
    repl    = repl.start
      prompt:"tower> "
      useGlobal: true
      context: @
      eval:(cmd, context, filename, callback) -> 
        cmd = cmd.slice(1,-1)
        Fiber(->
          try
            callback(null, eval.call(context, cmd))
          catch error
            callback(error)
        ).run()
```

```
tower> App.Post.all()
[ { isNew: false, errors: {}, readOnly: false },
  { isNew: false, errors: {}, readOnly: false } ]
tower> var p = App.Post.all()
undefined
tower> p
[ { isNew: false, errors: {}, readOnly: false },
  { isNew: false, errors: {}, readOnly: false } ]
```

Will try and clean this up a bit.

**Comment by lancejpollard** [comment]
Building off your `sync` branch:
- https://github.com/viatropos/tower/tree/sync
- https://github.com/viatropos/tower/commit/7a0a3eee9734dab7fbb32bc2c53f25ed760d1389

**Comment by lancejpollard** [comment]
merged! we need to add console options and such still.

**Comment by scottkf** [comment]
Alright, options finished in #226, works w/coffeescript console. And it's great, it'll make everything a lot easier for sure. You can't quite chain commands things with relationships yet: App.Post.first().get('comments').count() won't work, but the fact I don't have to type out a callback syntax is already a lot better. There's probably other bugs lingering there too, when mixing sync and async code, try it out @edubkendo

**Comment by lancejpollard** [comment]
Side note, you can make things synchronous in the web console too by setting jQuery's async to `false`, which for the model layer is done in this [to be cleaned up] way:

```
# add too app/client/config/bootstrap.coffee "bootstrap" method:
Tower.StoreTransportAjax.defaults.async = Tower.env != 'development' # false if development, so it's sync.
```

**Comment by edubkendo** [comment]
This is really dope. Pretty amazing. I'll let you know if I encounter any bugs on edge cases, but for the simple case it's working amazingly well. Really impressed with how quickly you got this working.

**Comment by lancejpollard** [comment]
Going to close this, looking good to me. Great work! If issues come up with it we can open those separately.
