### ISSUE TITLE
toParam for Resources

### ISSUE THREAD

**Issue by activestylus** [tower-archive/tower#214]
Trying to override the find method for a given resource to find by slug instead of id. Ideally I would be able to do this without having to define the actions. Inherited Resources gem allows you to do this by defining the resource method, which will be applied for all GET requests of model instances. In order to have this all play nicely with URL helpers all you have to do then is define the to_param method on the model.

``` ruby
#controller
def resource
  @model ||= model.find_by_permalink(params[:id])
end

#model
def to_param
  permalink
end
```

I personally never liked this separation of concerns. If Tower does anything similar I believe it belongs at the controller level. Here is the ideal code I would like to write

``` coffeescript
class App.SitesController extends App.ApplicationController
  @param "domainName"
  @param "topLevelDomain"
  @toParam "permalink"
```

Or if we wanted to kill two birds with one stone:

``` coffeescript
class App.SitesController extends App.ApplicationController
  @param "domainName"
  @param "topLevelDomain"
  @param "permalink", toParam: true
```

Of course I understand why Rails stuck it in the model. It's the easiest way to get model_path(@model) to work correctly, perhaps this could work in the router instead?

``` coffeescript
Tower.Route.draw ->
  @resources "sites", toParam: 'permalink'
```

Thoughts?

**Comment by scottkf** [comment]
I believe I got part of this working by by adding `toParam: -> "#{@get('id')}-#{@get('permalink')}"` to the model when I first tried tower. The url generation wasnt there though, but the finders worked. You can override buildResource, createResource and findResource in the controller, and probably resource too. The former are functions and the latter is an object

**Comment by lancejpollard** [comment]
@activestylus This is something that should definitely be built in and easy to modify.

I've also used https://github.com/norman/friendly_id in the past and it modified `find` so it could handle `slug` if I remember correctly. But that's probably not the best way to do it.

I like having `toParam` in the model to convert it to a param, but it seems that having some method like `@toParam 'permalink'` in the controller might make sense too - where it would basically override the `findResource` to use `where(permalink: @params.id)...`, something like that.

Send me a pull request and we can work off that if you'd like.
