### ISSUE TITLE
Debugging techniques

### ISSUE THREAD

**Issue by panbhag** [tower-archive/tower#218]
What are the debug equivalent of rails
=> raise
=> logger.info

**Comment by lancejpollard** [comment]
Not sure I fully understand. Tower doesn't have a built in logger system yet, but you can just use `console.log` and `console.error`, etc. Eventually we need to implement/integrate better logging.

**Comment by panbhag** [comment]
ok

**Comment by lancejpollard** [comment]
If you want to take a stab at making/integrating a better logger, let me know and I'll do what I can to help out.

**Comment by panbhag** [comment]
Not yet. Still getting familiar with the code. Will surely let you know
when I want to get on it.
Till then, console will work fine.

**Comment by autoferrit** [comment]
for logging, i dont know all the tools out there, but node-bunyan seemed like a good logger.

https://github.com/trentm/node-bunyan
