### ISSUE TITLE
WARN: field should be a hash

### ISSUE THREAD

**Issue by activestylus** [tower-archive/tower#22]
I see these warnings whenever I install tower. They also surface sometimes when I run generators and other tower commands

```
npm WARN underscore.string@2.0.0 dependencies field should be hash of <name>:<version-range> pairs
npm WARN moment@1.4.0 devDependencies field should be hash of <name>:<version-range> pairs
```

I am left wondering if this is related at all to the other problems I am having

**Comment by winfred** [comment]
This isn't specific to Tower.
Those are issues for underscore.string and moment. Specifically, they haven't updated the NPM package to include the newer NPM constraint of hash-based dependency references. Look in your node_modules/underscore.string/package.json to see that it still says 

``` javascript
...
 "dependencies": [],
...
```

http://search.npmjs.org/#/underscore.string

**Comment by lancejpollard** [comment]
Yeah @wnadeau is right, closing this issue.  Thanks!

**Comment by activestylus** [comment]
OK thanks for clearing that up!
