### ISSUE TITLE
The root page isn't showing in ember on a new project

### ISSUE THREAD

**Issue by scottkf** [tower-archive/tower#221]
I feel like I mentioned this, but I couldn't find it.

It's not showing for a couple reasons:
1. It has no state: `@match '/', state: '/', to: 'application#welcome'`. It only automatically fires when it's given `/` as the state
2. Once it has state, you get this error: `Uncaught Error: Action '/' is not defined properly.`. 

I'm not too familiar with Ember's router, but I'll look into it a little more, it's defined here: https://github.com/viatropos/tower/blob/master/packages/tower-net/client/states.coffee#L23-87

This is somewhat related to #210. You probably have a better idea of how to solve this, I've been looking and it seems easy, conceptually, but I'm not sure of the implementation.

**Comment by lancejpollard** [comment]
Ah, thanks for pointing this out. You're right, we haven't handled this yet, only the `resources` ones. This area needs a lot of work.
