### ISSUE TITLE
Server needs to be restarted in development mode

### ISSUE THREAD

**Issue by panbhag** [tower-archive/tower#223]
Server needs to be restarted in development mode, after change in models and controllers

**Comment by lancejpollard** [comment]
Thanks, this just broke when switching from design.io to grunt. Will get to this in a bit.

**Comment by lancejpollard** [comment]
This is fixed now (in master, not npm): https://github.com/viatropos/tower/commit/26766e3e72358174234d956dea00abc1f092e731
