### ISSUE TITLE
How to upgrade the version of tower to latest

### ISSUE THREAD

**Issue by panbhag** [tower-archive/tower#224]
There are certain files which tower generates, ex the JavaScripts and the stylesheets in the vendor directory.
In an existing application, what is the best way to upgrade the version of tower to the latest one in master.

**Comment by lancejpollard** [comment]
If you have generated an app using an older version of tower, and are asking how to upgrade it to the new one, you can use the nice one-click installer found here: .

Haha, no you just have to manually make the changes, no real clean way to do it. It should be straightforward though, most of it's the same.

**Comment by autoferrit** [comment]
well if youre using tower via cloning and not npm, wouldnt you just run 'git pull origin master" ? then at that point you just have to make sure api changes wont effect your app, and update your functions if they are effected to reflect the new api

**Comment by panbhag** [comment]
exactly. Other than that, there are a couple of files which are generated
by node when generating the application which would need to be updated, ex
the  javascript files and the css files generated in the vendor directory,
the configuration files etc. I was just wondering if we can have a command
to re-generate these files.

**Comment by edubkendo** [comment]
@panbhag cd into your tower directory, run "make watch", copy the file /dist/tower.js into your app's vendor/javascripts folder, replacing the copy that is there. update the copy of ember.js in that folder to https://github.com/downloads/emberjs/ember.js/ember-1.0.pre.min.js and you should mostly be good to go.

**Comment by lancejpollard** [comment]
I am able to get running with this:

```
git clone https://github.com/viatropos/tower.git
cd tower
npm install
npm link # this makes it globally available
make watch
```

Then in another window:

```
tower new app
cd app
npm link tower # link it to the git repo just installed
npm install
```

**Comment by lancejpollard** [comment]
Other things that you need to change when upgrading an existing project to the latest stuff:
- First, generate a new app, just so you can grab the files from it.
- copy/paste `./grunt.coffee` from the generated app to your existing app
- copy/paste `./vendor/javascripts/tower.js`
- copy/paste `./vendor/javascripts/ember.js`
- copy/paste `./vendor/javascripts/handlebars.js`
- really, just copy/paste the vendor directory probably.
- copy/paste `./test/client.coffee` (new stuff removed design.io)
- copy/paste `./config/assets.coffee` (or just remove `design.io`, and make sure ember and handlebars are in there)
- remove `Watchfile` from your existing app
- remove anything matching `design.io` in old `./package.json`
- add anything matching `grunt` in new `./package.json` (grunt-less, grunt-stylus)

Finally, look at your `./config/application.coffee` file (if you're existing app was using tower v0.4.0), and compare it to the newly generated app's `./config/application.coffee` and `./config/bootstrap.coffee`. Essentially, move everything in the old `@configure ->` block into `App.configure ->` inside `./config/bootstrap.coffee`. All that should be in application.coffee is the namespace declaration.

To compile assets in the new app, run this watch command in another window in the project directory:

```
grunt start --config ./grunt.coffee
```

To run your new app:

```
node server
```

**Comment by panbhag** [comment]
Thats exactly what I was looking for :)
