### ISSUE TITLE
String URL parameters that are Integers are incorrectly parsed

### ISSUE THREAD

**Issue by scottkf** [tower-archive/tower#227]
https://github.com/viatropos/tower/blob/master/packages/tower-net/shared/route.coffee#L93-116

``` coffeescript
# need a way to convert :id to integer if it's an integer...
# try
#   params[key] = JSON.parse(capture)
# catch error
params[key] = capture
```

Is a working fix, because long integers overflow and round up when parsed via JSON. It's not a good fix, you could check the fields type first maybe.

**Comment by lancejpollard** [comment]
Thanks for posting. This was some of the first code I wrote and this specific thing was just hacked in there, been meaning to come back to it. It seems this needs a much more robust solution, not sure though.

Can you send a pull request?
