### ISSUE TITLE
document for using mongoDB

### ISSUE THREAD

**Issue by lumin3000** [tower-archive/tower#24]
As my understanding, to use mongoDB as store, 

I have to deploy "Tower.Store.MongoDB.initialize" somewhere in the project.

and also this one: 

``` coffeescript
@store(new Tower.Store.MongoDB(name: "posts", type: "App.Post"))
```

what is the best place to write these two?

**Comment by lancejpollard** [comment]
This was fixed by 0.4.0 [noting for reference].
