### ISSUE TITLE
Support for validation type on field declaration and pre-defined validation methods

### ISSUE THREAD

**Issue by autoferrit** [tower-archive/tower#243]
currently for model fields, if we have to validate for a special format, we have to do

``` coffeescript
class Product extends Tower.Model
  @validates "legacyCode", format: { with: /\A[a-zA-Z]+\z/, message: "Only letters allowed" }
```

So what I'm thinking might be great, is to be able to do it from either  model methods, or right from the line we declare the field from.
Current:

``` coffeescript
class App.User extends Tower.Model
  @field "firstName", type: "String"
  @field "email", type: "String"
```

Proposed:

``` coffeescript
class App.User extends Tower.Model
  @field "firstName", type: "String"
  @field "email", validate: "Email"
```

Where `Email` would be a pre-defined validation method. You can also specify a custom name where you can define it in your own model, or even use an anonymous function

``` coffeescript
class App.User extends Tower.Model
  @field "firstName", type: "String"
  @field "email", validate: -> /^gandalf$/gi
```

or

``` coffeescript
class App.User extends Tower.Model
  @field "firstName", type: "String"
  @field "email", validate: "gandalf"

  gandalf: ->
    /^gandalf$/gi
```

or possibly from a helper:

``` coffeescript
# a generic validation
Validator.validate emailField "email"
# one build from a given model
User.validate userName "gandalf"
```

In php the validator would probably be implemented as an interface. which is a generic class that any model can inherit from, outside of the normal class inheritance.  Although I dont believe cakephp does it that way. i will have to look into how they do it.

So these validators could possibly be in the global Model class as generic validators. And any custom ones in our own models. Another note is that cakephp has a pretty robust and easy to borrow validation library. Then again im pretty sure rails does too. But php is what im more familiar with. the Validator class basically just has a method for each validator and tests against a predefined regex (which we could just copy). So the validation methods themselves shouldnt be too hard to make, just need to find the best way to use them.

CakePHP's Validator:

https://github.com/cakephp/cakephp/blob/master/lib/Cake/Utility/Validation.php

**Comment by lancejpollard** [comment]
This is actually partially implemented:
- https://github.com/viatropos/tower/blob/master/packages/tower-model/shared/attribute.coffee#L158
- https://github.com/viatropos/tower/blob/master/packages/tower-model/shared/validator.coffee#L4

You can use all of the `keys` defined in `validator.coffee` (though some of them haven't been tested):

https://github.com/viatropos/tower/blob/master/test/example/app/models/validatable.coffee

You've added some other good examples to think about, this is definitely something to be fleshed out more.
