### ISSUE TITLE
Not able to call toJson on an instance of a model

### ISSUE THREAD

**Issue by panbhag** [tower-archive/tower#246]
In Posts Controller

``` coffeescript
  show:  ->
    App.Post.find @params.id, (error, resource) =>
      if resource
        @render json: resource.toJson({include:['comments']})
      else
        @redirectTo "index"
```

```
TypeError: Object #<error> has no method 'toJson'
```

if i just do `@render json: resource`, if works fine.

But if I want  to include some resources, or exclude some fields I would explicitly need to call toJson, which does not work.

**Comment by lancejpollard** [comment]
The method is all caps: `toJSON`

**Comment by lancejpollard** [comment]
Other note, the `include: ['comments']` I don't think will work, that has not been setup yet.

**Comment by panbhag** [comment]
ok, should we not be sticking to javascript camel casing convention?

**Comment by lancejpollard** [comment]
We should, but there are notable exceptions. When a normally all-caps word comes first, it's all lower case, otherwise it's all uppercase:

``` javascript
function jsonPrettyPrinter() { }
function toJSON() {}
```

This is a pretty standard convention.
