### ISSUE TITLE
Weird behavior when executing unit tests

### ISSUE THREAD

**Issue by sebastianhoitz** [tower-archive/tower#252]
When writing unit tests for a tower app I noticed very weird behavior.

When running `npm test` it started running mocha, then waited and just stopped.

When I was searching for the issue I noticed that it never seems to finish initializing mongodb. It just stops when opening the connection, and the callback never gets called.

When I commented that out, I noticed this:

Lets say I have a file

orderHelperTest.coffee

``` coffeescript
method = undefined

describe "App.OrderHelper", ->
  before ->
    method = App.OrderHelper.getPriceAsString

  it "Should return the correct amount", ->
    value = method 300
    value.should.equal "3,00 €"

  it "It should return 10 cents", ->
    value = method 10
    value.should.equal "0,10 €"
```

But only the first test is run, the other test never finishes.

Has anybody done some unit testing on an actual tower app, not the tower source?

**Comment by lancejpollard** [comment]
I have done some testing and it has worked fine so far. Interesting...

Does it have anything to do with that `€` character? Also, maybe `method` is a special keyword (random things to try to debug).

Try also running the mocha command directly:

```
mocha $(find test -name "*Test.coffee")
```

**Comment by lancejpollard** [comment]
What does your `./test/server.coffee` file look like?

Also, if you get a timeout, maybe try increasing the duration of the `--timeout` option in `./test/mocha.opts`, but it doesn't seem like that's the issue here.

**Comment by lancejpollard** [comment]
Finally, try using the `assert.equal` method from chai, instead of `should`, I haven't tried `should`.

**Comment by sebastianhoitz** [comment]
This is my `./test/server.coffee`:

``` coffeescript
require 'tower'

global.chai     = require "chai"
global.assert   = chai.assert
global.expect   = chai.expect
global.sinon    = require 'sinon'
global.async    = require 'async'
global.test     = it
global.cb       = true # some library has a global leak...
global.factory  = -> Tower.Factory.create(arguments...)
global.urlFor   = Tower.urlFor
global.get      = _.get
global.post     = _.post
global.put      = _.put
global.destroy  = _.destroy

global.app      = Tower.Application.instance()

# Initialize the app before everything.
before (done) ->
  app.initialize done

# Run this before each action
beforeEach (done) ->
  if Tower.client
    Tower.StoreMemory.clean(done)
  else
    Tower.StoreMongodb.clean(done)
```

I simplified the file down to this:

``` coffeescript

describe "App.OrderHelper", ->
  it "Should return the correct amount", ->
    value = App.OrderHelper.getPriceAsString 300
    assert.equal value, "3,00 €"

  it "Should return 10 cents", ->
    value = App.OrderHelper.getPriceAsString 10
    console.log "Got this", value
    assert.equal value, "0,10 €"
```

This is the response while running mocha:

```
$ node_modules/mocha/bin/mocha $(find test -name "*Test.coffee")
path.existsSync is now called `fs.existsSync`.


  App.OrderHelper
    ✓ Should return the correct amount 
    ◦ Should return 10 cents: $
```

It does not really go into executing the second test. I can put a `console.log` in there, and nothing happens.

**Comment by lancejpollard** [comment]
try pasting the output from `npm list`, maybe it's a library/version thing? also, what folder is that helper test in?

(from irc, https://gist.github.com/3505316)

**Comment by lancejpollard** [comment]
also, what os/node/npm versions.

**Comment by sebastianhoitz** [comment]
npm list: https://gist.github.com/3505316

This is what my test folder looks like:

```
test/
├── client.coffee
├── helpers
│   └── orderHelperTest.coffee
├── mocha.opts
├── models
│   ├── customerTest.coffee
│   ├── eventTest.coffee
│   ├── itemTest.coffee
│   ├── orderTest.coffee
│   ├── paperTest.coffee
│   ├── photoTest.coffee
│   ├── sessionTest.coffee
│   └── userTest.coffee
└── server.coffee
```

the other test files are all commented out. This error also occurs when I just run the orderHelperTest test.

```
$ uname -a
Darwin Sebastian-Hoitzs-MacBook-Pro.local 12.0.0 Darwin Kernel Version 12.0.0: Sun Jun 24 23:00:16 PDT 2012; root:xnu-2050.7.9~1/RELEASE_X86_64 x86_64

# Thats Mountain Lion.

$ node -v
v0.8.8

$ npm -v
1.1.59
```

**Comment by lancejpollard** [comment]
I'm on:

```
$ node -v
v0.8.2

$ npm -v
1.1.32

OSX 10.6.7
```

**Comment by lancejpollard** [comment]
May be a coffee-script compilation thing? Try in the node cli:

```
> console.log(require('coffee-script').compile(require('fs').readFileSync('./test/helpers/orderHelperTest.coffee', 'utf-8')))
```

**Comment by lancejpollard** [comment]
are you perhaps using tabs anywhere (vs. 2 spaces) for indentation?

**Comment by lancejpollard** [comment]
Also try wrapping all the methods in parentheses:

``` coffeescript
describe("App.OrderHelper", ->
  it("Should return the correct amount", ->
    value = App.OrderHelper.getPriceAsString(300)
    assert.equal(value, "3,00 €")
  )
)
```
- Try changing the file to JavaScript and seeing.
- Try using no `App` specific code, such as just testing if `1 + 2 = 3`.
- Try returning `undefined` at the end of your `it` test function, maybe if it gets a return value something happens.

Basically, I'm not sure, just try a bunch of stuff.

**Comment by lancejpollard** [comment]
Also try multiple assert statements within the first `it` method, see if you can do that.

**Comment by sebastianhoitz** [comment]
Weird. It must have something to do with mountain lion. When I try to start the server, I get a 

```
[Wed, 29 Aug 2012 08:27:08 GMT] INFO Tower development server listening on port 4000
Segmentation fault: 11
```

When I run this on my workstation in the office (Snow Leopard), everything is fine and I can also run the unit tests. Weird...

**Comment by lancejpollard** [comment]
What's the state of this now?

**Comment by sebastianhoitz** [comment]
I still can't get it to run on my MacBook on Mountain Lion. But on my workstation iMac it runs perfectly. Also on our Debian servers. So I think this is a problem with my macbook.
