### ISSUE TITLE
Standardize the file/folder structure

### ISSUE THREAD

**Issue by lancejpollard** [tower-archive/tower#253]
Building off of this discussion... https://gist.github.com/1398757

There are three main "high level" ways of organizing the files from that gist, which can be roughly labelled as:
1. Rails: https://gist.github.com/1398757#2-a-appclient-folder-similar-to-rails-appassets
2. Integrated: https://gist.github.com/1398757#gistcomment-395680
3. Separated: https://gist.github.com/1398757#gistcomment-384957

In the _integrated_ approach, the top-level folders are things like `model`, `view`, `template`, `controller`, each with subfolders `client`, `server`, and possibly `shared`. This one seems to be the easiest to use if you're working on all parts of the app (client and server), because it is nice to group all the controllers together (client and server), because in your head they are somehow conceptually related.

In the _separated_ approach, the top-level folders are `client`, `server`, and `shared` (and possibly others like `mobile` and whatnot). This seems like it would be most useful if you have a larger team and people work on specific parts of the app (client vs. server). If a developer doesn't need to worry/care about the server-side controllers, then they really shouldn't even have to see them. By having `client/controllers` and `server/controllers`, theoretically you could only look in the `client` folder if you're a front-end dev, and the `server` folder if you're a backend guy.

The _rails_ way isn't ideal in this all-javascript environment because it focuses around the server, where the client and server should have roughly equal priority here.

Also to note, I don't think you should be able to "pick" one of these folder structures. There should be _one_ that the majority of people like. I imagine not everyone is going to agree on one approach, but we still have to reach that point.

**Comment by lancejpollard** [comment]
Some more notes...

I like the general structure of @krainboltgreene's [comment](https://gist.github.com/1398757#gistcomment-396669), not necessarily the PAC (vs. MVC) subfolders however. The main issue with the _integrated_ approach is that the top-level folders would also include folders that are really independent of either client or server:

```
bin # not often, but sometimes
logs
public
tmp
vendor
wiki # or docs
```

So, putting the model/view/template/controller/etc files into a top-level `apps` or `app` folder might be a good thing, in order to separate it from the other top-level folders that are independent of client/server distinctions. Because, this might be confusing:

```
bin
controllers
logs
models
public
stylesheets
templates
tmp
vendor
views
wiki
```

Instead, this may be clearer (where models/views/etc. are in `app`):

```
app
bin
logs
public
tmp
vendor
wiki
```

**Comment by lancejpollard** [comment]
Looking into @luckysmack's comment: https://gist.github.com/1398757#gistcomment-396669

**Comment by krainboltgreene** [comment]
I'm currently weathering the after effects of a tropica storm, but this is on my reading list.

**Comment by lancejpollard** [comment]
I am going to go try out this folder structure now:

```
|-- app
|   |-- config
|   |   |-- client
|   |   |   |-- bootstrap.coffee
|   |   |   `-- routes.coffee
|   |   |-- server
|   |   |   |-- assets.coffee
|   |   |   |-- bootstrap.coffee
|   |   |   |-- credentials.coffee
|   |   |   |-- databases.coffee
|   |   |   |-- emails.coffee
|   |   |   |-- jobs.coffee
|   |   |   `-- routes.coffee
|   |   `-- shared
|   |-- controllers
|   |   |-- client
|   |   |   `-- applicationController.coffee
|   |   |-- server
|   |   |   `-- applicationController.coffee
|   |   `-- shared
|   |-- models
|   |   |-- client
|   |   |-- server
|   |   |   |-- user
|   |   |   |   `-- emailConcern.coffee
|   |   `-- shared
|   |   |   |-- post.coffee
|   |   |   `-- user.coffee
|   |-- stylesheets
|   |   |-- client
|   |   |   `-- application.styl
|   |   `-- server
|   |   |   `-- email.styl
|   |-- templates
|   |   |-- client
|   |   |-- server
|   |   |   |-- layouts
|   |   |   `-- emails
|   |   `-- shared
|   |   |   |-- posts
|   |   |   |   `-- index.coffee
|   |   |   `-- users
|   |-- themes
|   |-- views
|   |   |-- client
|   |   |   |-- posts
|   |   |   `-- users
|-- data
|-- logs
|-- node_modules
|-- public
|   |-- images
|   |-- javascripts
|   |-- stylesheets
|   `-- uploads
|-- tests
|-- vendor
`-- wiki
```

Here is the rationale behind some of the decisions (add more if you think of any that are left out).

> Why so many client/server controllers?

At first we thought of top level `client` and `server` folders. But that makes it harder for the "single dev" to comprehend the entire app, because as a "full stack" developer, you're thinking of "models", "templates", "views", "controllers", etc., not of "client" vs. "server" and drilling down to "server models". You look for "models" first, then "server".

> Why not put the files in the `shared` folder at the parent directory?

This makes sense to do in the `models` case, because you're going to be using most/all of the models on both the client and server (at least early on in your app).

However, in the `controllers` case, the client and server controllers are very different (but they should both still be called "controllers"). It might seem strange if _most_ of the controller code is found in `server` and `client`, and one or two files at the top level. This is because, in the `models` case, files at the top-level would be assumed most important / core to the app, whereas in the controller case they wouldn't.

The shared folder explicitly states "these files are used in both places"; it makes it clear, no ambiguation.

> Why the top-level `app` folder, why not put `models`, `views`, etc. at the top?

Because then `models`, `views`, etc. would be mixed in with totally unrelated folders such as `logs`, `bin`, `wiki`, and `public`. Conceptually, those folders are unrelated to models/views/controllers/etc.

> Why not _optimize_ the client/server/shared folders for what's most common?

That is, since `views` and `stylesheets` are only for the client (at least as far as I can tell), `templates` technically are agnostic to the server and client, why not just have this?

```
|   |-- views
|   |   |-- posts
|   |   |   `-- index.coffee
```

instead of this:

```
|   |-- views
|   |   |-- client
|   |   |   |-- posts
|   |   |   |   `-- index.coffee
```

Still not 100% on this, but it seems that while having this "less nested" file structure is technically "more optimized", it leads to more questions that answers... Personally, my mind will look at the other folders and think, "well, technically, most models are agnostic to client/server, so do the same for them, oh but wait in certain cases... etc.". So, for now, all folders have this same structure.

Was not 100% decided on this for the stylesheets, but if you think about emails, then those should technically be "server side stylesheets" (which will be converted to inline css, eventually).

> _In response to @luckysmack's comments on the gist._

Still need to think about the top-level `db` vs. `data` folder. I like calling it `data` better personally. But the `data/tmp` folder shouldn't be generated, b/c having multiple tmp folders seems confusing. Instead, having somewhere in the docs/guides that using `tmp` folders is good practice might be good enough.

Also need to think more about a whole `themes` system. There should be a standard way of adding custom themes to your app, for these reasons:
1. Sometimes front end coders like to mess around with multiple different themes for their app, and having a folder structure in place for this would be helpful.
2. Maybe you want to have `ipad`, `browser`, etc. themes, for different devices.

However, along those same lines, I am not a big fan of the idea of grouping models/views/controllers/etc. into "plugins" or reusable components (like the comments module). While this looks good and feels right conceptually, in my experience it makes it harder to code down the road. Really, the code never gets modular enough that it's a black box you can port to other projects without error. If it does get to that point, it's probably already an `npm` module (rubygem), and so can accomplish the same thing. Also, when I am fixing some model bug and it's relation to other models, I want all the models to be in one place; having them in a nested module adds too much overhead to that workflow.

**Comment by krainboltgreene** [comment]
I wish there was a better venue for discussing this. Perhaps we should break it down into smaller discussions?  

## 

Kurtis Rainbolt-Greene
Difference Engineers
643 Magazine St STE #102,
New Orleans, LA 70130
202-643-2263

**Comment by lancejpollard** [comment]
#towerjs IRC?

There aren't any real good alternatives, and I would prefer not to use google groups. IRC and GitHub are ideal for me, what is best for you?

**Comment by lancejpollard** [comment]
Done.
