### ISSUE TITLE
Tower.root not dynamic enough AND SublimeREPL

### ISSUE THREAD

**Issue by edubkendo** [tower-archive/tower#254]
If you attempt to open the tower console from a directory interior to the base directory it gives the error:

```

module.js:340
    throw err;
    ^
Error: Cannot find module '/home/eric/projects/projects/towerApps/towerBot/app/config/application'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Function.Tower.Application.__defineStaticProperty._initializers._initializers [as _super] (/home/eric/git/community/tower/lib/tower-application/server/application.js:100:15)
    at Function.Ember.wrap.newFunc [as instance] (/home/eric/git/community/tower/node_modules/ember-metal-node/index.js:659:16)
    at CommandConsole.runCoffee (/home/eric/git/community/tower/lib/tower-command/server/console.js:94:29)
    at CommandConsole.run (/home/eric/git/community/tower/lib/tower-command/server/console.js:25:19)
    at Object.Tower.Command.run (/home/eric/git/community/tower/lib/tower-command/server/command.js:18:20)
```

This is because Tower.root seems to simply be the current directory.  Normally, for me at least, this is no big deal, because in the terminal I tend to leave it right there in the root directory of the project. However, I've been experimenting with adding Tower support to the [SublimeREPL](https://github.com/wuub/SublimeREPL) and it works great if when you attempt to start tower console the only open file you have is open is the cakefile or something else in the project's root directory, but if you have a file open in another, interior directory like something in app/models or test (a very common scenario for wanting to quickly open a REPL and test some code, ie. when you're working on a file and suddenly aren't sure how something works) it gives this error.

I will continue to try to find a solution within the plugin that causes it to always tell tower the project's root instead of the current file. But ideally, Tower.root would examine the path and determine the proper root if it is in an inner directory, and work correctly regardless. Either way, the prospect of having a working REPL in the editor that opens up right there, with access to all my functions and variables, full Tower console support AND syntax highlighting, snippets, autocompletion and everything else Sublime Text brings to the table is pretty exciting. 

If I don't find a way to fix the "root" problem soon, I'll go ahead and provide info on setting this up for those interested in using it, and the files, etc. As I said, it's working fine except you have to be careful which files are open when you try to open it, otherwise it gives that error and you have to close and re-open sublime to get it working. One workflow would be to open the REPL as soon as you open sublime and just leave it up as you work. I doubt the owner of the project will accept a pull-request unless we get the Tower-root problem fixed (and might not be interested in supporting frameworks anyways). So I'll just put in the PR, but make my fork available in the meantime.

**Comment by lancejpollard** [comment]
Yeah not sure about this one, let me know when you figure it out. Might want to check how/if rails does it. Maybe we can add some hidden file to look for, or just look up to the parent directories until the `ls` array lists some set of folders we are expecting, such as (pseudocode):

``` coffeescript
_path = require('path')
fs    = require('fs')

testIfRoot = (path) ->
  # first, the path must exist and be a directory
  return false unless fs.existsSync(path) && fs.statSync(path).isDirectory(path)
  # then check for package.json
  return false unless fs.existsSync(_path.join(path, 'package.json'))
  # then check for some key directories / files
  return false unless fs.existsSync(_path.join(path, 'config/application.coffee'))
  # if all pass, then we have the directory
  path

setTowerRoot = ->
  path = process.cwd()

  while !testIfRoot(path) && path != '/' # @todo some check to not traverse all the way to the root "/" path (windows and *nix)
    path = _path.join(path, '..')

  Tower.root = path unless path == '/'
```

**Comment by edubkendo** [comment]
Alright, first things first: Got the SublimeREPL plug-in working 99% with the tower console. It turned out to be easier than I thought because Sublime Text's api exposes a variable just for this sort of thing, $project_path. So I was able to just swap this out for $file_path in the profile I'd made for tower console in the plug-in and (after a bit of debugging where things weren't getting properly passed and needed to be ordered correctly), got it.

So, for those developing tower apps using Sublime Text, if you would like, check it out: https://github.com/wuub/SublimeREPL/pull/67 . I don't know if he'll accept my pull request since tower is a framework and not a language, but we'll see. Either way, you can just install my fork like this:

cd into the directory where Sublime installs packages and then clone the "adds-tower" branch. on Ubuntu this would be:

```
$ cd .config/sublime-text-2/Packages

$ git clone https://github.com/edubkendo/SublimeREPL.git -b adds-tower
```

And you should be set. Seems like it's still a little wonky sometimes. Easiest thing to do, when you first open sublime text with your project, open up a coffeescript file in the project's root like the cakefile and then start the REPL (cmd + shift + P, type tower). Now you can close those and should have zero problems re-opening the REPL no matter where you are. All this will be fixed when the real issue is addressed, which gets to the next part:

Yes, you can run the rails console from anywhere in your project. I checked it out with an old rails project of mine. Works fine. When I looked into the code though, this is it:

``` ruby
#!/usr/bin/env ruby
require File.expand_path('../../load_paths', __FILE__)
require 'rails/all'
require 'active_support/all'
require 'irb'
require 'irb/completion'
IRB.start
```

So, no help there. I have some ideas, actually from looking at some other sublime plug-ins, specifically the ones that work with git.  so adding this to my to-do list, lol.

**Comment by lancejpollard** [comment]
This is more robust now, you can do one of these:

``` coffeescript
# This can be set before any tower code is run, which is nice sometimes
process.env.TOWER_ROOT = __dirname # or anything

# Or you can do it manually
Tower.setRoot(__dirname)
```

It will also try to check up the parent change until it _looks_ like a tower app.

**Comment by edubkendo** [comment]
Yup, this has proven much more reliable. I made a tweak to the SublimeREPL plugin so that it works with this change in place. Now you can summon up tower console from any open file in your project.

Works great from the terminal too.

**Comment by lancejpollard** [comment]
Sweet.
