### ISSUE TITLE
Some IDs get interpreted as integer?

### ISSUE THREAD

**Issue by sebastianhoitz** [tower-archive/tower#256]
Tower seems to have problems with some specific ID formats.

When I have an object with an id "**501e35680656623306000011**", this gets interpreted as Infinity, causing tower to crash, because it can't really handle 404s yet.

Notice the e in the ID, which gets interpreted as 501 \* 10 ^ 35680656623306000011

**Comment by lancejpollard** [comment]
Yeah that number is far too big, not sure if any computer can handle numbers that large.

**Comment by lancejpollard** [comment]
Haha, totally kidding. No we need a more robust approach to parsing params:

https://github.com/viatropos/tower/blob/master/packages/tower-net/shared/route.coffee#L80
