### ISSUE TITLE
Not an issue: How does towerjs compare with meteorjs

### ISSUE THREAD

**Issue by panbhag** [tower-archive/tower#264]
It would be great if the authors could throw some light on this.

**Comment by maedi** [comment]
Tower is the Ruby on Rails of the Node world, while Meteor tries to move away from MVC and let the developer decide the structure and flow. Meteor is primarily client side, Tower is both. They both have auto syncing of data on multiple browsers.

These articles indirectly compare both:
<a href="http://stackoverflow.com/questions/9897017/railwayjs-vs-towerjs">RailwayJS vs TowerJS</a>
<a href="http://blog.derbyjs.com/2012/04/14/our-take-on-derby-vs-meteor/">Our take on Derby vs. Meteor</a>

<table>
  <thead>
    <th>Criteria</th><th>Tower</th><th>Meteor</th>
  </thead>
  <tbody>
    <tr>
      <th>Framework style</th><td>MVC</td><td>Roll your own</td>
    </tr>
    <tr>
      <th>Similar framework</th><td>Rails</td><td>Derby (also Node)</td>
    </tr>
    <tr>
      <th>Philosophy</th><td>Convention over configuration</td><td>Roll your own</td>
    </tr>
    <tr>
      <th>Default language</th><td>CoffeeScript</td><td>JavaScript</td>
    </tr>
    <tr>
      <th>Client JS framework</th><td>Ember</td><td>Meteor</td>
    </tr>
    <tr>
      <th>Template engine</th><td>CoffeeCup + Handlebars</td><td>Handlebars</td>
    </tr>
  </tbody>
</table>

In my opinion Tower is easier to understand and nicer to look at. Coming from Rails the MVC structure feels familiar.
