### ISSUE TITLE
Render JSON data as UTF-8

### ISSUE THREAD

**Issue by sebastianhoitz** [tower-archive/tower#267]
Right now, tower sends JSON data in a different charset then UTF-8.

The source of this problem is this line in **tower-controller/server/renderers.coffee** line 12:

``` coffeescript
@headers['Content-Type'] ||= require('mime').lookup('json')
```

It does not append the correct charset, like this:

``` coffeescript
@headers['Content-Type'] = "application/json; charset=UTF-8"
```

Maybe we shouldn't use node-mime here, or at least append the UTF-8 charset. What do you think?

**Comment by lancejpollard** [comment]
Yeah this needs to be cleaned up and made more robust. Do you know of a better alternative to node-mime?

I tried doing what you're suggesting a little while ago but it caused a bunch of the tests to fail (I'm pretty sure) so I switched it back.

``` coffeescript
@headers['Content-Type'] = "application/json; charset=UTF-8"
```

If that works (or we can fix the tests) then that's great. Going to start making the controllers more robust in a few weeks or so, I'll get to this then unless you want to send a PR.

**Comment by lancejpollard** [comment]
This is now fixed: https://github.com/viatropos/tower/commit/72acd23e6d3c8682bf00c54ccf269cc2a61c1b26#L1R22
