### ISSUE TITLE
MacOS 10.7 install issues

### ISSUE THREAD

**Issue by RickCarlino** [tower-archive/tower#268]
Tried doing a global install of tower.js by doing a 'sudo npm install -g tower'
and this is what was outputted:

https://gist.github.com/3690945

I am relatively new to node/coffee development, so very few packages outside of tower are installed globally on my system.

**Comment by lancejpollard** [comment]
What if you try without sudo?

```
npm install tower -g
```

Also, how did you install node? If you used a method other than HomeBrew then it could be some permissions thing I am not very familiar with. Also, what version of node/npm?

**Comment by edubkendo** [comment]
@rickcarlino @viatropos guys have a look at this. I'm thinking this might explain some of the errors we are seeing pop up with tower installs lately:

https://github.com/isaacs/npm/issues/2792

Looks like some very similar error messages to what you were having @rickcarlino , in the bottom part, but i think the entire thread may well be applicable.

**Comment by lancejpollard** [comment]
@edubkendo I think you're right on that, it's probably a git issue. In the short term we should make sure git is installed (note on the README), but eventually all the dependencies would ideally be installed from the npm link rather than git.

**Comment by lancejpollard** [comment]
@rickcarlino was this because git wasn't installed?

**Comment by RickCarlino** [comment]
@viatropos Truth be told, I am only now just starting with node (Tower is my first hands on experience with node). Do you mean if git is installed on the system? Or a git dependency for node? Git is installed on this system, but I havent touched anything on node hardly outside of installing coffeescript and npm etc.

**Comment by lancejpollard** [comment]
@rickcarlino see https://github.com/viatropos/tower/issues/272#issuecomment-8522405

If you installed node.js from an installer and are installing modules globally with sudo, it's highly recommend to install node with homebrew. Homebrew will take care of any/all permissions problems you will have on the Mac.

Other than that, 0.4.2-1 doesn't run any `npm install` commands when installing tower globally, so you should be good to go.
