### ISSUE TITLE
Method overriding does not seem to work yet

### ISSUE THREAD

**Issue by sebastianhoitz** [tower-archive/tower#269]
I issues this request:

  /orders?_method=put&order[isPaid]=true

and Tower identified this as a GET request instead of a PUT request.

My bootstrap.coffee has

``` coffeescript
@use "methodOverride", "_method"
```

Am I doing something wrong?

**Comment by lancejpollard** [comment]
I think it needs to be a POST request, since `req.body` is only defined for POST requests I'm pretty sure:

[https://github.com/senchalabs/connect/tree/master/lib/middleware/methodOverride.js#L28](https://github.com/senchalabs/connect/blob/15bb7e2598d1f3c18b3063673a6f7900e919ac69/lib/middleware/methodOverride.js#L28)

**Comment by sebastianhoitz** [comment]
Ah, ok. Shoot, I thought this was possible.

I have a lot of buttons in my code that toggle one single boolean switch in
my models. Right now I have a lot of actions that do the single change.

Now I will probably have to implement a lot of forms that do that logic,
right?

Like this:

``` html
<form action="/orders/#id" method="post">
  <input type="hidden" name="_method" value="put">
  <input type="hidden" name="order[isPaid]" value="true">
  <input type="submit" name="submit" value="Mark as paid">
</form>
```

I think it would be cool for tower to provide a view helper to do this kind
of stuff. What do you think?

On Mon, Sep 10, 2012 at 11:07 PM, Lance Pollard notifications@github.comwrote:

> I think it needs to be a POST request, since req.body is only defined for
> POST requests I'm pretty sure:
> 
> https://github.com/senchalabs/connect/tree/master/lib/middleware/methodOverride.js#L28https://github.com/senchalabs/connect/blob/15bb7e2598d1f3c18b3063673a6f7900e919ac69/lib/middleware/methodOverride.js#L28
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/viatropos/tower/issues/269#issuecomment-8438415.

## 

_Sebastian Hoitz_

Geschäftsführer, Entwickler, Coffee 2 Code converter

komola UG (haftungsbeschränkt)
Rebenring 33
38106 Braunschweig

Telefon: +49 531 3804200
Mobil: +49 175 2517038

Geschäftsführer: Sebastian Hoitz, Thomas Schaaf
Amtsgericht Braunschweig | HRB 201595

**Comment by lancejpollard** [comment]
The main reason you'd need to use forms like you've outlined is to support browser environments without javascript. Tower should be able to do that eventually but that's probably a little ways down the road.

To do this just use Ember's patterns. So if the form example is a button from a row in a table of `Order` records, when you check `Mark as paid` it can run the client `App.OrdersController#update` method, which calls `order.save()`, which makes the `PUT` request. If you bind the check mark's value to the `order.isPaid` then calling `order.save()` will only send that key/value pair to the server (probably also `updatedAt`).

Not sure how to do this with Ember off the top of my head, but it should be straight forward. Look at the (new) generated form in tower, to see how to bind the values if you're unfamiliar.

**Comment by lancejpollard** [comment]
Closing this since this is part of connect.
