### ISSUE TITLE
session cookie fail

### ISSUE THREAD

**Issue by lumin3000** [tower-archive/tower#27]
After "tower new app"
in config/application.coffee:

``` coffeescript
@use "session", secret: Tower.sessionSecret, cookie: {domain: ".#{Tower.cookieDomain}"}
```

the Tower.cookieDomain is undefined, and this will cause the session cookie fail.
Is that possible to set a default value or just delete it?

**Comment by lancejpollard** [comment]
This is no longer an issue with the new way the tower generator builds the session.
