### ISSUE TITLE
Dynamic Data Not Processing?

### ISSUE THREAD

**Issue by thehydroimpulse** [tower-archive/tower#274]
Just recently re-installed tower.js on my linux vm; started the server up and got a blank page. When you look into the source code you can see the template within a set of script tags. 

Image: http://cl.ly/image/0a2k2h090P1u

**Comment by edubkendo** [comment]
Because it is no longer using Design.IO, you have to run "cake watch" first.

**Comment by thehydroimpulse** [comment]
aha fixed the problem. Thanks :)
