### ISSUE TITLE
CoffeKup Helpers

### ISSUE THREAD

**Issue by j-mcnally** [tower-archive/tower#278]
Haven't got through all the code and I don't understand how mint factors into everything but i wrote the following initializer monkey patch to allow rails style helpers for coffee script. Is there a better way to accomplish this?

``` coffeescript
Tower.View.helpers = require('../../lib/coffecup-helpers')(Tower.View.helpers)
```

``` coffeescript
module.exports = (Thelpers) ->
  walker = require('./dirwalker.js')
  xtend = require('xtend')
  helpers = {};
  walker 'app/helpers', (err, results) ->
    if (err)
      console.log "No Helpers Found..."
    else
      console.log "Loading Helpers Into CoffeeKup", results.join(",")
      for file in results
        mod = require("../#{file}")
        xtend helpers, mod
  helpers = xtend Thelpers, helpers
```

Also I was able to easily add 3rd party helpers like coffeecup-helpers

by adding a file under my helpers that contains 

```
module.exports = require 'coffeecup-helpers'
```

**Comment by lancejpollard** [comment]
You can try something like this:

``` coffeescript
paths = _.select require('wrench').readdirSyncRecursive('app/helpers'), (i) ->
  i.match(/\.coffee$/) # only coffee-script files

for path in paths
  Tower.View.helper(require(path))
```
- https://github.com/ryanmcgrath/wrench-js

There needs to be a cleaner way to do this but I'm not sure it's there. You can add helpers to the controllers like this but I'm not sure they get added to the view as well:

``` coffeescript
class App.PostsController extends App.ApplicationController
  @helper App.TagsHelper
```

There is a lot of room for improvement here, let me know if you see a better way.

**Comment by lancejpollard** [comment]
Note, the `Tower.View.helpers` object, which `Tower.View.helper` extends with it's arguments, is only added to the coffeecup engine right now, later it should be added to any engine.
