### ISSUE TITLE
"csrf" cause "post" action fail

### ISSUE THREAD

**Issue by lumin3000** [tower-archive/tower#28]
tower used "csrf"

but the scaffold FORM coffeekup template doesn't include csrf fields which will cause a 403 error in any post action.

**Comment by elmacnifico** [comment]
same problem here...the example app doesn't have any csrf fields in the forms either but seems to work...were is my mistake?

**Comment by yusugomori** [comment]
You can manually put

input type: "hidden", name: "_csrf", value: @request.session._csrf

in the form.
