### ISSUE TITLE
Add form/table HTML to generator for associations

### ISSUE THREAD

**Issue by lancejpollard** [tower-archive/tower#281]
When you run this:

```
tower generate scaffold post title:string belongsTo:user
tower generate scaffold user email:string hasMany:posts
```

it should generate some sort of nice HTML for the show/index/_form. Any ideas for this?

Sidenote, this looks cool, I can see it growing to have a large collection of very useful HTML snippets:

http://bootsnipp.com/snipps

**Comment by ivoreis** [comment]
You are saying to create associations in the views? Something like [rails_admin](https://github.com/sferik/rails_admin) use to create their associations?

**Comment by lancejpollard** [comment]
Yeah integrating that would be a great start!

http://rails-admin-tb.herokuapp.com/admin/field_test/158/edit

What are your thoughts?

**Comment by ivoreis** [comment]
This  rails_admin feature is supported by the Ryan's [nested_form](https://github.com/ryanb/nested_form) and the core of this feature can be found here [https://github.com/ryanb/nested_form/blob/master/lib/nested_form/builder_mixin.rb](https://github.com/ryanb/nested_form/blob/master/lib/nested_form/builder_mixin.rb) and already have a ruby support for formtastic (I think you use it in tower, maybe i'm wrong)

**Comment by lancejpollard** [comment]
Tower is using something like Formtastic, haven't used nested_form though. If you'd like to take a stab at something like this definitely let me know.

Cheers!
