### ISSUE TITLE
Hook.io & Weakref?

### ISSUE THREAD

**Issue by thehydroimpulse** [tower-archive/tower#285]
I was just moving my development environment from linux to mac osx and when I run the server I get a boat load of errors:

Daniels-Mac:tower_app daniel$ node server
   info  - socket.io started
[Mon, 17 Sep 2012 03:06:43 GMT] INFO Tower development server listening on port 3000

/Users/daniel/Documents/Projects/tower_app/node_modules/hook.io/node_modules/weak/lib/bindings.js:14
        throw e
              ^
Error: dlopen(/Users/daniel/Documents/Projects/tower_app/node_modules/hook.io/node_modules/weak/build/Release/weakref.node, 1): no suitable image found.  Did find:
    /Users/daniel/Documents/Projects/tower_app/node_modules/hook.io/node_modules/weak/build/Release/weakref.node: mach-o, but wrong architecture
    at Object.Module._extensions..node (module.js:485:11)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at requireTry (/Users/daniel/Documents/Projects/tower_app/node_modules/hook.io/node_modules/weak/lib/bindings.js:11:14)
    at Object.<anonymous> (/Users/daniel/Documents/Projects/tower_app/node_modules/hook.io/node_modules/weak/lib/weak.js:1:99)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)

I tried searching everywhere on this issue on all the related modules but found nothing, maybe someone has a clue on the relationship of these modules and the culprit (unless it's just me)?

**Comment by lancejpollard** [comment]
What is your version of OSX, node, and npm? Also, see if you have hook.io installed locally and globally.

**Comment by thehydroimpulse** [comment]
Running mountain lion (10.8)
Node -> v0.8.9
NPM -> 1.1.61

Hook.io was originally installed locally, but i also tried global and it made no difference.

**Comment by lancejpollard** [comment]
If you git clone the repo and link it to your app and try to install everything, do you get the same issue? Also, it may be because of the hard-coding to that specific version of hook.io, which may not work on OSX 10.8. Try doing `>= x` for the version of hook.io.

**Comment by thehydroimpulse** [comment]
Still the same effect. I posted a new issue on the hook.io project but the project is no longer in development, which could be the reason why it doesn't work on mountain lion.

**Comment by j-mcnally** [comment]
@TheHydroImpulse  hook.io is deprecated and uses an old version of weak that uses waf which does not work in 10.8. I have a work around but it requires you build tower from src.

https://gist.github.com/3740178

If you have problems following this join us in #towerjs on irc.freenode.net

**Comment by thehydroimpulse** [comment]
@j-mcnally Thanks! This solved the problem.

**Comment by edubkendo** [comment]
I think we need to look at replacing hook.io or forking the repo because this is going to stop lots of dev's in their tracks

**Comment by thehydroimpulse** [comment]
yup. It road blocked me for a few days at least. Maybe updating the README file to alert mac developers running mountain lion.

**Comment by lancejpollard** [comment]
Thanks @j-mcnally for that workaround! Seems like the hook.io and node-weak authors should merge in your changes
- https://github.com/j-mcnally/node-weak/commit/274e3f1b288e2421ff93244a4b650d1b9219bf5a
- https://github.com/j-mcnally/hook.io/commit/8160fe5e5c5c8a3c6366feaea8ed0cb2b9fc2720

I will look into removing hook.io temporarily as well, since it's only being used to send data to the browser from records you modify from within `tower console`:
- [packages/tower-application/server/application.coffee#L187](https://github.com/viatropos/tower/blob/d340a33aaaf62d6d6cebdd907eb98ef9bc7f7b6d/packages/tower-application/server/application.coffee#L187)

That's just a *nice to have*, shouldn't require this workaround. Thanks for figuring it out though, helps a lot.
