### ISSUE TITLE
Add an easy setup hook to for ember templates [Enhancement]

### ISSUE THREAD

**Issue by j-mcnally** [tower-archive/tower#287]
``` coffeescript
App.TemplateData = Ember.Object.create
  page_title: ( ->
      @.get('_page_title');
    ).property('_page_title');
  page_sub_header: ( -> 
      @.get('_page_sub_header');
    ).property('_page_sub_header');
  _page_title: "team"
  _page_sub_header: "kohactivators, mount up!"


App.View = Ember.View.extend
  init: ->
    if @.setup?
      @.setup()
    @._super()
```

Then in a view -->

``` coffeescript
App.HomesIndexView = App.View.extend
  templateName: 'homes/index'
  setup: ->
    App.TemplateData.set('_page_title', 'Kohactive')
    App.TemplateData.set('_page_sub_header', 'Take the dive')
```

_header:::

``` coffeescript
div class: "row-fluid page-header", ->
  div class: "span8", ->
    h1 -> span "{{App.TemplateData.page_title}}"
    span class: "sub-header", "{{App.TemplateData.page_sub_header}}"
```

Perhaps we should have a Tower.View that could encapsulate some of this data along with some sort of global like Tower.TemplateData.

This type of workflow works we'll when you want to share properties accross templates. Maybe its best to leave this up to the end user but it took me a big to figure out so maybe atleast this post will help someone else out.

**Comment by j-mcnally** [comment]
@viatropos , I think a DSL for setting properties would be nice, i feel like it could get a bit redundant, i'd build that out if you think this is a good idea.

**Comment by lancejpollard** [comment]
Not quite sure what you're trying to accomplish here. Is this basically a layer between the model and the view?
