### ISSUE TITLE
Development Flow?

### ISSUE THREAD

**Issue by thehydroimpulse** [tower-archive/tower#291]
I'm wondering if the way I have my tower development environment is the "right" way. It works but it becomes a pain when I have to wait for the build of the Javascript files. 

So I'm always going about changing files within **packages/tower-controller/client/**. From what I experienced I'm assuming these files are all concatenated and placed within a single **tower.js** within the **dist/** folder. The problem for me is that the default grunt tasks when watching for changes within any *.coffee files, it doesn't re-build the tower.js within the dist folder. Which leads to the client-side "framework" not being changed within the browser. 

So I went and changed the grunt file and added a "build:client" task after a coffee file is changed. This completely solves the problem but adds a HUGE lag. Sometimes it takes 10-40 seconds for the build completes and then I can go and refresh the browser to see the changes. This works, but it's an awful efficiency issue. It seems like i'm running a rails command.

The tower.js file is then linked to one of my demo apps inside vendor/javascripts. 

So I'm wondering if I have the development flow wrong and missing a piece here? If someone could enlighten on my issue here that would be great!

Thanks,
Daniel

**Comment by lancejpollard** [comment]
No this is an issue, thanks for pointing it out. Right now the client `./dist/tower.js` isn't rebuilt for every change, for the same reason that it adds a lag to development.

What we should do is compile each package into a dist/ file (`dist/tower-support.js`, etc.). This would be an initial way to speed things up.

In the long term we should integrate something like requirejs or some other more formal system. It seems that those approaches would take a while to implement though, so I haven't even really considered them yet.

For now we need a grunt task to compile the top-level packages. I think I started that but it's not finished. Do you want to tackle this @TheHydroImpulse? Sounds like you're already almost there. This is definitely a useful thing to have!

**Comment by thehydroimpulse** [comment]
Thanks for the response. Yeah i'll take a look. I got the grunt all figured out now so i'll see what needs to be done. And I do like the requirejs implementation. Possibly having each package file become it's own module just like in the coffeescript. Possibly even having a lazy-loading feature to kick-start the application faster? Though there is a lot of boilerplate code that needs to be loaded right away it could be something to do in the optimization steps.

I'll keep you posted about the grunt. I'm almost done with the sockets too.

**Comment by lancejpollard** [comment]
\m/ looking forward to it

**Comment by lancejpollard** [comment]
Yeah it would be really great if, when building an app and you ran into some unimplemented feature or bug on the tower client, you could just modify the tower source and refresh the browser and it would load the new tower client code just as if you changed some file in your app. That would be awesome.

I'm going to try to set this up so it will load each file individually on the client if you're linked to the tower repo.

**Comment by lancejpollard** [comment]
@TheHydroImpulse Have you started doing anything with require.js?

If you add the tower module to the static paths in `app/config/server/bootstrap.coffee`, you can load it easily in the browser:

``` coffeescript
App.configure ->
  @use 'favicon', Tower.publicPath + '/favicon.png'
  @use 'static',  Tower.publicPath, maxAge: Tower.publicCacheDuration
  @use 'static',  Tower.joinPath(Tower.root, 'node_modules/tower/lib'), maxAge: 0
```

``` coffeescript
# in some app/templates
script src: '/tower/client.js'
```

**Comment by thehydroimpulse** [comment]
@viatropos That's pretty sweet. A much cleaner version of what I did; just used symlinks from the tower source to any tower project. But this is a much better alternative.

No I haven't started on require.js per say, I'm working on implementing the IoC first to get some centralization going, but then I'll take a look at require.js, especially on the client-side.
