### ISSUE TITLE
Test that when you change a file in the app, it gets reloaded properly

### ISSUE THREAD

**Issue by lancejpollard** [tower-archive/tower#293]
How are you supposed to test this practically? Are mocks/stubs normally used in this situation? Need to test that reloading changed files works cross-os.

**Comment by scottkf** [comment]
Shouldn't grunt test for this? Or are you testing your integration of grunt? If so, you can setup a simple test gruntfile just for grunt so it performs faster

**Comment by lancejpollard** [comment]
Yeah I want to test the integration of it (it's actually just with chokidar in `tower-application/server/watch.coffee`, not grunt).

There's a lot of these integration-level things that we need to test and I don't yet see a solid pattern for how/when to test them. The insights help. This stuff unexpectedly breaks every now and then and we need a way to prevent that.
