### ISSUE TITLE
RequireJS & Optimizations

### ISSUE THREAD

**Issue by thehydroimpulse** [tower-archive/tower#294]
So the goal would be to incorporate require.js into the client-side environment. I came across some awesome optimization tools that come with require that could shorten the amount of code that's sent to the browser: http://requirejs.org/docs/optimization.html#hasjs

Maybe this could be incorporated into grunt or the build process but we could effectively create "build" systems for different environments. For example on mobile you could leave out specific tower or other modules or require alternative ones. Maybe you can go even further and apply this to routes and only require the up-front routes first. Then lazy-load the later controllers, models, etc.. when they are needed.

**Comment by edubkendo** [comment]
you might want to have a look at how: http://brunch.io/ does it. Especially https://github.com/icholy/ember-brunch  . I don't think we need another build tool (grunt is awesome) but I do think brunch does a pretty good job of making require.js work well. There is also the way a lot of people doing Rails w/ ember work, using Rake Pipeline and minispade. Might be useful for inspiration. Here's a good example of a workflow that seems to be popular: http://blog.nulayer.com/post/23294069876/building-simple-javascript-libraries-with-rake-pipeline

**Comment by lancejpollard** [comment]
I'm liking the look of brunch.io. Sidenote: we should allow people to pick between grunt and brunch if they really want (eventually).
- https://github.com/asciidisco/grunt-requirejs
- https://github.com/jrburke/almond
- https://github.com/jrburke/requirejs/blob/master/require.js#L17
- https://github.com/jrburke/requirejs/blob/955e93f922be7bf31d9f43ec2cbdcaf1655d42af/require.js#L1979-2000
