### ISSUE TITLE
EJS dev dependencies?

### ISSUE THREAD

**Issue by thehydroimpulse** [tower-archive/tower#297]
Some people in the irc commented about how they had to install ejs separately to get tower working. It seems that ejs is included in the devDependencies but wondering if it's used anywhere?

**Comment by lancejpollard** [comment]
It is only used by the generator: https://github.com/viatropos/tower/blob/master/packages/tower-generator/server/generators/tower/model/templates/model.coffee

What is the issue people are having? I'll be on IRC early tomorrow.

**Comment by thehydroimpulse** [comment]
ahh that makes sense. I guess it confused some people because it wasn't included in the dependencies and they had to install it manually. Of course it's a simple step install, but for new comers they might not know what to do when presented by those errors.

**Comment by lancejpollard** [comment]
It seems the reason it wouldn't install is because they have `NODE_ENV` set to `production`, or something like that, which makes it so `devDependencies` aren't installed. You can change that with:

```
npm config delete NODE_ENV --global
```

https://npmjs.org/doc/config.html
