### ISSUE TITLE
Incorrect template rendered

### ISSUE THREAD

**Issue by lumin3000** [tower-archive/tower#30]
I have these in my app:
/chunks/new
/items/new
/users/new

They are all rendered as the same template (the one I visited first)

Here I found this code at  "Tower.View.Rendering._readTemplate(template, prefixes, ext)"

``` coffeescript
result = (_base = this.constructor.cache)[_name = "app/views/" + template] || (_base[_name] = this.constructor.store().find({
```

should I change it to:

``` coffeescript
path = prefixes?(prefixes+'/'+template):template
result = (_base = this.constructor.cache)[_name = "app/views/" + path] || (_base[_name] = this.constructor.store().find({
```

The rendering is working fine currently after this change.

**Comment by lancejpollard** [comment]
working on a cleaner view/path system for this…  thanks for the fix tho.

**Comment by tomchentw** [comment]
[ Edited ]
After trying the fix at the correct line, it solved. Thanks !!!

# 

I'm not sure if I got the same issue here...
I've tried :
tower new app
cd app
tower generate scaffold Post title:string body:text belongsTo:user
tower generate scaffold User email:string firstName:string lastName:string hasMany:posts

then starting the server.
However, when I first click the "user" navigation on the top bar, it redirects to /users => index right?
Now, I click "post" and navigate to /posts => index, but here comes the problem:
1. The title is not refreshed to "Posts"
2. The content of table > tbody is all the script include tag, which should be loaded outside the table tag.
What can I do now...? Thanks!

**Comment by awnist** [comment]
can confirm that scaffolding seems broken as @tomap41017 is describing. Getting inconsistent templates depending on order.
