### ISSUE TITLE
Scaling, Speed, Optimizations...

### ISSUE THREAD

**Issue by thehydroimpulse** [tower-archive/tower#301]
(Some of this was discussed in the irc)
I thought i'd make an issue here to discuss some possibilities on scaling, speed, and optimizations.  

Because the V8 engine is single threaded (with reason because it's meant for the browser) this leaves the node world on a single execution thread. We can do multi-threading with the help of clustering multiple node.js instances across a single server. This is all great but ads a limit to how systems can handle data, memory, etc... When clustering you have to offload all the data to databases of all kinds (redis, mongodb, mysql, etc...). But tower.js wasn't really designed this way. It heavily uses local memory storage (with possibility of offloading to redis, etc...). 
## Master and Slaves

This concept is pretty simple and is used by other software. Essentially you would have a single "master" Tower.js instance running and under the master it would execute many many slaves. The master would only need to load the infrastructure, then each slave would essentially start from a cached infrastructure leading to insane start up times (really fast). The problem is node.js or specifically V8 doesn't support a shared memory architecture. Meaning each instance are a complete seperate V8 instance and cannot be shared. 
### AST - Abstract Syntax Tree - Javascript

This could be the solution.... before parsing the Javascript to machine code the V8 engine would create a AST. Basically a tree of execution nodes of various functions and such. The concept is we could essentially "clone" the AST state of the master then send it off in the V8 engine for each slave. This means each slave would start with a cached AST.

**Resources:**
- [Google's V8 Javascript Engine - **AST File**](http://v8.googlecode.com/svn/trunk/src/ast.h)
- [Node.js AST Parse, Mangler, Modifier - UglifyJS](https://github.com/mishoo/UglifyJS#uglifyjs-%E2%80%94-a-javascript-parsercompressorbeautifier)
- [Node AST Module](https://github.com/dresende/node-ast-transformer) - (Apparently this does more than just modifying the AST)

**Edit:** UglifyJS also provides a way to mangle or modify the AST.

The uglifyJS package offers the ability to generate a AST and also parse a AST. This would probably take a little while to develop but the turn out could mean a huge improvement to speed. This means that slaves could boot up in no time, and would improve the development environment.

**Edit:** It seems the way it works is as follows: You would have a front-end looping module that would load and cache Tower.js' AST. We could essentially have a front server file **load.js** that would take care of loading the other files (in this case through the AST). 

This would also provide some extra debugging features possibly. (Would obviously add complexity)
### Examples
- https://github.com/dresende/node-ast-transformer/tree/master/examples
  
  Again a lot of this is speculation and or theoretical so take this with a teaspoon of salt.

**Comment by careo** [comment]
This is is exactly the use case for the cluster module (http://nodejs.org/api/cluster.html) in Node.js. It provides everything you'd need to manage a pool of workers, including some slick event support and hooks to automatically ensure the children are sharing the sockets.

Sadly, I don't think Node.js has a copy-on-write friendly GC, so the workers won't end up using all that much memory from the master.
