### ISSUE TITLE
Client Side Destroy

### ISSUE THREAD

**Issue by edubkendo** [tower-archive/tower#302]
Can't seem to destroy a model's instance on the client side. The "destroy" action ( https://github.com/viatropos/tower/blob/master/packages/tower-controller/client/actions.coffee#L40 ) calls a method "destroyResource" that seems to be missing. The others (createResource, findResource, etc) are all [here](https://github.com/viatropos/tower/blob/master/packages/tower-controller/shared/resourceful.coffee) but deleteResource (and updateResource, just noticed) is missing.

**Comment by thehydroimpulse** [comment]
Yup it's a common problem apparently. This also relates to the syncing for resources - create works but update and delete don't sync up. Might have to write those two methods.

**Comment by edubkendo** [comment]
I can get around this by changing my client side controller's to look like this:

``` coffeescript

class App.UsersController extends Tower.Controller
  @scope 'all'

  # @todo refactor
  destroy: ->
    resource = @get('resource')
    App.User.destroy(resource)
```

With "User" being replaced by whatever the model for that particular controller should be. This does not, however, cause it to sync across browsers. As @TheHydroImpulse points out, it appears that the only action currently bound to the scope, and thus, registering in multiple clients from the server, is the create action. I'll make a seperate issue for that, though.

**Comment by edubkendo** [comment]
This is fixed in my pull request, both parts actually, so gonna close this to keep issues tidy.

**Comment by lancejpollard** [comment]
Sweet.
