### ISSUE TITLE
Move Tower-Docs to the Wiki

### ISSUE THREAD

**Issue by lancejpollard** [tower-archive/tower#306]
And have the wiki be a submodule.

What do you guys think of this? It would make it easier to contribute since it feels closer. Then you could do `git submodule init` if you clone the tower src and it will grab the wiki, so you could git push/pull from the wiki too.

Having the separate tower-docs repo makes it feel like too much work to modify.

**Comment by edubkendo** [comment]
I think we still need to address the fact that it feels like documentation is in a million different places, and none of it seems to agree with each other, but all in all, I think having the docs in a wiki so its really easy to modify is a good thing. Currently, it feels like a pain to work on them, and I often forget all about doing so. I think making the docs easy to access is probably the most important factor.

**Comment by lancejpollard** [comment]
Agreed. Also by putting it in a submodule, it will be much easier to add to the tower src `grunt` tasks to compile the wiki for the website, etc.

I am redoing the docs, updating them will make it much easier to get started.

**Comment by careo** [comment]
For docs, would there be any value in using one of the automatic doc generators for JS? 

Is there anything for coffee like that?

**Comment by lancejpollard** [comment]
Yeah tower is using [codo](https://github.com/netzpirat/codo) for the docs, though I haven't run it in a while so there's probably some formatting issues to update in the comments. You can try with:

```
npm install codo -g
codo ./packages
```

**Comment by lancejpollard** [comment]
Added a `make docs` task.

**Comment by maedi** [comment]
Thanks. I've added a draft beginners guide to the wiki:
https://github.com/viatropos/tower/wiki/Tower-Beginners-Guide

**Comment by lancejpollard** [comment]
Nice work on https://github.com/viatropos/tower/wiki/Tower-Beginners-Guide @Maedi!
