### ISSUE TITLE
Why do form action pass through the router rather than hitting them directly?

### ISSUE THREAD

**Issue by j-mcnally** [tower-archive/tower#309]
The scaffold has the following

```
    # @todo
    # if @get('resource.isNew')
    #   @get('controller.target').send('createBlogs')
    # else
    #   @get('controller.target').send('updateBlogs', @get('resource'))
```

imo, the @todo implementation would be

```
 @get('controller').create(@get('resource')) is there a reason we'd want to go through the router for this?
```

**Comment by lancejpollard** [comment]
It doesn't necessarily need to go through the router, but I think it should execute the controller action the same way the router does it (that was the initial reason for making it use the router).

**Comment by j-mcnally** [comment]
would the create function ever happen through the router outside of this implementation tho?

**Comment by lancejpollard** [comment]
This is going to be much different in tower 0.5.0 (ember also does this much differently now as well).
