### ISSUE TITLE
cake watch error

### ISSUE THREAD

**Issue by jupy** [tower-archive/tower#317]
After following commands:

```
tower new app-name-here
cd app-name-here
npm install
tower generate scaffold Post title:string body:text belongsTo:user
tower generate scaffold User email:string firstName:string lastName:string hasMany:posts
cake watch
```

I've got:

```
path.existsSync is now called `fs.existsSync`.
execvp(): No such file or directory
```

version of tower: 0.4.2-4

**Comment by thehydroimpulse** [comment]
I've had this problem before so i'll try to remember what I did to fix it...

What OS are you using? (Mac?)

Did you install grunt globally? `sudo npm install grunt -g`

Try running grunt directly and skip cake: `grunt start --config ./grunt.coffee`

**Comment by jupy** [comment]
My OS is Ubuntu 12.04.1 LTS
I've installed grunt globally. Here is the result:

---

cake watch
path.existsSync is now called `fs.existsSync`.
Default database not set, using Memory store
Running "copy:js" (copy) task
Copied 35 files.

Running "copy:css" (copy) task
Copied 2 files.

Running "coffee:all" (coffee) task

Running "less:bootstrap" (less) task

Running "stylus:compile" (stylus) task
File 'public/stylesheets/app/stylesheets/client/application.css' created.

Running "templates:all" (templates) task

Running "watch" task

## Waiting...

It seems cake hangs after 'Running "watch" task'.
If I run grunt directly, I have the same result.
Could you help?

**Comment by thehydroimpulse** [comment]
There is no problem. The process runs in a 'loop' so to speak. It needs to keep watching the file system for changes in each file (add, delete, update). 

So it seems like your good to go. The normal environment as suggested by @viatropos is to have a terminal window for each project. Inside each terminal window you'll have a minimum of two tabs: **Node.js Server**, and `cake watch` process. You could have another tab for using other `cake` commands and / or scaffolding feature. It may seem a little strange at first having to run a separate command to watch for changes but that's how it's done.

**Comment by edubkendo** [comment]
yeah the "watch" task means it continues to run and watches the directory, just leave it running while you develop or run the server. (obviously you can turn it off when you arent working). Then in another tab just run your node server.js.

**Comment by jupy** [comment]
Ok. Thank you very much.
