### ISSUE TITLE
Issue Installing Towerjs

### ISSUE THREAD

**Issue by bendangelo** [tower-archive/tower#319]
Following the instructions for the first time:

```
npm install tower -g
tower new app
```

I get an error:

```
Error: Cannot find module 'ejs'
```

I fixed it by running

```
npm install ejs -g
```

I think this should be mentioned somewhere for beginners.

**Comment by bendangelo** [comment]
Ok, so i'm following the generator commands:

```
cd app
tower generate scaffold Post title:string body:text belongsTo:user
```

I got an issue running tower generate:

```
Error: Cannot find module 'tower'
```

Fixed it by running:

```
npm install tower
```

Am I doing this right?

**Comment by bendangelo** [comment]
Looks like I had to install lots of packages to even run:
    tower server -p 3000

I think these should be added as dependencies or mentioned on the site:
    socket.io, mongodb, coffeecup, coffee-script and chokidar

Now i'm getting an error:
    Error: Constant 'App.' wasn't found
        at _.extend.constant (/home/blah/app/node_modules/tower/lib/tower-support/shared/shared.js:270:15)

I was hoping the installation would go smoother. Great work so far.

**Comment by lancejpollard** [comment]
What is you operating system, node version, and npm version? It should be working, we're just fine tuning windows installation and installation may have broken elsewhere but should be easy to fix.

**Comment by edubkendo** [comment]
@bendangelo it looks like when you created your new app, and cd'ed into it, you didn't run "npm install" to install the app's dependencies. This is why you were having to install tower and other things by hand.  The ejs thing is a seperate weird issue, you shouldn't have had to install that manually.

**Comment by edubkendo** [comment]
to clarify, creating a new app should go like this:

```
tower new myAwesomeApp
cd myAwesomeApp
npm install
cake watch
```

Then, open a second terminal tab and run your server, run generators, etc. Also, if you run a generator, you may need to re-start the "cake watch" task, though normally it should pick up changes to your app on its own, I'm not sure if it picks up newly generated stuff without being restarted. Pretty sure this info is available in the README

**Comment by lancejpollard** [comment]
@bendangelo were you able to get past this? going to close the issue if so, let me know. thanks!

**Comment by bendangelo** [comment]
Those steps worked for me. Except:
    cake watch

I'm on Ubuntu 12.04 x64. Nodejs 0.8.11. Npm 1.1.62

**Comment by thehydroimpulse** [comment]
What didn't work with `cake watch`?

**Comment by bendangelo** [comment]
Oh sorry. It says cake is currently not installed. I couldn't find anything in npm. What is it?

**Comment by edubkendo** [comment]
do you have coffeescript installed globally? cake is coffeescript's version of make/rake/jake/etc

**Comment by bendangelo** [comment]
Ok I ran:

```
npm install coffee-script -g
```

and it worked. Thanks.

**Comment by thehydroimpulse** [comment]
Can you close the issue?
