### ISSUE TITLE
node.js to use sublime's tab completion?

### ISSUE THREAD

**Issue by lancejpollard** [tower-archive/tower#330]
@edubkendo is there a way to hook into Sublime Text 2's tab completion somewhere?

It could be possible (even easy) to make the `tower console` use the autocompletion stuff from different editors (sublime, textmate, etc.), all that's needed is a command line api or something like `subl --input "App.Po"`, and it would give `App.PostsController` and `App.Post`, etc.

That would be cool.

**Comment by lancejpollard** [comment]
p.s. `tower console` is way better now, just added a few things:
- cursor.toJSON(), so you can do `App.Post.all().toJSON()` and it will print colored JSON (from node's own console.log stuff)
- `App.Post.destroy()`, `update()`, and `create()` all work on `n` number of records, using the synchronous option, so you can do `App.Post.update(public: true).toJSON()` and see the records you just updated.
- You can press up/down to go through the repl history, even when you exit out and start the console again (it's stored in `./tmp/replHistory.coffee`). Only setup for the coffee repl so far, but it's very easy to port.
- After entering code in the repl and pressing enter, it will always resolve on the `tower>` prompt, whereas before you sometimes had to press enter to reset it (super annoying).

This readline stuff is super powerful stuff, check out the code it's by far the best documentation on it:

https://github.com/joyent/node/blob/master/lib/readline.js

Cheers!

**Comment by edubkendo** [comment]
@viatropos If you use my fork of SublimeREPL (cause I'm not sure if he ever merged my pull request) you can use Tower's console in sublime text, with it's code completion, syntax highlighting, and all. Pretty awesome stuff. As far as pulling that out of sublime and into the terminal or something, that would go deeper into sublime's internals than I've tried to do.  Also, installing this package: https://github.com/alienhard/SublimeAllAutocomplete  will give you autocompletions for all open files, so you can have completions for everything in the console that your currently working on, which is awesome. There's a SublimeCodeIntel package, which would be even more awesome except it doesn't currently support coffeescript. I'm currently watching it closely and have made that feature request along with numerous other people so hopefully we'll see it happen. I'm also planning to port the node.js package by @tanepiper to coffeescript, so those snippets will work with completion in coffee files, as well as starting a collection of tower specific snippets which would be useful. LOL. so much to do.
