### ISSUE TITLE
Error on client-side with models called "Event"

### ISSUE THREAD

**Issue by sebastianhoitz** [tower-archive/tower#337]
I have a model called Event.

It seems that the client-side tower stuff seems to have problems initializing the pages with a model called like this, because

```
Tower.constant(this.resourceType)
```

returns the browsers Event object. This causes this error:

```
Uncaught TypeError: Object function Event() { [native code] } has no method 'where'
```

I don't know what would be the best case to handle this...

**Comment by sebastianhoitz** [comment]
I took a quick look at the Tower.constant method.

It seems like this would prevent developers from using any model names, that are also existent in the global namespace, since those are given a higher priority:

https://github.com/viatropos/tower/blob/master/packages/tower-support/shared/shared.coffee#L255

**Comment by thehydroimpulse** [comment]
The inversion-of-control container and more specifically, the service locator will fix this issue entirely. Basically, you will technically never access any resources like: 

``` coffeescript
Tower.Controller
App.ModelName
```

You will write it out as such, but behind the scenes (using harmony proxies ftw), there's a huge system just to access and set resources. 

An example using this feature from scratch (isn't just Tower specific as I made a separate repository):

``` coffeescript
Context = require 'ettore'
Container = Context.create 'App'

# You can set properties or objects like:
Container.set 'Tower.Events', new (class Events extends Container.get('Tower.Class'))
Container.set 'App.PostsController', new (class PostsController extends Container.get('Tower.Controller'))

Container.configure ->
    @set 'Tower.Controller.Action', new (class Hello extends @get('Tower.Class')' # You can use the lazy-loading feature or just use node's require statement.
```

But you don't want to be using getters and setters in your whole applications; so you can create a bunch of aliases!

``` coffeescript
# Continuing from previous snippet:

global.App = Container.alias 'App'
global.Tower = Container.alias 'Tower'

# To access the previous resources you can use the new variables:
App.PostsController # Returns instance of class 'PostsController'.
Tower.Controller.Action # Returns instance of class 'Hello'
```

You can do a much of cool things. You can also (working on this atm) create two different containers. One for the app, and one for Tower objects. This will have a clean separation between objects and will also allow you to specify fallback containers if an object is not found within the current container. 

You can get more info here: #325

There might be a quicker solution to implement, but this would definitely have a resulting effect.

**Comment by sebastianhoitz** [comment]
Wow that sounds cool!

What about switching classes to mock objects for unit tests? Is that possible, too?

**Comment by thehydroimpulse** [comment]
Yes, the system fully supports mocking objects.

**Comment by sebastianhoitz** [comment]
Sweet :+1: Can't wait for it! :)

**Comment by thehydroimpulse** [comment]
:)

I'm almost done unit testing it, after which I'll start implementing it within Tower on another branch. Got a lot of ideas to go along with it, especially with optimizations of the front-end... The front-end or client-side IoC will be slightly different, with possibly having it's own module loader, that's a bit, awesome! Instead of lazy-loading on download, you lazy-load on parsing and execution, which makes the initial page load extremely fast. http://hydrocodedesign.com/blog/2012/10/21/javascript-modules/

**Comment by lancejpollard** [comment]
As a less-robust solution for now, does the last commit work for you?

**Comment by edubkendo** [comment]
Ran into this problem in irc today, person having an issue with "Comment" model, getting the exact same error. Grepping tower's source didnt reveal any use of "comment", so it must be in Ember. Whatever the case, we definitely need your permanent solution to this issue @TheHydroImpulse . Between Tower and Ember, there's just so many words in use, we're bound to start seeing more and more cases of this as tower picks up users and use cases.

**Comment by thehydroimpulse** [comment]
I hear ya. I've had that same problem with another framework and its quite
annoying.

Once I'm done the packages, I'll finish the IOC. Not sure when exactly, but
in a couple weeks for sure. Still trying yo get around some limitations or
weirdness in proxies.

**Comment by vraptor75011** [comment]
I m the one wha had the problem with model Comment today and talked with @edubkendo .
It seems that Tower.constant bugged because window.Comment is part of the DOM.
