### ISSUE TITLE
Length validations

### ISSUE THREAD

**Issue by iagooar** [tower-archive/tower#339]
I have been playing around with length validations and have tried this in my code:

``` coffeescript
class App.Foo extends Tower.Model
  @field 'foo', type: 'String'

  @validates 'foo', length: { maximum: 3 }
```

Each time I try to persist the model, I'm getting the same error as already mentioned in https://github.com/viatropos/tower/issues/157

But if I try this:

``` coffeescript
class App.Foo extends Tower.Model
  @field 'foo', type: 'String'

  @validates 'foo', length: { max: 3 }
```

then everything works fine.

The wiki says:

``` coffeescript
class App.User extends Tower.Model
  @validates 'name', length: { minimum: 2 }
  @validates 'bio', length: { maximum: 500 }
  @validates 'password', length: { minimum: 6, maximum: 20 }
  @validates 'registrationNumber', length: 6
```

So there are two solutions for this problem: either minimum and maximum should be called min and max, which I don't like personally, or the code in the Length validator should be changed so that it matches against the minimum and maximum keys.

Either solution would be fine. If you want me to fix the validator, I'll do it and send a pull request. Else, the wiki should be updated. Tell me what do you think about it guys.

**Comment by iagooar** [comment]
OK, next observation:

If you do

``` coffeescript
class App.Foo extends Tower.Model
  @field 'foo', type: 'String'

  @validates 'foo', length: { min: 1, max: 3 }
```

then the validation only checks the "min" value, ignoring completely the max value. This is obviously a bug and should also be fixed. As I said before, I'll do it once there is a decision about the naming of the min(imum) and max(imum) keys.

**Comment by edubkendo** [comment]
Yeah, the validations are kind of weakly implemented. I worked on them a little bit, which is why you had an example that worked, prior to that, length validations were actually comparing Numbers or something really broken like that. A robust solution would be awesome. I don't have a preference on max/maximum, but left it as "max" when I worked on them because that's what was already in the code. @viatropos should weigh in though.

**Comment by iagooar** [comment]
OK so I have been pushing myself through the validation model and have tried to fix this issue. You can watch the changes I made at my fork:

https://github.com/yagooar/tower/commit/0de69adc854168c5ffc3731e1e92df5709992260

I have tried to make possible the following inside a model definition:

``` coffeescript
@validates 'foo', length: { min: 1, max: 3 }
```

The main issue I discovered was at `packages/tower-model/shared/validator.coffee:44`

``` coffeescript
if typeof name == 'object'
```

It seems that name is always a string, as it defines the type of validation itself, so the condition was always false.

Then, I realized that actually this kind of definitions is unique amongst all other, because it includes actually two different validations: one for the minimum and one for the maximum value.

So I went one step back and changed the `@createAll` method so it can iterate over the elements of the hash and create more validators.

Everything works fine, tests are green, buuuut... I have tried this in an application and the problem now is:

``` coffeescript
@validates 'foo', length: { min: 2, max: 5 }
```

When I try to persist a model with this validation, 2 things happen:

-> If the attribute is too short, the validation works just fine, throwing an error
-> If the attribute is too long, the validation doesn't work, it seems like the model was persisted, but then if you reload it, no changes have been actually done to the attribute.

This is far beyond my current knowledge about the framework, so I'm asking you guys for help finding why this happens and how we could fix it. Take a look at my commit or checkout my fork and try this out.
