### ISSUE TITLE
SEO and browsers with JS disabled

### ISSUE THREAD

**Issue by jridgway** [tower-archive/tower#343]
Now that I have my first Tower prototype up and running, I can see the extent to which Ember is used on the front-end. Is Tower concerned at all with SEO and browsers with JS disabled? Is there any way in Tower to server pages that work well in these situations? Thanks!

**Comment by thehydroimpulse** [comment]
For all I know, Tower render's it's first request from the server which allows crawlers to find the content. I'm not sure if this has changed with all the additions, but could be implemented either way. I believe meteor has this problem for sure, because they are mostly client-side.

**Comment by lancejpollard** [comment]
Building off @TheHydroImpulse's comment, you can just not use client-side routing and every route will hit the server and you can have it render plain HTML the same way Rails would. In the future we're going to implement some sort of way to get both client-side views/routing (dynamic pages) and SEO/static pages, but we're going to have to work with Ember on that one. For now though, you can get SEO benefits by rendering static HTML.
