### ISSUE TITLE
scaffolding: sorting tables doesnt work

### ISSUE THREAD

**Issue by svasva** [tower-archive/tower#345]
Steps to reproduce:
- create an empty project
- scaffold some model
- run server
- save few model instances
- go to the model index page
- click on the table header (column name)
- it goes to "http://localhost:3000/users?sort=+" (my model name is User), and that is not even an AJAX request

**Comment by lancejpollard** [comment]
Thanks for posting. This hasn't been fully implemented yet, you are welcome to work on it and send a pull request if you'd like!

This should first be implemented using the server-side `tableFor` code, but should also be implemented in Ember on the client using the Ember.View in some way (maybe a mixin?).
