### ISSUE TITLE
Render wrong view

### ISSUE THREAD

**Issue by hotrannam** [tower-archive/tower#35]
I create 2 views - index.coffee - for 2 controllers called App and Post. I got the same rendering output is the first request regardless of request whether localhost or localhost/posts.

If I specify the path of post view as @render 'posts/index' then it works. What's wrong?

**Comment by lancejpollard** [comment]
Can you post all the code you're using, specifically:
- the paths to your views and controllers
- your controller code
- your `routes.coffee`
- your version of Tower `tower -v`
- and your operating system, node version `node -v`, and npm version `npm -v`

This problem existed in older versions but I don't see this problem anymore.  Wondering what your specifics are...

**Comment by hotrannam** [comment]
Once you mentioned it was a problem before, I try using node (0.6.12) and tower (0.3.9-11), the problem is disappeared. Thanks for awesome work!
