### ISSUE TITLE
Reference the piles of wiki documentation on the website

### ISSUE THREAD

**Issue by bobobo1618** [tower-archive/tower#353]
At the moment, the website doesn't appear to have any links to the wiki. As someone who discovered Tower through Google and came across the website first, I had some trouble figuring out what the hell I was doing. Especially with a few of the changes that have come about.

I know you're going through some big documentation changes but could you put something on the website alerting people to the stuff on the wiki in the meantime?

**Comment by thehydroimpulse** [comment]
Yeah this has been discussed many times. There are currently plans for a complete overhaul of the website butt i think the priorities right now are feature set, new api and especially all the new client side stuff that @viatropos has been working on. I'll take some time this week to maybe get a proper web design and documentation going.

**Comment by bobobo1618** [comment]
@TheHydroImpulse I'm not talking about the overhaul or anything like that. I'm saying go and put, on the website you have now, on the index or header something like 

```
<a href="wiki URL"><h1 style="font-color:#FF0000;">Wiki has more info, go here.</h1></a>.
```

Leave everything else the way it is, just leave a notice until you do the overhaul.

**Comment by thehydroimpulse** [comment]
Oh yeah. But I'm also thinking a good solid website would help new comers a
ton instead of using github wikis.

**Comment by bobobo1618** [comment]
@TheHydroImpulse I agree but as you said, that issue has been discussed many times :P

This is a separate issue.

**Comment by thehydroimpulse** [comment]
The websites source is on github. I'll submit a PR when I get to it.

Though once the new APIs come out, we'll really need a proper website with
examples, screen casts, demos, etc... But for now, a little notice should
be enough.

**Comment by lancejpollard** [comment]
We're working on the new site, very excited about it!
