### ISSUE TITLE
Publicity, Blog, Screencasts....

### ISSUE THREAD

**Issue by thehydroimpulse** [tower-archive/tower#361]
I've been thinking of this for a little while. I think for 0.5.0 we'll need to get awareness out there and promote the framework as much as possible. I think atm it's in a fragile state as things are moving, fluctuating a lot and the API isn't stable at all. When we hit 0.5.0, we'll be feature full, API would be fairly stable, though not 1.0 stable, but it'd become production ready.

I think around 0.5.0, before it launches, we should put up some sort of update blog similar to Ember.js. It's really helpful for new comers or whoever, when every week, or, every couple weeks you write what everyone's been working one, features, fixes, etc... and it would bring some publicity to the framework so that more people can use it. The more info we put out there, the more people will come. 

I'd be willing, and I'm sure other contributors might also want to update the blog with everyone's projects (within Tower) and what's ready, what's not, etc...

I think we could get a really good collection of screencasts when 0.5.0 comes out. I think many other frameworks lack in this area, especially meteor, and ember.js. They have "flashing" videos demonstrating the outcome, but rarely show much code and it's all copy-past or skipped. I'll definitely be making some screencasts, but the more, the better.

Thoughts?

**Comment by lancejpollard** [comment]
I totally agree, when 0.5.0 gets released we should have a few screencasts, a new site, and up-to-date documentation ready to go. I haven't thought of that blog idea, but it sounds great - every few weeks posting what we've been working on, new developments, challenges, etc.

I also agree that it's pretty rare that frameworks/projects in the past had enough docs/screencasts. It's because it takes a lot of time, and it's tough to say "this screencast is good enough" if you're not in the flow of making screencasts regularly (like, perhaps, railscasts or peepcode).

Do you have any ideas for screencasts and/or posts in mind? Maybe creating a list of desired docs/videos would be inspiring.

I have been doing a lot to standardize the API, and keep it local so as not to confuse anyone. It would be nice to have such docs/screencasts using a stable API so we can publicly discuss that kind of stuff.

**Comment by thehydroimpulse** [comment]
Awesome! Screencasts is the tricky one. I've been doing tutorial screencasts on Youtube for a couple years now and still have lots to improve. But it doesn't matter if we try 50 times and every time we start over, I think if we can get a really solid first few screencasts up, it'll get extremely easier over time. I think people, especially newcomers, need direction. They need steps 1 to 50, and transitions to each step. A lot of frameworks / screencasts (meteor for example) show a sped up version of step 1 and then skip to random steps there afterwords. It confuses the users who don't know where to start. Especially with this new technology, I would classify Meteor and Tower in the same group for future web apps, just an all-around new way to make applications. Users aren't used to this kind of thinking, programming, or concepts. Though Tower is more feature-full I'd say, and that means we would need more stuff out there. 

Written documentation would be the hardest one, as it's very tedious, and there will have lots of it. But there's a lot of people, myself included that would try to improve/finish it as much as possible. 

Screencasts Ideas:
- **Introduction**: A simple, yet intuitive introduction video that explains what Tower is, how it roughly works, and how to get started. An all-around well explained video.
- **Real-time**: Because Tower is built on this real-time approach, we should explain what the heck it is, how it roughly works (with references to future videos), etc...
- **MVC/App Structure**: This would be a simple video, but basically showing how an app structure look like and showing the controllers, models, views, and templates, and explaining each part separately.
- **JS or Coffee**: Probably not a long video, but something that demonstrates using both languages in Tower. I'm not sure where we are in that decision, so that'll impact this video.
- **Scaffolding a New Application**: Exactly that, we would start with installing Tower from npm, creating a new app and getting started. Maybe we should come up with a good demo app that would show the power that Tower has. Todo-lists are too simple. Blogs are again, too simple, though you could increase the feature-set of a blog, it's still in the past, though. I think something like what Meteor did in their screencasts. Something completely custom, yet somewhat simple.
- **Controllers**: Explaining all the different controller concepts, APIs, etc... both client and server-side.
- **Models**: How they work, etc...
- **Views**: x
- **Templates**: x
- **Router**: A somewhat big video demonstrating everything you can do with it, client and server. Possibly splitting it into smaller parts (i.e 3 10 minute videos are better then 1 30 minute video.) Because we explained the controllers, models, views, and templates previously, we can go ahead and introduce them to joining all the parts with the router.
- **Backgroung Jobs**: We still need to decide on a proper API, I think that'll come, we have some really good options, but we just need to get the balance right (model vs controller, etc...). 
- **Authentication**: Probably a later video, they'll definitely be more "basic" videos in-between, but we should definitely show how to build membership sites.
- **Packages**: Not sure if this should be in 0.5.0, but I think it could be. Lot's of tuning will have to be done, but it's pretty straight forward. Anyways, showing how they could create a package, distribute it with NPM, and we could possibly have a "Packages" section on the Tower website where people could add their packages to it. Though the packages would be stored on github/npm, it would just become a directory or yellowpages of sort.

I've got lots of ideas for screencasts, so this is just the beginning. If we have a strong documentation, video and written, we'll be rock solid. 

For blog posts, we could have the following:
- API decisions:
- Polls: Where we ask the community what they think of a particular part of Tower
- Progress: Explain, possibly weekly or bi-weekly at least where we are in progress, feature-set, improvements, fixes, etc...
- Releases: An obvious one. When we release a new version, we'd post up what's included, the things changed in bullet points. Breaking changes, etc...
- Interesting Problems: Things like the data synchronization, and other problems that we either have multiple solutions in mind or we actually solved the problem. 

I'm sure other people would have plenty of suggestions for topics, and once we release 0.5.0, new users would be perfect to ask what we can improve on.

**Comment by edubkendo** [comment]
I think one thing that would be super useful, in getting the docs ready, is if we had a list of ALL public API's, and whether or not they have yet been documented. I know that in the past I wanted to make a go at working on the docs and then just didnt really know what to do beyond reading through what was already there and updating/making some corrections. Of course, since this is in flux right now it's not something that could be finished right away, but it might be something that could start being listed out as its being worked on. Just a thought.
