### ISSUE TITLE
Nested controllers, relations in routes and custom REST API routes?

### ISSUE THREAD

**Issue by ragulka** [tower-archive/tower#374]
By looking at the routes Wiki page, I can see thtat Tower can automagically create resourceful routes for  a resource. I have 2 questions about the routes:
1. How can I prepend all routes with something, for example `/api/v1/` so that a route becomes `POST /api/v1/posts`?
2. How can I create relational/nested routes, for example `GET /api/v1/projects/:projectId/comment/:commentId` - any examples somewhere?

**Comment by maedi** [comment]
Regarding nested routes https://github.com/viatropos/tower/wiki/Routing-and-WebSockets
