### ISSUE TITLE
Proxy/Server Crashing

### ISSUE THREAD

**Issue by thehydroimpulse** [tower-archive/tower#380]
Thought I'd leave this here to keep things active. I'm currently adding a nice feature into Tower's new core that will prevent the whole process from exiting. Instead, the process will hang until a file has changed (or any other event). If the server crashes, the error will be printed in the command line and also within the browser. 
![Screen Shot 2013-02-06 at 10 23 54 PM](https://f.cloud.github.com/assets/565790/134719/01c52752-70f2-11e2-841e-1070779a9d11.png)

This might make Tower a lot easier to use when developing the framework itself or an app.

**Comment by thehydroimpulse** [comment]
This is still very raw, and not done, but while the server is down, all incoming connections (http, https, web sockets - yes even websockets) will be queued up with Buffers until the server is back up again. That means there won't be any loss in data or transactions failing.

**Comment by lancejpollard** [comment]
No way. This is awesome!

**Comment by thehydroimpulse** [comment]
I plan on integrating the bundler's watcher into this new system. This means that we can easily have multiple tower instances running all going through the single proxy. Because tower is now actually being spawned as a child process. 

On another note, I had to remove the node_modules file watcher for the packages. Its wayyy to slow for the current watcher.
