### ISSUE TITLE
Install issue on OSx

### ISSUE THREAD

**Issue by gilbertbw** [tower-archive/tower#383]
I tried installing tower using '''npm install -g tower''' it appeared to work fine but '''tower''' was not a recognised command. I then tried '''npm cache clean''' and then '''npm install -g tower'''. But it failed

console log & log file: https://gist.github.com/gilbertbw/4951927

**Comment by thehydroimpulse** [comment]
That chmod error is because you need root privilege to install modules
globally.

**Comment by gilbertbw** [comment]
with 'sudo npm install -g tower' the install runs without error but running 'tower' I receive the error '-bash: tower: command not found'

**Comment by lancejpollard** [comment]
Try uninstalling the global tower then reinstalling:

```
npm uninstall tower -g
npm install tower -g
```

Also, if you have ever run `npm link` from within a cloned version of the GitHub repo, then `cd` into that repo and run `npm unlink`.

**Comment by gilbertbw** [comment]
I ran the both commands 'sudo', with no success. I then uninstalled 'sudo' and reinstalled with standard permissions, the install ran fine but 'tower' is still unrecognised.

**Comment by lancejpollard** [comment]
Maybe npm executables aren't found. Try adding your `/usr/local/share/npm/bin` path to your `~/.bash_profile` (http://dandean.com/nodejs-npm-express-osx/#telling-your-system-where-to-find-node).

Your `~/.bash_profile` should looks something like below (this is how mine looks):

``` bash
export PATH="$HOME/.rbenv/bin:/usr/local/share/npm/bin:/usr/local/bin:$HOME/bin:$PATH"
```

**Comment by paxer** [comment]
adding <code> /usr/local/share/npm/bin </code> - fix the problem for me. Thanks!
