### ISSUE TITLE
Upgrading from Grunt 0.3 to 0.4

### ISSUE THREAD

**Issue by colinwren** [tower-archive/tower#384]
Grunt 0.4 came out on monday (Febuary 18th) with significant changes that make tower.js incompatible with the current version of Grunt. Here is the [migration guide](https://github.com/gruntjs/grunt/wiki/Upgrading-from-0.3-to-0.4) with information on how to transition to the latest version of Grunt.

**Comment by thehydroimpulse** [comment]
Right now I'm guessing that Tower won't move to grunt 0.4 unless someone sends a PR and that will become useless for reasons I'll share below. Were working hard on Tower version 0.5.0. I don't want to say too much at this point, but let's just say it's different, very different. As a result, we are dropping grunt all together.

**Comment by lancejpollard** [comment]
See https://github.com/viatropos/tower/issues/386
