### ISSUE TITLE
Grunt Missing

### ISSUE THREAD

**Issue by ghost** [tower-archive/tower#386]
Hi,

I have installed tower and done everything up to the point where i have to execute the command "cake watch" and i receive this error. I already install grunt globally but i still receive this error

![prob](https://f.cloud.github.com/assets/3678954/188107/e7201996-7dc3-11e2-8448-0bd3a3f4f0df.PNG)

**Comment by edubkendo** [comment]
grunt has to be installed globally: `npm install -g grunt` but from what I understand the current version of grunt doesnt work, so you'll deliberately need to install an older version of it. I don't know what the exact version number is, but maybe @TheHydroImpulse can tell us? anyways, these errors will be resolved in the next version of tower, coming in a couple weeks, as the install process (as well as everything else) has been vastly streamlined.

**Comment by ghost** [comment]
Ok i try `npm install -g grunt@0.3.x` both locally and globally and i receive another error.
The grunt.js is located in the folder
![prob2](https://f.cloud.github.com/assets/3678954/188848/b5055320-7e15-11e2-81d0-f7552a4ff160.PNG)

**Comment by lancejpollard** [comment]
Try installing grunt 0.3.x, such as this:

```
# inside your app:
npm uninstall grunt
npm install grunt@0.3.17
```

**Comment by ghost** [comment]
I still have the same prob after installing grunt@0.3.17. Please help!!

**Comment by lancejpollard** [comment]
Grunt 0.4.0 installed a separate `grunt-cli` npm, maybe try uninstalling that too:

```
npm uninstall grunt -g
npm uninstall grunt-cli -g
npm install grunt@0.3.17 -g
```

Also, try to run the `grunt` executable locally (it seems you tried but I don't think you were referencing the local executable):

```
# in your app directory:
./node_modules/grunt/bin/grunt
# or maybe ./node_modules/.bin/grunt
```

If that works, then you can change the reference in the `Cakefile` (from the `cake watch` command) to point to `./node_modules/grunt/bin/grunt` rather than `grunt`.

**Comment by ghost** [comment]
I run the grunt in the app directory and receive this error. 
![prob3](https://f.cloud.github.com/assets/3678954/189233/5c136286-7e59-11e2-806c-95c2e6d9f34f.PNG)

And also can you show me how to change the reference in the `Cakefile`?

**Comment by lancejpollard** [comment]
I don't think you can run commands from inside those directories, because npm looks for modules, e.g. `require('some-lib')`, in relation to the app's root (I think), which has the `./node_modules` folder. I think the error you just got is because of this.

Try running the commands only from your app's root directory.

To manually change the `Cakefile`, go to [Cakefile#L11](https://github.com/viatropos/tower/blob/fec2c17af23ac7dfb3c385d79fb8de5db89d5aea/packages/tower-generator/server/generators/tower/app/templates/cake#L11) and change it to:

``` coffeescript
watcher = spawn('./node_modules/grunt/bin/grunt', args)
```

**Comment by ghost** [comment]
Ok i tried and this is what i get
![prob4](https://f.cloud.github.com/assets/3678954/189238/f5829d0a-7e5a-11e2-9211-9541bc2b8920.PNG)

**Comment by lancejpollard** [comment]
Ok, making progress :)

So that `Unable to find "grunt.js"` error is a Grunt 0.3.0 error. [Grunt 0.4.0](http://gruntjs.com/getting-started) looks for `Gruntfile.js`, while 0.3.0 looks for `grunt.js`.

For Grunt 0.3.x, you can also specify the path to the grunt file, so what we were doing is this (since we were using coffeescript instead of javascript):

```
grunt --config ./grunt.coffee
```

So, try running this:

```
grunt --config ./grunt.coffee
```

That `x1 is not a valid Win32 application` error, I have no idea... It could be because of file paths (unix uses `/` while windows uses `\`). So if there are any paths you're writing (such as `./node_modules/grunt/bin/grunt`), try using backslashes.

**Comment by lancejpollard** [comment]
Also, that error `failed to connect to [127.0.0.27017]` is because mongodb isn't running. Make sure mongodb is installed and is running.

http://docs.mongodb.org/manual/tutorial/install-mongodb-on-windows/

**Comment by ghost** [comment]
Ok i solved the server prob. The grunt i still receive some errors. 
![prob5](https://f.cloud.github.com/assets/3678954/189255/672e81a0-7e5e-11e2-8436-efb350fd8e19.PNG)

How to you fixed grunt to read grunt.coffee instead of grunt.js? Do I have to execute this `grunt --config ./grunt.coffee` everytime?

**Comment by lancejpollard** [comment]
Yes, execute that:

```
grunt --config ./grunt.coffee
```

The `cake watch` command should have abstracted that, see [Cakefile#L8](https://github.com/viatropos/tower/blob/fec2c17af23ac7dfb3c385d79fb8de5db89d5aea/packages/tower-generator/server/generators/tower/app/templates/cake#L8).

**Comment by ghost** [comment]
Ok but when i execute cake watch i still get the above error. 

When i execute `grunt --config ./grunt.coffee`, I get this,
![prob6](https://f.cloud.github.com/assets/3678954/189305/c5e2d43c-7e66-11e2-8d6a-0a71cebe80a2.PNG)

**Comment by lancejpollard** [comment]
Looks like you're close.

Try uninstalling all the grunt modules in your app, and installing the ones that match the 0.3.17 grunt you installed. (By uninstalling `grunt-contrib-less` and `grunt-contrib-stylus`, but keeping your `grunt@0.3.17`, when you run `npm install` in your app, it will [I think] install the grunt less/stylus versions that match `grunt@0.3.17`). So try:

```
# in your app directory:
npm uninstall grunt-contrib-less grunt-contrib-stylus grunt-contrib
npm install
```

If you get any errors with `npm install`, try running the above `uninstall grunt-contrib...` command again, followed by `npm cache clean`, then run `npm install` again.

**Comment by ghost** [comment]
Same result and it does not install the ones that match the 0.3.17 grunt when i does that.

**Comment by lancejpollard** [comment]
I would look in that `grunt-contrib-less/package/json` file and see what version of grunt it requires (in it's `dependencies` hash).

Also make sure that the `./node_modules/grunt/package.json` is 0.3.17.

You'll have to trace the error to that grunt-contrib-less line, I can't dig any further on it. It has something to do with versions between the different grunt/grunt-contrib modules. You can also comment out [grunt.coffee#L42-45](https://github.com/viatropos/tower/blob/fec2c17af23ac7dfb3c385d79fb8de5db89d5aea/packages/tower-generator/server/generators/tower/app/templates/grunt.coffee#L42-L45) and see if that works.

**Comment by ghost** [comment]
ok i solved the grunt-contrib prob its due to the grunt-contrib-less dependencies. I reinstall those and its ok. But when i run cake watch i still get this error
![prob5](https://f.cloud.github.com/assets/3678954/189334/09341cb4-7e6c-11e2-967c-73e968939ea8.PNG)

**Comment by lancejpollard** [comment]
Make sure it has specified the coffee-script config:

```
grunt --config ./grunt.coffee
```

The Cakefile should also be doing that, but since you're on windows, it's probably something like:

```
grunt --config grunt.coffee
# or
grunt --config .\grunt.coffee
```

I have never used windows so not sure. Once you know how to specify the path to the `./grunt.coffee` file using the windows-specific path format, then you should be good to go.

**Comment by ghost** [comment]
btw cake watch is under which module? I have try everything i could but still receive that same error

**Comment by lancejpollard** [comment]
[Cakefile#L8-11](https://github.com/viatropos/tower/blob/fec2c17af23ac7dfb3c385d79fb8de5db89d5aea/packages/tower-generator/server/generators/tower/app/templates/cake#L11)

**Comment by ghost** [comment]
This is part of my codes in Cakefile: 

``` coffeescript
require 'tower'
knox  = require('knox')
spawn = require('child_process').spawn
which = require('which').sync
path  = require('path')

spawnGrunt = (args = []) ->
  args.push('--config', path.join(process.cwd(), '.\grunt.coffee'))

  grunt   = which('grunt')
  watcher = spawn('.\node_modules\grunt\bin\grunt', args) 
  watcher.stdout.setEncoding('utf8')
  watcher.stderr.setEncoding('utf8')
  watcher.stdout.on 'data', (data) ->
    console.log data.replace(/\n$/m, '') # remove extra line
  watcher.stderr.on 'data', (data) ->
    console.log data.replace(/\n$/m, '')
```

I still get that error. I have no idea why as the `grunt --config .\grunt.coffee` works

**Comment by lancejpollard** [comment]
I'm not sure if this works:

``` coffeescript
  args.push('--config', path.join(process.cwd(), '.\grunt.coffee'))
```

That backslash `\` might be interpreted as trying to escape the `g`, as in `\g`. Try tinkering with that, such as doing `.\\grunt.coffee`. I'm not sure if windows includes the `.` in relative paths either. How does windows handle relative paths, any ideas?

**Comment by lancejpollard** [comment]
If you can get the following to work, then you are good to go:

```
grunt --config .\grunt.coffee # or however you point windows to that path
```

and in a separate window:

```
node server
```

The `cake watch` command can be accomplished by using the above `grunt --config ./grunt.coffee`.

**Comment by ghost** [comment]
http://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx#paths

I still cannot get it to work. If i am gonna use `grunt --config ./grunt.coffee`, thats all right?

Edited, Ok i got it to work using `grunt --config ./grunt.coffee` but it will not update as the server is running right?

**Comment by lancejpollard** [comment]
Yeah, that just starts the watcher to watch your files for changes. Keep that open in one terminal window.

Then in another terminal window (the main one you'll work from), run:

```
node server
```

**Comment by ghost** [comment]
![prob7](https://f.cloud.github.com/assets/3678954/189374/29b27868-7e72-11e2-9510-1eccd9a3ed2a.PNG)

When its done it just end, so is it really watching the files for changes?

**Comment by lancejpollard** [comment]
Try:

```
grunt start --config ./grunt.coffee
```

`grunt start` compiles and watches for changes, while `grunt` just compiles.

**Comment by ghost** [comment]
ok thx i solve it. Looking forward to Tower 0.5.0

**Comment by lancejpollard** [comment]
Awesome. Yes, Tower 0.5.0 won't have this issue :). Let me know if you have you have any other questions/ideas.
