### ISSUE TITLE
App.Chat wasn't found

### ISSUE THREAD

**Issue by mitchpolska** [tower-archive/tower#387]
Hi,
I have crated controller only by: tower generate controller chat.
And now, error occurs when I want to run server (or something else like cake watch).

How can I fix it ?

**Comment by btbinhtran** [comment]
What are the error messages?

Also, which version of Tower are you using?
The one from NPM Registry or the cutting edge from this repository?

**Comment by mitchpolska** [comment]
I have resolved problem by removing @scopeall from controllers. Thank you for your response.

**Comment by btbinhtran** [comment]
Good to know.

**Comment by mitchpolska** [comment]
I don't want create another issue (I think the problem is trivial). Maybe you know how to update model ? I have created model named chat but now I want to add another fields to it. How to do this ?

**Comment by btbinhtran** [comment]
This link should have all the info you need.

https://github.com/viatropos/tower/wiki/Models

Cheers!

**Comment by mitchpolska** [comment]
Doesn't work. Anyway, thank you !
