### ISSUE TITLE
Can't create new app

### ISSUE THREAD

**Issue by tycooon** [tower-archive/tower#39]
So I wanted to play around with Tower.js but when I run `tower new app` the script gets stuck on 

```
create : app/public/swfs/WebSocketMain.swf
create : app/public/swfs/WebSocketMainInsecure.swf
```

It just hangs there not doing anything and not stopping.

I'm using Mac OS X 10.7.3, node v0.6.12 (installed using homebrew), and tower version 0.3.9-11.
Any hints?

**Comment by lancejpollard** [comment]
I have seen that happen somewhat randomly…  Just tried it and it worked, but will look into this more.  If you CTRL-C quit it still will have generated the complete app app though.

**Comment by lancejpollard** [comment]
This doesn't seem to be happening anymore, closing for now.
