### ISSUE TITLE
Use Coffeecup instead of Coffeekup

### ISSUE THREAD

**Issue by pocesar** [tower-archive/tower#391]
Coffeekup hasn't been updated for over 2 years, so the dependency should be changed to  https://github.com/gradus/coffeecup instead, that is activelly maintained

And btw, how to change it easily on a new Towerjs project?

**Comment by thehydroimpulse** [comment]
Sorry, but were not updating version 0.4.x anymore (unless someone steps in). Were putting the effort towards 0.5.0 instead.

**Comment by edubkendo** [comment]
As far as I know, Tower has actually been using the "coffeecup" repo for a really long time now, it just calls it coffeekup in the documentation because that's the recognizable name. If you check the package.json, though, you;ll see it' says:

``` javascript
"coffeecup": ">= 0.3.17"
```

**Comment by pocesar** [comment]
ah ok, my bad
