### ISSUE TITLE
Custom error handling

### ISSUE THREAD

**Issue by yusugomori** [tower-archive/tower#40]
When using Rails, it is possible to custom error handling by writing codes in application_controllers.rb as follows (in 404 case):

``` ruby
class CustomNotFound < Exception; end

class ApplicationController < ActionController::Base
  protect_from_forgery

  rescue_from CustomNotFound, :with => :error_404_not_found

  def error_404_not_found(exception=nil)
    render :template => "errors/404", :status => 404, :layout => "application"
  end
end
```

Is there any ways similar to **_rescue_from**_ ?

**Comment by lancejpollard** [comment]
Not yet, this is a useful feature to have though.  Feel free to add it if you're up to it.  I will also look into adding something like this soon.

**Comment by lancejpollard** [comment]
some notes on trying to handle errors better in controllers. In short, I think you'd have to end up wrapping any async call in something like `Tower.withContext @request.domain, App.Post.all, (error, posts) => ...`, similar to ember's `Ember.get(@, 'length')`.
- https://github.com/viatropos/tower/commit/c7d6b150c163458208474133770928c289416340
- https://gist.github.com/3431201
