### ISSUE TITLE
Cannot install Tower

### ISSUE THREAD

**Issue by maximkott** [tower-archive/tower#404]
There are the latest few lines

> ws@0.4.30 install /Users/mk/local/lib/node_modules/tower/node_modules/tower-cli/node_modules/tower-server/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
  SOLINK_MODULE(target) Release/bufferutil.node: Finished
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
  SOLINK_MODULE(target) Release/validation.node: Finished
  CXX(target) Release/obj.target/fibers/src/fibers.o
  CXX(target) Release/obj.target/fibers/src/coroutine.o
  CC(target) Release/obj.target/fibers/src/libcoro/coro.o
  SOLINK_MODULE(target) Release/fibers.node
  SOLINK_MODULE(target) Release/fibers.node: Finished
Installed in `/Users/mk/local/lib/node_modules/tower/node_modules/tower-cli/node_modules/tower-console/node_modules/fibers/bin/darwin-x64-v8-3.14/fibers.node`
tower@0.5.0 /Users/mk/local/lib/node_modules/tower
├── tower-router@0.1.0 (part-async-series@0.1.0)
├── tower-validator@0.1.0 (indexof@0.0.1, tower-emitter@0.1.1)
├── tower-adapter@0.1.0 (tower-load@0.1.0, tower-emitter@0.1.1, tower-stream@0.1.0)
├── tower-resource@0.1.0 (tower-load@0.1.0, tower-text@0.1.0, part-async-series@0.1.0, tower-emitter@0.1.1, tower-attr@0.1.0-pre, tower-stream@0.1.0)
├── tower-route@0.1.0 (part-async-series@0.1.0, path-to-regexp@0.0.2, tower-emitter@0.1.1, tower-param@0.1.0)
├── tower-type@0.1.0 (part-is-array@0.0.1, tower-emitter@0.1.1)
├── tower-memory-adapter@0.1.0 (tower-uuid@0.1.0, tower-stream@0.1.0)
├── tower-query@0.1.0 (part-is-array@0.0.1, part-each-array@0.0.1, tower-program@0.1.0)
└── tower-cli@0.1.0 (commander@2.0.0, tower-cookbook@0.1.0, tower-fs@0.5.0-pre2, tower-server@0.1.0, tower-console@0.1.0)

If I run in console "tower" - I get "command not found".

**Comment by thehydroimpulse** [comment]
@maximkott Is that the full output?

Also, are you running `npm install tower -g`?

**Comment by maximkott** [comment]
@TheHydroImpulse this is the last part of the output. 
I used: npm install -g tower

**Comment by thehydroimpulse** [comment]
@maximkott The tower binary is included in the `tower-cli` package, that's why you're running into errors. Try running `npm install tower-cli -g`. We might have to put some sort of wrapper executable in this repository for simplicity.

**Comment by lancejpollard** [comment]
Alright this is fixed now. The `tower` executable is now part of the `tower/tower` repo, and I've deleted the `tower/cli` repo. Make sure you can do this after installing:

```
$ tower -v
0.5.1
```

Also, the cookbooks are setup too. You can install a component generating cookbook like this:

```
npm install tower-component-cookbook -g
```

Then you can run it anywhere like this:

```
tower create component my-component
```
