### ISSUE TITLE
Still under development?

### ISSUE THREAD

**Issue by tarun1793** [tower-archive/tower#409]
I would love to try tower.js but the statistics on github got me wondering if it is a work in progresss or just used to be?

**Comment by thehydroimpulse** [comment]
@tarun1793 Hey, the main repo doesn't change because most of the functionality has been moved in independent repos across the tower organization.

Tower isn't as much of a framework, but a collection of many independent components. I'll be working on integrating much of the platform to make it a framework, or make it easier to use all these components.

**Comment by tarun1793** [comment]
Ok. Most would be coming from a convention of a framework, so seeing such low activity on primary face of the module/organisation they may, like me, assume that the project is at a stand still.

I would say keep this issue open until we reach a point to make it a full framework. maybe for a quick job merge the other repos into this one.so that installing this module will make all other available.

**Comment by tarun1793** [comment]
And Hey!!

**Comment by thehydroimpulse** [comment]
@tarun1793 Yeah, I mean Tower still kinda **is** a framework, or that's the goal, but not in the Rails sense of the word. The framework part is still under wraps and being developed while the underlying mechanics are pretty much there. The final effort is to streamline the process, and stuff.

We like to get away from the Rails notion of a framework definition. Node is very much different from how Ruby works, in terms of community, principles, etc...

**Comment by tarun1793** [comment]
Yap, agree on that. 
Never been a ruby guy, PHP, Yii, .NET was my thing.

I will be looking at some code, will love to help if able to!

**Comment by thehydroimpulse** [comment]
@tarun1793 Awesome. Let me know if you need help. There's virtually no docs or anything, which is something on the horizon.

**Comment by tarun1793** [comment]
Your answer on SO was extremely helpful.
This might figure low in priority given the #things to be done. Will be great if you may do a fair comparison for a few major ones, like sails or geddy. 

+-----------------------+------------------------------+------------------------------------+
|                       | RailwayJS                    | Tower.js                           |
+-----------------------+------------------------------+------------------------------------+
| First commit          | Jan 2011                     | Oct 2011                           |
| Rails                 | 2.3.x                        | 3.x                                |
| Node.js               | >= 0.4.x                     | >= 0.4.x                           |
| Server                | ✓                            | ✓                                  |
| Client                |                              | ✓                                  |
| Template agnostic     | ✓                            | ✓                                  |
| Default engine        | EJS                          | CoffeeKup                          |
| Database agnostic     | ✓                            | ✓                                  |
| Default datastore     | MongoDB                      | MongoDB                            |
| Model validations     | validatesPresenceOf('email') | validates('email', presence: true) |
| Query scopes          | ✓                            | ✓                                  |
| Chainable scopes      |                              | ✓                                  |
| Param parsing         |                              | ✓                                  |
| Controllers           | ✓                            | ✓                                  |
| Resource controllers  |                              | ✓                                  |
| File naming           | users_controller.js          | usersController.coffee             |
| vm.runInCustomContext | ✓                            |                                    |
| Asset pipeline        |                              | ✓                                  |
| Asset compression     |                              | ✓                                  |
| Routing               | map.resources('posts')       | @resources 'posts'                 |
| Nested routes         | ✓                            | ✓                                  |
| Generated url helpers | ✓                            |                                    |
| Generators            | ✓                            | ✓                                  |
| Command-line api      | ✓                            | ✓                                  |
| REPL (console)        | ✓                            | ✓                                  |
| CoffeeScript console  |                              | ✓                                  |
| Asset cache method    | timestamp                    | md5 hash                           |
| Production asset path | /app.css?123123123           | /app-859c828c89288hc8918741.css    |
| Preferred Language    | JavaScript                   | CoffeeScript                       |
| CoffeeScript support  | ✓                            | ✓                                  |
| Internationalization  | ✓                            | ✓                                  |
| Heroku support        | ✓                            | ✓                                  |
| String case           | snake_case                   | camelCase                          |
| Form builder          | ✓                            | ✓                                  |
| Semantic form builder |                              | ✓                                  |
| Table builer          |                              | ✓                                  |
| File watcher API      |                              | ✓                                  |
| Live-reload assets    |                              | ✓                                  |
| Test suite            |                              | ✓                                  |
| Generators for tests  |                              | ✓                                  |
| Twitter Bootstrap     | ✓                            | ✓                                  |
| HTML5 Boilerplate     |                              | ✓                                  |
+-----------------------+------------------------------+------------------------------------+

**Comment by tarun1793** [comment]
This table could happily reside on the readme as well

**Comment by tarun1793** [comment]
bump.

**Comment by thehydroimpulse** [comment]
@tarun1793 Oops, forgot to reply. fyi @viatropos posted that answer on SO. I should also note that the comparison was for earlier versions of Tower and Railwayjs (I think they changed names).

Lance and myself and decided to concentrate efforts on small portions of Tower at a time, and start branding it as an experiment for modular apps.
