### ISSUE TITLE
node server raises error

### ISSUE THREAD

**Issue by fabnoe** [tower-archive/tower#41]
node server results in a big error message. please help

mac01:demo johndoe$ node server

   info  - socket.io started
[Tue, 13 Mar 2012 22:27:16 GMT] INFO Tower development server listening on port 3000
[Error: Target script does not exist: node_modules/design.io/bin/design.io]

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: failed to connect to [127.0.0.1:27017]
    at [object Object].<anonymous> (/Users/johndoe/Development/Workspaces/2012/nodejs/demo/node_modules/mongodb/lib/mongodb/connection/server.js:405:73)
    at [object Object].emit (events.js:88:20)
    at [object Object].<anonymous> (/Users/johndoe/Development/Workspaces/2012/nodejs/demo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:96:15)
    at [object Object].emit (events.js:70:17)
    at Socket.<anonymous> (/Users/johndoe/Development/Workspaces/2012/nodejs/demo/node_modules/mongodb/lib/mongodb/connection/connection.js:385:10)
    at Socket.emit (events.js:67:17)
    at Array.0 (net.js:319:25)
    at EventEmitter._tickCallback (node.js:192:40)

**Comment by lancejpollard** [comment]
This is because mongodb probably isn't running on your computer.  Make sure you have it installed and started (use homebrew to install if this is new):

```
brew install mongodb
mongod start
```

Let me know how that goes.

**Comment by fabnoe** [comment]
Oh, yeah. You are right. But now i get this error:

node server

   info  - socket.io started
[Wed, 14 Mar 2012 07:33:28 GMT] INFO Tower development server listening on port 3000

info:  Name: design.io-watcher::demo hook::listening                          Type: hook            Data: 5000
info:  Name: design.io-watcher::demo hook::started                            Type: hook            Data: 5000
info:  Name: design.io-watcher::demo hook::ready                              Type: hook            Data: {"name":"design.io-watcher::demo","type":"hook","p ... 
info:  Name: design.io-watcher::demo ready                                    Type: hook            Data: {"name":"design.io-watcher::demo","type":"hook","p ... 
[Wed, 14 Mar 2012 07:33:46 GMT] ERROR /Users/johndoe/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
[Wed, 14 Mar 2012 07:33:46 GMT] ERROR :
[Wed, 14 Mar 2012 07:33:46 GMT] ERROR no such file to load -- rb-fsevent (LoadError)
    from /Users/johndoe/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
    from /Users/johndoe/Development/Workspaces/2012/nodejs/demo/node_modules/design.io/lib/design.io/listener/mac.rb:2:in `<main>'
[Wed, 14 Mar 2012 07:33:46 GMT] ERROR /Users/johndoe/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
[Wed, 14 Mar 2012 07:33:46 GMT] ERROR :
[Wed, 14 Mar 2012 07:33:46 GMT] ERROR no such file to load -- rb-fsevent
[Wed, 14 Mar 2012 07:33:46 GMT] ERROR (

**Comment by fabnoe** [comment]
Ok it's running. I had to install a ruby gem:
gem install rb-fsevent

**Comment by maedi** [comment]
Could this be put in a getting started guide?
