### ISSUE TITLE
towerjs.org vs tower.github.io?

### ISSUE THREAD

**Issue by andreyvit** [tower-archive/tower#410]
Hey, is towerjs.org an older site of yours? It seems to be describing a very different framework from what Tower seems to be right now. (And, incidentally, I really liked the framework described there. :-)

**Comment by thehydroimpulse** [comment]
@andreyvit Hey,

towerjs.org should be redirecting to tower.github.io. We did have a towerjs.org our previous site for an older version of Tower.

I'll be getting some stuff in the README that explains what the current Tower is all about.

**Comment by tarun1793** [comment]
It certainly doesn't redirect.

**Comment by thehydroimpulse** [comment]
@tarun1793 mmmm, that's a bit strange. It works for me, but I'll see what's going on.
