### ISSUE TITLE
UI Bindings?

### ISSUE THREAD

**Issue by tarun1793** [tower-archive/tower#411]
Does tower.js client side part supports UI binding?

**Comment by lancejpollard** [comment]
yep, check out https://github.com/tower/template. the /test folder has the basic examples of how it works

**Comment by tarun1793** [comment]
Thanks.
I was under an impression that coffeeScript is present at the core of Tower, yet everywhere examples are in plain JS. 
Any links to that documentations? or is  it a work in progress?

I have used Spine.js before and they way they embrace the Class functionality is great

**Comment by thehydroimpulse** [comment]
@tarun1793 the previous version was written in coffee script. The current version is in JavaScript.

**Comment by tarun1793** [comment]
Why? :(

**Comment by thehydroimpulse** [comment]
@tarun1793 Didn't get a notification for that last message. Coffee-script added a barrier to entry and to participate. It also added unnecessary complexity.
