### ISSUE TITLE
Server-side rendering?

### ISSUE THREAD

**Issue by dts** [tower-archive/tower#413]
Based on the docs on http://tower.github.io/guide#template, the template engine should work on the server side, but there appears to be no evidence that this is the case, looking at https://github.com/tower/template/blob/master/index.js , there appears to be no server-side support.  Am I correct, or is there some magic somewhere that I can't find?

**Comment by thehydroimpulse** [comment]
@dts Our templating engine supports both the client-side and server-side. The client-side portion is a little bit messy, and we have old repos laying around.

The server-side is rendered through [server-dom](https://github.com/tower/server-dom) and the actual template library is under the `new` branch (https://github.com/tower/server-template/tree/new). I'll merge it in to the master branch and update NPM if you'd like. 

The client-side will be much cleaner, almost exactly like the server-side. So server and client compatible.

I might just make the template repo server & client to simplify everything.

**Comment by dts** [comment]
If the functionality is ready, I'd say merge and push out to NPM.  How would you describe the "production readiness" of tower?  How many people are using it?  Are there any demos for the new system?

**Comment by thehydroimpulse** [comment]
@dts It's not "production ready", I wouldn't say. Right now, I wouldn't classify Tower as anything close to a framework. Right now, it's a bunch of small modules that can be used independently, or together. I'm currently putting my effort into the view system (server & client). The templating system is pretty much complete, the view system is just a higher abstraction.

The main effort in getting the templates to work seamlessly client and server is a pipeline of sort. Where we package up all the templates to be used on the client-side. That's a future goal, and pretty easy to accomplish.

I'm currently using many of the Tower modules in production for @titananalytics. @viatropos and I are getting the ideology of Tower together, and the process of building apps with our modules.
