### ISSUE TITLE
testing frameworks

### ISSUE THREAD

**Issue by s0nspark** [tower-archive/tower#43]
Is there an easy (i.e. documented) way to swap out testing frameworks with Tower.js? I'm 92.3% sure I would like to use mocha and am not really sure how to proceed...

**Comment by lancejpollard** [comment]
Tower doesn't quite have the following functionality yet, but it's on the list:

``` coffeescript
@config.generators (g) ->
  g.orm             "mongodb"
  g.templateEngine  "coffeekup"
  g.testFramework   "mocha"
```

Tower will also be defaulting to mocha, it's just way better :).  Will let you know when this is added.

**Comment by s0nspark** [comment]
Awesome ... sounds great!
