### ISSUE TITLE
cannot call method 'match' of undefined

### ISSUE THREAD

**Issue by webdesserts** [tower-archive/tower#5]
I run into this issue when I try to run.

```
   info  - socket.io started

node.js:134
        throw e; // process.nextTick error, or 'error' event on first tick
        ^
TypeError: Cannot call method 'match' of undefined
    at Object.run (/usr/lib/node_modules/tower/lib/tower/command.js:6:19)
    at Object.<anonymous> (/usr/lib/node_modules/tower/bin/tower:3:33)
    at Module._compile (module.js:402:26)
    at Object..js (module.js:408:10)
    at Module.load (module.js:334:31)
    at Function._load (module.js:293:12)
    at Array.<anonymous> (module.js:421:10)
    at EventEmitter._tickCallback (node.js:126:26)
```

I have a feeling this is either an issue with my instillation or my version of node isn't compatible with tower. Any Ideas on what the issue might be?

**Comment by webdesserts** [comment]
**Node** v0.4.9
**NPM** 1.0.106

I didn't realize my Node version was so low, Just freshly installed not to long ago. Gunna try upgrading.

**UPDATE**

Ok upgrade Node to v0.6.11 but it's still not working.

**Comment by lancejpollard** [comment]
It should run on any node version 0.4.x and up (you can deploy a Tower app to Heroku, which uses node v0.4.7 as of this post).

What command did you run?

I get the same error if you run this command:

```
tower
```

That line, [/usr/lib/node_modules/tower/lib/tower/command.js: 6:19](https://github.com/viatropos/tower/blob/c52a3d706d1b6852c2f54fd707df0326083ec2f3/lib/tower/command.js#L6) tries to parse the 3rd item in the `process.argv` array, which looks like this:

``` javascript
// $ tower
[ 'node', '/usr/local/bin/tower' ]
// $ tower new app
[ 'node', '/usr/local/bin/tower', 'new', 'app' ]
```

I'm going to be cleaning up this api soon, but you should be able to generate a new app.  To start the server just run `node server`.

Let me know if that helps.

**Comment by webdesserts** [comment]
Ahh, you're right. I'm pretty sure I was trying to use `tower` and/or `tower help` just as a confirmation that it worked . Creating a new app works fine. Guess I shouldn't have let the first error stop me. Thanks for the help!

**Comment by lancejpollard** [comment]
Cool, good to hear.

**Comment by lancejpollard** [comment]
Fixed

```
$ tower
  Usage: 
    tower [command] [options]

  Commands:
    new <app-name>                    generate a new Tower application in folder "app-name"
    console                           command line prompt to your application
    generate <generator>              generate project files (models, views, controllers, scaffolds, etc.)

  Options:
    -h, --help                        output usage information
    -v, --version                     output version number

$ tower new
  Usage:
    tower new <app-name> [options]

  Options:
    -T, --title <title>               project title (as opposed to its file name)
    -D, --description <description>   project tagline (one sentence)
    -K, --keywords <keywords>         project keywords (e.g. "node.js, file uploading, s3")
    -n, --namespace <namespace>       global namespace for your app (defaults to YourProjectName)
    -h, --help                        output usage information
    -v, --version                     output version number
    --skip-procfile                   skip creating a Procfile (for deploying to Heroku)
    --skip-git                        Skip Git ignores and keeps

```
