### ISSUE TITLE
everyauth example?

### ISSUE THREAD

**Issue by fabnoe** [tower-archive/tower#50]
Does anyone got an example of using towerjs with everyauth https://github.com/bnoguchi/everyauth ?

I just found this – But the documentation is pretty poor.
https://github.com/viatropos/tower/wiki/authentication

**Comment by lancejpollard** [comment]
No complete example yet, but here's a snippet of code from one of our internal projects that used everyauth.
- https://github.com/viatropos/tower/issues/18#issuecomment-4278945

Also, just a note.  Any documentation in the github wikis (https://github.com/viatropos/tower/wiki/ …) is not _complete_.  Anything that's roughly complete will be mirrored on the main site http://towerjs.org.

**Comment by lumin3000** [comment]
I am using mongoose-auth(from everyauth too) with tower, so far so good....
what is your problem so?

**Comment by yusugomori** [comment]
I wrote sample codes on gist.
Chek them on

config/application.coffee
https://gist.github.com/2318167

config/initializers/authentication.coffee
https://gist.github.com/2318237

app/models/user.coffee
https://gist.github.com/2318251

I hope it will help.
Comments are written in Japanese, so feel free to ask me questions.

**Comment by kristianmandrup** [comment]
Would be really nice to fill in the wiki with some example code on setting up authentication. I'd also like there to be a recipe for making Tower extensions (plugins) for example for various authentication solutions.

**Comment by edubkendo** [comment]
I've taken the liberty of providing rough translations of the Japanese code comments. This was probably unnecessary as the code seems quite clear, but thought it might possibly be helpful to someone. I can't be sure my translations are accurate, so  please ask yusugomori any questions. Hope this wasn't out of line in any way.

**Comment by svasva** [comment]
I have added an everyauth example here: https://github.com/viatropos/tower/wiki/Everyauth-integration-example
If anyone can add something to this one, that would be nice.
