### ISSUE TITLE
Adding url helpers to views (e.g. `newPostPath`)

### ISSUE THREAD

**Issue by lancejpollard** [tower-archive/tower#54]
[moved from email from @kristianmandrup]

Hi Lance,

I have been a Rails programmer for the past 3 years, but I feel the time has come to switch to using Node.js, especially with frameworks such as Tower coming on to the scene which makes it much easier for us Rails developers to adapt to use the underlying Node.js and Express frameworks.

However, even after reading through the documentation, I wasn't sure exactly how to get started. Are there any good example apps out there to look at and get a feel for it.

I have one minor question on how to use Tower:

I would like to use the route paths in my view for generating links, similar to how I would do it in Rails

``` haml
= link_to "Sign in", new_user_session_path
```

However examining the Tower code I find

``` coffeescript
Tower.View.ComponentHelper =
  # ...    
  linkTo: (title, path, options = {}) ->
    a _.extend(options, href: path, title: title), title.toString()
```

How can I reference the path using the routes?

``` coffeescript
Tower.Route.draw ->
  @match "/login", "sessions#new", via: "get", as: "login"
```

I would like to avoid this hardcoding

``` haml
= link_to "Sign in", "/user/signin"
```

All I see is fx

``` coffeescript
urlFor(post)
Tower.urlFor(App.Post, action: "new")
urlFor controller: "posts", action: "index"
urlFor @user
urlFor User
urlFor "admin", @user
```

Hmm…

``` javascript

Tower.urlFor = function() {
  var args, item, last, options, result, route, _i, _len;
  args = Tower.Support.Array.args(​arguments);
  if (!args[0]) return null;
  if (args[0] instanceof Tower.Model || (typeof args[0]).match(/(string|​function)/)) {
    last = args[args.length - 1];
    if (last instanceof Tower.Model || (typeof last).match(/(string|function)​/)) {
      options = {};
    } else {
      options = args.pop();
    }
  }
  options || (options = args.pop());
  result = "";
  if (options.controller && options.action) {
    route = Tower.Route.find({
      name: Tower.Support.String.camelize(​options.controller).replace(/(​Controller)?$/, "Controller"),
      action: options.action
    });
    if (route) {
      result = "/" + Tower.Support.String.​parameterize(options.​controller);
    }
  } else {
    for (_i = 0, _len = args.length; _i < _len; _i++) {
      item = args[_i];
      result += "/";
      if (typeof item === "string") {
        result += item;
      } else if (item instanceof Tower.Model) {
        result += item.toPath();
      } else if (typeof item === "function") {
        result += item.toParam();
      }
    }
  }
  result += (function() {
    switch (options.action) {
      case "new":
        return "/new";
      case "edit":
        return "/edit";
      default:
        return "";
    }
  })();
  if (!options.hasOwnProperty("​onlyPath")) options.onlyPath = true;
  options.path = result;
  return Tower.Support.String.urlFor(​options);
};
```

It doesn't seem like there is any logic to support this Route Registry lookup functionality yet? What happens to the routes when they are registered with an alias? I wouldn't mind implementing this logic myself if you can just give me some pointers/advice.

Thanks!

**Comment by lancejpollard** [comment]
[Moved from email response from @viatropos]

You're right, the documentation needs to make it clearer how to get started.  The framework is still pretty young, but that's on the todo list.  For the most part though, you should be able to assume anything in Rails and get the rough equivalent in CoffeeScript.

About your `urlFor` question…  2 things.

First, the implementation isn't complete, so it doesn't look through the routes and everything like you pointed out, I just hacked together something quick to get started.  I'd love for you to contribute a more robust implementation, that'd be awesome!  Otherwise, it's on my list but I may not get around to it for a few weeks.  https://github.com/viatropos/​tower/wiki/todo

Second, there are a few things in Rails that I wasn't a big fan of, and one of them was the 100's of dynamically generated helper methods (url helpers, dynamic finders like find_by_x, etc.).  I prefer using the low-level API directly for 3 reasons: 1) there's fewer methods in memory, which means faster startup since javascript doesn't have method_missing, and 2) even though it may take one or two extra parameters, it's less mental overhead, and it gives you more power.  I ended up pretty much only using `polymorphic_url_for` and `url_for` in Rails.

So, I would rather not add this feature, but still have Tower's `urlFor` be just as robust as Rails'.  But, if it turns out it's only a few lines of code to generate all of those methods and it doesn't really impact startup performance at all, I'm not opposed to adding it.  At the least, it could be a separate plugin.

For now though, `Tower.urlFor` works for simple cases:

``` coffeescript
urlFor(App.Post) # "/posts"
urlFor("admin", App.Post) # "/admin/posts"
urlFor(new App.Post(id: 10), action: "edit") # "/posts/10/edit"
```

Hope that helps, let me know if you have any more questions.

**Comment by lancejpollard** [comment]
[Moved from email response from @kristianmandrup]

Another suggestion would be for you to create a Tower-user and Tower-dev Google groups or similar for such discussions take place.

You can then select posts to include on the TODO or issues list.

I would love to help out in improving/extending the framework.

I agree that Tower.js shouldn't overuse auto-generation of methods such as the `_path` methods in Rails. Good point. Instead I thought it could use some string/hash conventions. For my example:

``` coffeescript
urlFor 'Login', path: 'login'
```

OR?

``` coffeescript
urlFor 'Login', 'login_path'
```

Here, a quick regexp (or just substring last 5 chars) would on matching with `_path` resolve the prefix to a registered path/route.

OR even

``` coffeescript
pathFor 'Login, 'login'
```

AND default 

``` coffeescript
pathFor 'Login'
```

Could resolve to the path name (route alias) as the text underscored and lowercased?

What do you think? How could I make a plugin for this?

Thanks again!

Kris

PS: If I get started I will contribute a getting started screencast if you like ;)

**Comment by lancejpollard** [comment]
Yeah Tower should include this sort of named route functionality without having generated helper methods.

So for something like this route:

``` coffeescript
Tower.Route.draw ->
  @match "/login", as: "login"
```

How about doing one of these:

``` coffeescript
urlFor(route: "login") # I'm liking this one
urlFor(name: "login")
```

I'd rather it not take an arbitrary string and check for a named route, such as this:

``` coffeescript
urlFor("login")
urlFor("login_path")
urlFor("loginPath")
```

The reasons are these… First, by using a string-based convention, you'd then have to run every `urlFor` call through the parser or whatever which isn't ideal.  Also, if you for some reason wanted to have a url be `http://localhost:3000/login_path`, then the convention of `_path` would require an extra workaround to override default behavior, which adds more code to the urlFor method and some mental overhead.

You should be able to do what you're describing using a parameter like `route: 'login'`, does that work?

Also, that'd be awesome to have a getting started screencast, let me know if you make one!

A guy named Nate Kidwell just created a Google Group for this kind of stuff, waiting for his reply.  We can take this kind of discussion there next time, it was just so rich I wanted to take it out of email to share.

**Comment by ludicast** [comment]
Good thread (off topic - I've used Kristian's mongoid-geo code plenty of times).

Following his above suggestion for a dev group, I just added a towerjs-dev google group so now you have
https://groups.google.com/group/towerjs-dev
and
https://groups.google.com/group/towerjs

**Comment by kristianmandrup** [comment]
urlFor(route: "login") # I'm liking this one

+1

Yeah, I'm "all in" with regards to Mongo ;) A major reason why I like the Tower framework :) So natural with JSON from client to server to DB, JSON which is by nature document structures. 

So @viatropos, can you do a quick patch to implement this "route-alias lookup" feature for _urlFor_ this weekend?

**Comment by lancejpollard** [comment]
Yeah I'm down, I'll get that `urlFor` route alias feature in this weekend.

**Comment by lancejpollard** [comment]
Sorry guys, wasn't able to get to it this weekend.  If anyone wants to go after it that'd be awesome, otherwise I'll do my best to get this in there this week.

**Comment by kristianmandrup** [comment]
Hi there, are you still planning to add that feature or too busy? I wouldn't know where to start...
Thanks! Have a nice weekend!

**Comment by lancejpollard** [comment]
Still planning on this! Have had to work on a bunch of model stuff for Tower all week for a project... won't be able to get to this for a little while. If you wanted to try it out, fork/clone the project and mess around with these two files:
- https://github.com/viatropos/tower/blob/master/src/tower/support/string.coffee#L185
- https://github.com/viatropos/tower/blob/master/src/tower/http/route/dsl.coffee

Let me know if you need anything to get started.  I'll definitely get to this at some point in the near future, just don't know exactly when.

Thanks. Have a great weekend.

**Comment by kristianmandrup** [comment]
_extractOptions:
 name            = @_extractName(options)
_extractName: (options) ->
    options.as || options.name

So name should already be set to the :as alias if defined as part of the route (DSL).

But where are the Routes registered? I assume it is some kind of Array of hashes?
In Tower.Support.String.urlFor I simply need to make a lookup in this registry. Would be nice if it was a hash, with the keys= the name of the route for fast lookup.
