### ISSUE TITLE
the paginate function with mongodb is not working

### ISSUE THREAD

**Issue by lumin3000** [tower-archive/tower#59]
I think the problem is here: "node-mongodb-native" is using "skip" option to do the paginate not "offset"

So I did a little fix here, but i dont think it is a perfect solution

``` javascript

Tower.Store.MongoDB.Serialization.serializeOptions = function(options) {
    if (options == null) options = {};
    if (typeof(options.offset)!='undefined')options.skip = options.offset
    return options;
  }
Tower.Store.MongoDB.include(Tower.Store.MongoDB.Serialization);
```

sorry I stil not well with pull requests...

**Comment by lancejpollard** [comment]
No problem, adding this to the code, have a few more things to do before it's pushed.  Thanks for posting the solution!
