### ISSUE TITLE
error using jade includes

### ISSUE THREAD

**Issue by ludicast** [tower-archive/tower#61]
A "filename" needs to be set in the options passed into jade if you are going to use partials.  Otherwise you get the following error:

Error: the "filename" option is required to use includes at Object.parseInclude (jade/lib/parser.js:458:13) 

A quick fix for me was to add within _renderLayout (before _renderString is called in tower/view/rendering):

options.locals.filename = __dirname + "/../../../../../app/views/layouts/" + options.layout;

That's obvously ugly :) but I'm not too familar with tower's source or jade (my first time trying jade actually).

**Comment by lancejpollard** [comment]
This should be a quick fix, will get to this soon.  It most likely will be a fix to [mint.js](https://github.com/viatropos/mint.js/blob/master/src/mint.coffee#L74).

**Comment by lancejpollard** [comment]
This is working for me, are you using the latest version of jade?  Try installing the latest version of tower and try again.

**Comment by j-mcnally** [comment]
I am having this same issue again, i just installed tower today and get this when using

include shared/nav
