### ISSUE TITLE
The client side

### ISSUE THREAD

**Issue by jede** [tower-archive/tower#63]
Hi!

Tower.js seams really promising! However I can't really understand how I'm supposed to get access to and use my models on the client side?

Is the prefered way to try to serialize them into JSON and then load them on the client side, like described in the question regarding using tower only in the frontend? If so, how would this look? I can't seam to find an example of this in the documentation.

Thanks!

**Comment by lancejpollard** [comment]
Yeah, need to write more docs on the client stuff!  But if you generate models, it will add them to `config/assets.coffee` and they'll be available in the browser.

The way I'm currently bootstrapping data to the client is this:

``` coffeescript
# app/controllers/applicationController.coffee
class App.ApplicationController extends Tower.Controller
  # bootstrapping example
  index: ->
    App.User.all (error, users) =>
      App.Post.all (error, posts) =>
        @render "index", locals: data: {users, posts}
```

``` coffeescript
# app/client/config/application.coffee
class App extends Tower.Application
  # json data
  bootstrap: (data) ->
    App.User.load(data.users) if data.users
    App.Post.load(data.posts) if data.posts
```

Then in `app/views/layouts/application.coffee`:

``` coffeescript
# ...
script "App.bootstrap(#{JSON.stringify(@data)})"
# ...
```

Going to clean this up soon.  But with that you can use your models in the client (and client models don't need callbacks, but they work both ways):

``` coffeescript
# e.g. webkit console
App.User.all()
#=> [>User, >User]
```

**Comment by jede** [comment]
Thanks! Really powerful stuff! Would probably be quite easy to make some helpers for this. Got it working with some modifications:

``` coffeescript
# app/controllers/applicationController.coffee
        #...
        @render "index", locals: data: {users: users, posts: posts}
```

``` coffeescript
# app/views/layouts/application.coffee
script "$(function(){ App.bootstrap(#{JSON.stringify(@data)}) })"
```

``` coffeescript
# app/client/config/application.coffee
class App extends Tower.Application
  # json data
  bootstrap: (data) ->
    @User.load(data.users) if data.users
    @Post.load(data.posts) if data.posts
```

**Comment by lancejpollard** [comment]
I've added this functionality to the generator, so when you generate a model it will add it to these bootstrap methods.
