### ISSUE TITLE
Tower.Dispatch.Url missing: Uncaught TypeError: Cannot read property 'Url' of undefined 

### ISSUE THREAD

**Issue by sebastianhoitz** [tower-archive/tower#65]
When I open a tower page and execute App.run() I get the error

```
Uncaught TypeError: Cannot read property 'Url' of undefined 
```

every time. For some reason, the class Tower.Dispatch.Url does not exist.

The line mentioned is:

```
    this.History.Adapter.bind(global, "statechange", function() {
      var location, request, response, state;
      state = History.getState();
      location = new Tower.Dispatch.Url(state.url);
      request = new Tower.Dispatch.Request({
        url: state.url,
        location: location,
        params: _.extend({
          title: state.title
        }, state.data || {})
      });
```

in Application.prototype.listen

**Comment by lancejpollard** [comment]
Yeah that's old code, I have to update that.  Try replacing `Dispatch` with `HTTP`, the new namespace.

**Comment by lancejpollard** [comment]
I've updated the client library to point to `HTTP`, you can get that here:

https://raw.github.com/viatropos/tower/master/dist/tower.js
