### ISSUE TITLE
@on "click" events not working anymore

### ISSUE THREAD

**Issue by sebastianhoitz** [tower-archive/tower#66]
They always get resolved to the default "clickHandler" method in Tower.Controller.Elements which simply sets an empty click handler.

**Comment by lancejpollard** [comment]
Thanks for posting, still working on the client side of things.  You can override the click handler (and set global defaults) like this:

``` coffeescript
class App.ApplicationController extends Tower.Controller
  # eventHandler == name + "Handler"
  # dispatcher is set to the window by default.
  @clickHandler: (name, handler, options) ->
    $(@dispatcher).on name, (event) =>
```

More on this soon.

**Comment by lancejpollard** [comment]
Updated the client library, works now.

https://raw.github.com/viatropos/tower/master/dist/tower.js
