### ISSUE TITLE
feature request: Model @fields macro

### ISSUE THREAD

**Issue by kristianmandrup** [tower-archive/tower#68]
Would be nice (and DRY) to have a `@fields` macro that would allow me to define attributes as:

``` coffeescript
class App.User extends Tower.Model
  @fields "firstName", "middleName", "lastName", :type "String"
```

or since String is likely the default type:

``` coffeescript
class App.User extends Tower.Model
  @fields "firstName", "middleName", "lastName"
```

**Comment by lancejpollard** [comment]
Will consider, there's also this case:

``` coffeescript
class App.User extends Tower.Model
  @fields firstName: "String"
    middleName:      "String"
    lastName:        "String"
    likeCount:       type: "Integer", default: 0
```

Ideally it would be able to handle them all.

**Comment by kristianmandrup** [comment]
I will play around with that ;) It's a good little mini feature in order to get started contributing.

**Comment by kristianmandrup** [comment]
``` coffeescript

fields: (names..., options) ->
  for name of names
    @field name, options
  @_fields   ||= {}


set_fields: (attributes) ->
  for name, options of attributes
    @field name, options
```

in the test_app

``` coffeescript
class App.Address extends Tower.Model
  @field "coordinates", type: "Geo"
  @field "street"
  @field "city"
  @fields "state", "zip", type: 'String'
  @fields "other", "house"
  @set_fields my: "String", your: "Integer"
```

Compiling manually and inserting

```
Tower.Model.Attributes = {
  ClassMethods: {
    fields: function() {
      var name, names, options, _i;
      names = 2 <= arguments.length ? __slice.call(arguments, 0, _i = arguments.length - 1) : (_i = 0, []), options = arguments[_i++];
      for (name in names) {
        this.field(name, options);
      }
      return this._fields || (this._fields = {});
    },
    set_fields: function(attributes) {
      var name, options, _results;
      _results = [];
      for (name in attributes) {
        options = attributes[name];
        _results.push(this.field(name, options));
      }
      return _results;
    }
```

$ npm test
✔ 373 tests complete (6533ms)

Not sure how to merge the fields and set_fields method to handle all cases...

**Comment by lancejpollard** [comment]
Nice!  I was messing around with that a little too:

https://github.com/viatropos/tower/blob/development/src/tower/model/attributes.coffee#L24

Made me think though, a reason why we may want to leave it out, even though it may decrease the amount of code you write, is that it makes it more complicated to read.  A big goal is to make it so if _anyone_ see's the code, no matter if they're a coder or not, they will understand (or as close as possible to understanding).

If we introduced these 3 different ways of writing fields, consider what this might look like:

``` coffeescript
# Define one at a time
class App.User extends Tower.Model
  @field 'firstName'
  @field 'middleName'
  @field 'lastName'
  @field 'email'
  @field 'likeCount',     type: 'Integer'
  @field 'activatedAt':   type: 'Date'
  @field 'active',        type: 'Boolean', default: false
  @field 'admin',         type: 'Boolean', default: false
```

``` coffeescript
# Define multiple at a time
class App.User extends Tower.Model
  @fields 'firstName', 'middleName', 'lastName', 'email'
  @fields 'likeCount',        type: 'Integer'
  @fields 'activatedAt',      type: 'Date'
  @fields 'active', 'admin',  type: 'Boolean', default: false
```

``` coffeescript
# Define as hash
class App.User extends Tower.Model
  @fields firstName: 'String'
    middleName:       'String'
    lastName:         'String'
    email:            'String'
    likeCount:        'Integer'
    activatedAt:      'Date'
    active:           type: 'Boolean', default: false
    admin:            type: 'Boolean', default: false
```

``` coffeescript
# Define using all 3!
class App.User extends Tower.Model
  @field 'id', type: 'Id'
  @fields 'firstName', 'middleName', 'lastName', 'email'
  @fields likeCount: 'Integer', activatedAt: 'Date'
  @fields 'active', 'admin', type: 'Boolean', default: false
```

The last case is very hard to quickly grasp functionality.  But, that's what would probably end up happening with all these choices.  The first, while being a little more verbose, makes it so all apps will be easy to read.

As a side note, I think sometimes it's okay to make the api robust, particularly when you're writing it a lot.  This is the case with the finder api:

``` coffeescript
App.User.find 1
App.User.find 1, 2
App.User.find [1, 2]
App.User.find existingUser # .get('id')
App.User.find existingUser, 2
App.User.find [existingUser, 2]
```

The reason having multiple ways of writing this api is okay it seems is because it might take arguments in many different ways (from `@params` in the controller, or writing it by hand in the web console, etc.).  In that case, whatever makes it both easy to write and robust.

Just some thoughts.

**Comment by kristianmandrup** [comment]
I made it work like this in js:

``` javascript
    fields: function() {
      var name, names, options, _i, attributes, first_arg;

      names = 2 <= arguments.length ? __slice.call(arguments, 0, _i = arguments.length - 1) : (_i = 0, []), options = arguments[_i++];
      first_arg = _.first(names) || names;

      if (_.isEmpty(first_arg) || _.isString(first_arg)) {
        // handle as array of strings        
        for (name in names) {
          this.field(name, options);
        }
      } else {
        attributes = arguments;
        // handle as hash of field_key, type
        for (name in attributes) {
          this.field(name, attributes[name]);
        }                
      }
      return this._fields || (this._fields = {});
    }
```

I don't mind that developers have the option to write in more concise and DRY. You can never guard against ugly coding styles. 

I would think most developers would do sth like this:

``` coffeescript
class App.User extends Tower.Model
  @field 'id', type: 'Id'
  @field likeCount: 'Integer'

  # strings
  @fields 'firstName', 'middleName', 'lastName', 'email'

  # booleans
  @fields 'active', 'admin', type: 'Boolean', default: false

  # dates
  @fields 'activatedAt', 'createdAt', 'startDate', 'endDate', type: 'Date'
```

The old alternative

``` coffeescript
class App.User extends Tower.Model
  @field 'id', type: 'Id'
  @field likeCount: 'Integer'

  # strings
  @field 'firstName'
  @field 'middleName'
  @field 'lastName'
  @field 'email'

  # booleans
  @field 'active', type: 'Boolean', default: false
  @field 'admin', type: 'Boolean', default: false

  # dates
  @field 'activatedAt', type: 'Date'
  @field 'createdAt', type: 'Date'
  @field 'startDate', type: 'Date'
  @field 'endDate', type: 'Date'
```

Readable but a bit long and bloated IMO. At least now there is the option to write it shorter and more DRY. All power can be misused of course ;)

**Comment by kristianmandrup** [comment]
Another variant could be this:

``` coffeescript
class App.User extends Tower.Model
  @id 'id'
  @integers 'likeCount'
  @strings 'firstName', 'middleName', 'lastName', 'email'
  @booleans 'active', 'admin', default: false
  @dates 'activatedAt', 'createdAt', 'startDate', 'endDate'
```

For the common built-in types. For other types use the field/fields or for custom types even have some hook to allow them to define their own smart type macro? Just some crazy ideas...

**Comment by kristianmandrup** [comment]
My attempt at a #strings macro

``` javascript
    strings: function(args) {
      var names, options, _i;
      names = 2 <= arguments.length ? __slice.call(arguments, 0, _i = arguments.length - 1) : (_i = 0, []), options = arguments[_i++];
      if (!options || _.isString(options))
        options = {} 
      $.extend(options, {type: 'String'});
      fields(names, options)
    },
```

The #extend from jQuery should be able to merge objects, but I get:

ReferenceError: $ is not defined
      at Function.strings (/Users/kmandrup/private/repos/tower/lib/tower/model/attributes.js:14:7)

**Comment by kristianmandrup** [comment]
I would actually like to make this available as an example of a Tower extension (plugin). 
Would be nice if you could help me do that and it would serve as a nice tutorial for Tower "plugin development" as well.
I think you are correct, that it shouldn't be part of Tower core.
Cheers and Happy Easter!

**Comment by kristianmandrup** [comment]
I have now tried to create such a Tower plugin as a Node.js module.

Please see it here and let me know what you think. I'm not yet sure how to write the tests and how to test it :P

https://github.com/kristianmandrup/tower_fields

When I get this working I will move on and try to make a plugin for Passport authentication.

**Comment by lancejpollard** [comment]
Looks pretty cool! Gotta get that screencast on how to create Tower extensions now...  Closing this issue.
