### ISSUE TITLE
pluralizer/singulizer function missing 'ss'=>'sses' case

### ISSUE THREAD

**Issue by jamespeerless** [tower-archive/tower#69]
For example the word Business => Businesses => Business is not handed properly.

**Comment by lancejpollard** [comment]
If you know how to do this I'd love your help.  I'm putting this "inflection" code off for a while, until the important stuff in the [roadmap](http://github.com/viatropos/tower/wiki/roadmap) is complete.

**Comment by jamespeerless** [comment]
I can patch this up, makes sense to put it off.  For now I just avoided using a name that ended in ss =)

**Comment by lancejpollard** [comment]
Fixed, now using a better inflection library.

https://github.com/viatropos/tower/commit/e52491d2ab32c74c4b63764dd3cfcc733ec75f0a#L5R188

**Comment by contentfree** [comment]
Shouldn't Tower.Support.String use these? It appears to have it's own, non-`_` methods for inflection and are used in important places (like Relations).
