### ISSUE TITLE
Default scaffold not working?

### ISSUE THREAD

**Issue by jameswyse** [tower-archive/tower#72]
I set up a pretty basic scaffold from the example in the documentation:

```
tower new my-app --stylesheets styl --views jade --database mongodb
cd my-app
sudo npm install
tower generate scaffold Post title:string body:text belongsTo:user
tower generate scaffold User email:string firstName:string lastName:string hasMany:posts
node server.js
```

Everything seemed to work until I add either a user or post.

When I add a user, the posts section renders the 'users' view instead of the 'posts' view. The same happens if I add a post first, the users section will render the posts view.

**Comment by jameswyse** [comment]
Ah I see this seems to be the same issue reported here: #30
Sorry for the duplicate!

**Comment by lancejpollard** [comment]
Working on this one today, thanks for posting!

As a side-note, those options `--views jade --database mongodb` don't actually do anything yet.  The generator only works with coffeekup, but technically you can remove the coffeekup views and replace them with jade ones.
