### ISSUE TITLE
support/format.coffee breaks client side

### ISSUE THREAD

**Issue by goldibex** [tower-archive/tower#73]
The new module system in 0.4.0-1 breaks the client side, in particular this code (tower.js 1091, from client.coffee 7):

``` Javascript
Tower.modules = {
    validator: global,
    accounting: global.accounting,
    moment: global.moment,
    geo: global.geolib,
    inflector: global.inflector
  };
```

Most of these don't actually exist yet, and when code from support/format.coffee tries to read them, it understandably breaks. I think this may have resulted from an accidental commit of development-branch code to master.

**Comment by goldibex** [comment]
I would just like to add that Tower rocks, by the way.

**Comment by lancejpollard** [comment]
You're right, I am going to fix [this template issue](https://github.com/viatropos/tower/issues/30) as well and publish a new version on npm today.  Thanks for posting.

**Comment by lancejpollard** [comment]
Alright pushed 0.4.0-2 and it's working for me.  Try updating tower with `npm install tower` in your app and `npm install tower -g` globally, and grab the latest [client-side tower.js](https://raw.github.com/viatropos/tower/master/dist/tower.js), or generate a new app.
