### ISSUE TITLE
Validator error in client-side tower.js

### ISSUE THREAD

**Issue by sebastianhoitz** [tower-archive/tower#74]
With the latest client-side tower.js file, I get this error:

```
Uncaught TypeError: Cannot read property 'prototype' of undefined 
```

on line 1094:

```
validator.Validator.prototype.error = function(msg) {
  this._errors.push(msg);
  return this;
};
```

This makes the whole towerjs application blow up, because the browser stops parsing the JS file and then all my controllers can't extend the Tower.Controller because it is not defined.

**Comment by lancejpollard** [comment]
Is this still a problem?  Make sure you have the latest version of Tower installed (and the latest client js)

**Comment by sebastianhoitz** [comment]
Yes I used the latest version and ran into this problem.

**Comment by lancejpollard** [comment]
I'm not getting this error, are you sure you've loaded the validator library on the client?
