### ISSUE TITLE
shift.js

### ISSUE THREAD

**Issue by Kotrotsos** [tower-archive/tower#8]
Anyone any idea where shift.js has moved to, the github repo is not there anymore and I can't seem to find any information on it by Googling- strangely enough. I would like to use Handlebars with Tower- and investigating if Shift.js would be the way to go about it.

Thanks!
Marco

**Comment by lancejpollard** [comment]
Moved to https://github.com/viatropos/mint.js, updated the link on the main site.

**Comment by benatkin** [comment]
There's a broken link on the [README](https://github.com/viatropos/tower) too.
