### ISSUE TITLE
Documentation: How do you use/configure the Memory Store?

### ISSUE THREAD

**Issue by contentfree** [tower-archive/tower#80]
We don't use Mongo so we're stuck "out of the box" with Tower. There's no documentation (yet) for using the memory store. I tried using the example databases.coffee as a guideline but using "memory" instead of "mongodb" or "redis" (without the host info, obviously) failed.

Would you please update the Wiki page regarding the Memory Store with a configuration example?

**Comment by lancejpollard** [comment]
I will update the documentation soon, but for now I'll just give you an example.

The memory store isn't like a redis store, it's just a simple "in memory" store.  To change stores globally, set the store on `Tower.Model`:

``` coffeescript
Tower.Model.store(Tower.Store.Memory)
Tower.Model.store(Tower.Store.MongoDB)
Tower.Model.store(Tower.Store.Ajax)
```

To change it on a per-model basis, you can do this:

``` coffeescript
App.User.store(Tower.Store.Memory)
```

**Comment by contentfree** [comment]
It would be interesting to borrow Rails' convention and have the top-level index be the environment (instead of the adapter as it seems it currently is) and then have the store parsed from that when the configuration is loaded. If that isn't doable (yet) then I suppose the config/environments/\* (currently empty files) could be used in combo with your example above.

**Comment by contentfree** [comment]
Does Tower default to Mongo? I've commented out everything in databases.coffee and tried `npm test` which failed due to not being able to connect to a database on some port.

**Comment by lancejpollard** [comment]
This may be b/c `Tower.Store.MongoDB` has an initialization hook:

[https://github.com/viatropos/tower/tree/master/src/tower/server/store/mongodb.coffee#L22](https://github.com/viatropos/tower/blob/221efcbd4aa4ebe9a069f5cc59070a29acb99085/src/tower/server/store/mongodb.coffee#L22)

We probably have to change this.  Try messing with that (comment it out) and seeing if you can get it to work.  If you can find a fix that allows opt-out of MongoDB that would be awesome, send me a pull request.  I won't be able to get to this for a couple days.

**Comment by contentfree** [comment]
Are you ever on IRC? I've jumped on a few times to an empty channel. It might be a good chance to talk about implementing Rails' style DB config file – environment -> adapter – vs the current Tower way of adapter -> environments.

**Comment by lancejpollard** [comment]
I'll be on IRC more regularly (#towerjs), I hardly ever have used it.

**Comment by kynan** [comment]
I don't understand how to globally change the store. At which point would I `Tower.Model.store(Tower.Store.Memory)`?
