### ISSUE TITLE
Can not use templates in the client-side controllers

### ISSUE THREAD

**Issue by sebastianhoitz** [tower-archive/tower#81]
My server-side templates get sent to the client in the templates.js file and registered in Tower.View.cache.

However, when I try to use those templates in my controller via @render(), I always get this error:

```
TypeError: Object #<Memory> has no method 'findPath'
```

This is what I try to do in my controller:

```
class App.PhotoController extends Tower.Controller
  @on "event:photo.create", "addPhoto"
  addPhoto: (photo) ->
    item = @render "_item", locals: photo
    $("#slideshow ul").append item
```

Am I doing something wrong?

**Comment by lancejpollard** [comment]
You're correct, this is a bug.  You should be able to mess with [Tower.View#_readTemplate](https://github.com/viatropos/tower/blob/ffef44f9d92aaed2200358cf37b4029417fee2cb/dist/tower.js#L6046), changing that `store.findPath` to something like `Tower.View.cache`.  I updated this to fix a previous template bug server side, haven't updated client.  Will fix this soon unless you get to it first.

Also, we need better ways to test the client side of tower.

**Comment by avastou** [comment]
I need help to fix this bug.
Someone already corrected or could help me?

**Comment by sebastianhoitz** [comment]
This is merged in as of pull request #111.

What do you think?

**Comment by avastou** [comment]
I do not see how to use it.
Is this correct:

``` coffee
    item = @render "shared/application/_tweet", locals: tweet
    $(item).hide().prependTo(".tweet-container").fadeIn(1500);
```

because it seems not to work

**Comment by sebastianhoitz** [comment]
It depends on the context you are in. You can use the @render method the same way you would use it on the server side.

So, assuming you are within the applicationController:

``` coffeescript
item = @render "_tweet", locals: tweet
```

should give you the correct item. Does that work for you?

**Comment by avastou** [comment]
it's in my client side controller, i use this : 

``` coffee
item = @render "shared/application/_tweet", locals: {tweet: tweet}
```

but this does not work.

**Comment by sebastianhoitz** [comment]
Skip the "shared/application".

Just use @render "_tweet" like you would do on the server side.

On Mon, May 7, 2012 at 4:03 PM, avastou <
reply@reply.github.com
