### ISSUE TITLE
Scaffolding for CamelCased models does not work.

### ISSUE THREAD

**Issue by egv** [tower-archive/tower#84]
Scaffolding will not work for models with CamelCased names. All files are generated, but when you try to click model's name in navigaiton bar you get "no path matches.." error.

Steps to reproduce:

> tower new test
> cd test
> npm install -d
> tower g scaffold TestTest name:String
> node server

after clicking on TestTest link in the navigation bar you get 

> No path matches /test-tests

**Comment by lancejpollard** [comment]
Thanks for posting, will fix this soon.
