### ISSUE TITLE
passportjs example?

### ISSUE THREAD

**Issue by avastou** [tower-archive/tower#86]
Does anyone got an example of using towerjs with passportjs ?

I can not integrate it.
Thank you.

**Comment by lancejpollard** [comment]
I am starting to use passport now.  I will post an example project when I get the time.

For now, here is some extracted code (hacks now, need a clean way to make those urls in the app in a controller):

``` coffeescript
# config/application.coffee
global.passport   = require 'passport'

require './credentials'
require './session'

MongoStore = require('connect-mongo')

FacebookStrategy  = require('passport-facebook').Strategy

passport.use new FacebookStrategy
  clientID:     Tower.secrets.facebook.key
  clientSecret: Tower.secrets.facebook.secret
  callbackURL:  "http://localhost:3000/auth/facebook/callback"
  (accessToken, refreshToken, profile, done) ->
    process.nextTick ->
      global.App.User.findOrCreateFromFacebook profile, (error, user) ->
        done error, user

class App extends Tower.Application
  @configure ->
    @use "favicon", Tower.publicPath + "/favicon.ico"
    @use 'static', Tower.publicPath, maxAge: Tower.publicCacheDuration
    @use "profiler" if Tower.env != "production"
    @use "logger"
    @use "query"
    @use "methodOverride", "_method"

    require './databases'
    mongostore = _.extend {}, Tower.Store.MongoDB.config[Tower.env]
    mongostore.db = mongostore.name
    delete mongostore.name

    @use 'bodyParser'
    @use 'cookieParser', Tower.config.session.key
    @use 'session', secret: Tower.config.session.secret, store: new MongoStore(mongostore)#, cookie: {domain: "." + Tower.config.session.cookie.domain}
    ##@use "csrf"
    @use passport.initialize()
    @use passport.session()

    @get "/auth/facebook", passport.authenticate("facebook"), (request, response) ->
      # The request will be redirected to Facebook for authentication

    @get "/auth/facebook/callback", passport.authenticate("facebook", failureRedirect: "/login"), (request, response) ->
      response.redirect "/"

    passport.serializeUser (user, done) ->
      done null, user.get('id').toString()

    passport.deserializeUser (id, done) ->
      global.App.User.find id, (error, user) ->
        done error, user

    @use Tower.Middleware.Agent
    @use Tower.Middleware.Location
    @use Tower.Middleware.Router

module.exports = global.App = new App
```

``` coffeescript
# config/secrets.coffee
Tower.secrets =
  facebook:
    key:    "your-key"
    secret: "your-secret"
```

``` coffeescript
# app/models/user.coffee
class App.User extends Tower.Model
  @field "facebookId"
  @field "firstName"
  @field "lastName"
  @field "fullName"
  @field "username"

  @findOrCreateFromFacebook: (meta, callback) ->
    data            = {}
    name            = meta.username
    name          ||= meta.displayName
    name          ||= ""
    name            = name.replace(/[^a-z0-9]/gi, "-")
    data.firstName  = meta.name.givenName
    data.lastName   = meta.name.familyName
    data.fullName   = meta.displayName
    data.username   = meta.username
    data.username ||= name
    data.facebookId = meta.id

    @create data, callback
```

``` coffeescript
# app/controllers/applicationController.coffee
class App.ApplicationController extends Tower.Controller
  @layout "application"

  @beforeAction "setCurrentUser"

  setCurrentUser: ->
    @currentUser ||= @request.user
    true
```

Hope that helps.

**Comment by avastou** [comment]
thanks for help.

**Comment by kristianmandrup** [comment]
Here is my untested attempt at wrapping the Passport configuration in a more Object Oriented way. 
Feel free to modify as needed:

``` coffeescript
class App extends Tower.Application
  @configure ->
    # ...
    @use 'bodyParser'
    @use 'cookieParser', Tower.config.session.key
    @use 'session', secret: Tower.config.session.secret, store: new Tower.Store.Mongo()

    @auth = new Tower.Auth.Passport(@)    

    # middleware
    @use Tower.Middleware.Agent
    @use Tower.Middleware.Location


Tower.Store.Mongo extends Tower.Class
  constructor: (options = {}) ->
    @initialize options

  # cookie: {domain: "." + Tower.config.session.cookie.domain}
  initialize: (options = {}) ->
    require './databases'
    @mongostore = _.extend Tower.Store.MongoDB.config[Tower.env]
    @mongostore.db = @mongostore.name
    delete @mongostore.name
    new MongoStore(@mongostore, _.extend(options, store_options) 

  store_options: ->
    cookie: {domain: "." + Tower.config.session.cookie.domain}

# Passport configuration

Tower.Auth = {}

class Tower.Auth.Passport extends Tower.Class
  @configure: ->    
    @app.use passport.initialize()
    @app.use passport.session()
    @passport = @app.passport

  strategy: (name) ->
    strategy_found = Tower.Auth.Passport[_.camelize(name)]
    throw Error "Passport strategy #{name} not defined" if not strategy_found
    strategy_found

  constructor: (app) ->
    @initialize app

  initialize: (app, strategies) ->
    @app = app
    @configure
    new Tower.Auth.Passport.strategy(name)(@passport)  

class Tower.Auth.Passport.Strategy extends Tower.Class
  constructor: (passport) ->
    @initialize passport

  initialize: (passport) ->
    passport.serializeUser (user, done) ->
      done null, user.get('id').toString()

    passport.deserializeUser (id, done) ->
      global.App.User.find id, (error, user) ->
        done error, user

class Tower.Auth.Passport.Facebook extends Tower.Auth.Passport.Strategy
  constructor: (passport) ->
    @initialize passport

  initialize: (passport) ->
    super(passport)
    new Routes(passport)

class Tower.Auth.Passport.Facebook.Routes extends Tower.HTTP.Route
  constructor: (passport) ->
    @initialize passport

  initialize: (passport) ->
    get "/auth/facebook", passport.authenticate("facebook"), (request, response) ->
      # The request will be redirected to Facebook for authentication

    get "/auth/facebook/callback", passport.authenticate("facebook", failureRedirect: "/login"), (request, response) ->
      response.redirect "/"
```

**Comment by lancejpollard** [comment]
That's pretty cool, generates a whole bunch of ideas!

**Comment by kristianmandrup** [comment]
Thanks. Likely should be `Routes.draw` ?

**Comment by lancejpollard** [comment]
Those `get` things, yes.  But the tricky part is figuring out how to insert those `passport.authenticate("facebook")` calls.  That's middleware, haven't handle that case.  They could be placed in a `beforeAction` callback in the controller, but that's not ideal.

**Comment by avastou** [comment]
i have a small probleme with :

class Tower.Auth.Passport.Local.Routes extends Tower.HTTP.Route
  constructor: (passport) ->
    @initialize passport
    console.log passport

  initialize: (passport) ->
    @post "/auth/login", passport.authenticate("local", failureRedirect: "/login"), (request, response) ->
      response.redirect "/"

Error:
TypeError: Object #<Routes> has no method 'post'

AND is it possible to do something like this in the models ( user.verifyPassword(password) ) ?
  global.App.User.findOne
    username: username
  , (err, user) ->
    return done(null, false)  unless user.verifyPassword(password)

**Comment by Akkuma** [comment]
I'm having an interesting problem getting passport to work. I verified I'm not an idiot by getting express installed, running, and using the same quick passport test to limit it to something within Tower.

The actual error:

```
/[appName]/node_modules/passport-google/node_modules/passport-openid/node_modules/openid/openid.js:333
  provider.endpoint = service.uri;
                             ^
TypeError: Cannot read property 'uri' of undefined
  at /[appName]/node_modules/passport-google/node_modules/passport-openid/node_modules/openid/openid.js:333:32
  at /[appName]/node_modules/passport-google/node_modules/passport-openid/node_modules/openid/openid.js:477:25
  at /[appName]/node_modules/passport-google/node_modules/passport-openid/node_modules/openid/openid.js:207:9
  at IncomingMessage.<anonymous> (/[appName]/node_modules/passport-google/node_modules/passport-openid/node_modules/openid/openid.js:211:32)
  at IncomingMessage.emit (events.js:88:20)
  at HTTPParser.onMessageComplete (http.js:137:23)
  at CleartextStream.ondata (http.js:1150:24)
  at CleartextStream._push (tls.js:375:27)
  at SecurePair.cycle (tls.js:734:20)
  at EncryptedStream.write (tls.js:130:13)
```

The reason this is happening is that within openid there is the following code:

``` javascript
  for(var s in services)
  {
    var service = services[s];
    var provider = {};

    provider.endpoint = service.uri;
```

The for loop is picking up isEnumerable, since there is no hasOwnProperty check and then throws an error. I'm not sure what is adding this or where it is coming from, so I figured I'd raise it here. At the same time it seems that node-openid shouldn't be using a for in on an Array anyway.

I submitted a [patch/pull request](https://github.com/havard/node-openid/pull/71) to node-openid for their side of the problem, which resolved everything on my end, but perhaps TowerJS should take a look into the isEnumerable portion as well.

**Comment by kristianmandrup** [comment]
Great :) I think the problem lies in openid as you point out :) Would be great with some more sample implementations of PassPort integration and similar auth solutions :) Let us know if the openid patch solves your problem.

**Comment by Akkuma** [comment]
@kristianmandrup Yes, the patch I submitted resolved the issues I had with Tower when it comes to Google OpenID authentication. I'm sure it would resolve it for the others I'll be adding soon.

**Comment by Akkuma** [comment]
It looks like I found **another** case where node-openid was using `for in` when they really shouldn't have been. Aside from all the fixes I made, I found I can't get the Steam OpenID working for me.

**Comment by kristianmandrup** [comment]
Are you using this one? https://github.com/liamcurry/passport-steam

**Comment by Akkuma** [comment]
@kristianmandrup Yes that is correct. I verified it is not working in a simple Express app as well, so the issue doesn't stem from Tower.

Additionally, I've gotten a fairly clean way to do authentication while using the Routes without any sort of framework required. It probably is the simplest and most elegant solution right now.

``` coffeescript
  @match '/auth/:provider', to: 'application#auth'
```

Inside of my Application Controller:

``` coffeescript
  auth: ->
    passport.authenticate(@params.provider) @request, @response, -> console.log arguments
```

**Comment by kristianmandrup** [comment]
Cool :) Could you share your "full" passport setup example on a gist or something ;)

**Comment by Akkuma** [comment]
As requested a "full" passport setup example https://gist.github.com/2429021

**Comment by kristianmandrup** [comment]
Way to go! :) This is excellent news... 

Would be nice with a small sample application illustrating authentication setup this way. Then we could mix in an authorization solution later perhaps ;) 

``` coffeescript
if can(current_user, :read, @post)
  # render some template
else
  # render some other template or perhaps no template?

# or perhaps
if current_user.can(:read).the(@post)

if current_user.can(:read).all_the(@posts)

if current_user.can(:read).any_of_the(@posts)
```

https://github.com/ryanb/cancan/wiki/Defining-Abilities

``` coffeescript
Tower.Authorization.Cannibal extends Class
  can -> (user, actions, models)
    ...
  cannot -> (user, actions, models)    
    !can(user, actions, models)
```

``` coffeescript
MyApp.Ability extends Tower.Cannibal.Ability
  initialize -> (subject, options = {})
    subject.can('read').any(Post)
```

``` coffeescript
Tower.Cannibal.Ability extends Class
     can -> (actions)
        action_rule = new Tower.Cannibal.ActionRule(actions)
        @rules.concat action_rule if action_rule
```

``` coffeescript
Tower.Cannibal.ActionRule extends Class
    initialize -> (actions)
      @actions = actions

     any -> (model_classes)
       @model_classes = model_classes
       new Rule(@)

     the -> (model)
       @model = model
       new Rule(@)

     all_the ->
     any_of_the ->
```

``` coffeescript
# similar to CanCan Rule
Tower.Cannibal.Rule extends Class
  initialize -> (options = {})

  # other can be an object or functio returning object for relation
  by -> (method_name, other)

  # fun is a function
  when -> (fun)

```

Just some initial ideas ;)

**Comment by Akkuma** [comment]
I come from a ASP.NET background, so the way we handled authorization where I worked was through an Authorization Attribute. Basically, you threw it onto the controller actions that required authorization .

It might almost be worth it for someone to try porting CanCan to node, especially with the goal of this framework to largely replicate RoR and the ideas it has like you threw out there seems to jive well with how authorization could work.

**Comment by lancejpollard** [comment]
If @kristianmandrup doesn't get to it first, I'm definitely going to implement CanCan a couple weeks from now.  It's the most elegant solution to the authorization problem I've seen.

**Comment by kristianmandrup** [comment]
I will get on it today. I agree, but I think it could be much better, especially the DSL could be improved and no reason why it should be limited to operate on `current_user` only.

**Comment by kristianmandrup** [comment]
Here is my attempt at porting a subset of CanCan:

https://github.com/kristianmandrup/beer_can

Note, no tests and surely some pieces missing. Is all I had time for now (grunt work). Cheers!

**Comment by kristianmandrup** [comment]
I've just made a lot of fixes to BeerCan so I think it now provides a pretty good foundation for a CanCan-like Authorization implementation. Just needs some more love and care from someone more expert in Tower, coffeescript and javascript frameworks... The basic tests/specs should now be in place.

**Comment by lancejpollard** [comment]
You're the man! Gotta take a look at it tomorrow, can't wait.

**Comment by kristianmandrup** [comment]
Now finally starting to look usable ;) ttyl. Have a nice wkend.

**Comment by kristianmandrup** [comment]
I've now setup _beer_can_ with _jasmine_ and _coffeescript-guard_ for BDD. This in turn has let me debug and fix the syntax errors. However I still have problems running jasmine (via ruby). 

I'm still not able to load the _beer_can_ module from spec_helper before running each individual spec. 
Could you have a look? Thanks.

https://github.com/kristianmandrup/beer_can
