### ISSUE TITLE
Don't use database?

### ISSUE THREAD

**Issue by vjsingh** [tower-archive/tower#87]
Is there any way to avoid using a database at all, except for going into the source and changing it? I'm trying to deploy on nodejitsu and would like to avoid setting up a database on that.

Thanks

**Comment by lancejpollard** [comment]
Working on this...

Thinking about making it so you have to require the components of tower you want (and the generator will give you defaults while being customizable).  Something like:

``` coffeescript
# config/application.coffee

require 'tower/store/mongodb'
require 'tower/store/memory'

class App extends Tower.Application
# ...
```

I'd like to not have to go down that road, but the alternative is having some sort of config variables like this:

``` coffeescript
class App extends Tower.Application
  @stores: ["memory", "mongodb"]
```

Not sure yet if custom config variables like that are more confusing.  One the other hand, the `require` method would require we separate tower out into chunks and it's not ready for that yet.

The client should work this way too in the end, where you can require minimal amounts of code.  By default, `tower.js` would give you everything.  But you should also be able to do this:

```
/javascripts/tower.core.js
/javascripts/tower.model.js
/javascripts/tower.store.memory.js
/javascripts/tower.controller.js
```

Or more fine-grained, if you only wanted non-persisted tower models without chainable scopes:

```
/javascripts/tower.core.js
/javascripts/tower.model.core.js
/javascripts/tower.model.attributes.js
/javascripts/tower.model.validations.js
```

But that's the last thing on the [roadmap](https://github.com/viatropos/tower/wiki/roadmap).  Will try and find a short-term workaround.

**Comment by vjsingh** [comment]
Making Tower more modular would definitely make it more useful in the future, I think. Especially since it already has so many features.

About the 2 different version of requiring, they seem roughly equivalent to me. If anything I like the second one more, although if there end up being lots of optional requires then the first one is probably neater.

That said, its usually not a huge issue to just set up a mongoDB database, so I agree this isn't the most urgent issue.

**Comment by vjsingh** [comment]
Or, only initialize mongoDB if the user adds it in databases.coffee? So removing all of databases.coffee would prevent mongoDB from being initialized, and you could default to using in-memory store.

**Comment by contentfree** [comment]
I like Rails' approach better: You specify the store per environment. You could then configure dev and test to use Memory and staging and production to use Mongo (or MySQL / Postgres eventually). This would all be in databases.coffee. I've got a check-in that removes the references to Mongo in the tests and defaults to the Memory store... need to submit the pull request.

**Comment by rafaelmotta** [comment]
News about this issue?

**Comment by sean** [comment]
Any updates on this issue? It's unfortunate that creating a new Tower.js app and then following the README results in this:

```$ npm start

> launchpad@0.0.1 start /Users/sean/Projects/launchpad
> node server.js -e production

path.existsSync is now called `fs.existsSync`.
   info  - socket.io started
[Mon, 30 Jul 2012 01:09:53 GMT] INFO Tower production server listening on port 3000

/Users/sean/Projects/launchpad/node_modules/tower/lib/tower/server/store/mongodb/database.js:39
            throw error;
                  ^
Error: failed to connect to [127.0.0.1:27017]
    at Server.connect.connectionPool.on.server._serverState (/Users/sean/Projects/launchpad/node_modules/mongodb/lib/mongodb/connection/server.js:473:73)
    at EventEmitter.emit (events.js:115:20)
    at connection.on._self._poolState (/Users/sean/Projects/launchpad/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:92:15)
    at EventEmitter.emit (events.js:91:17)
    at Socket.errorHandler (/Users/sean/Projects/launchpad/node_modules/mongodb/lib/mongodb/connection/connection.js:387:10)
    at Socket.EventEmitter.emit (events.js:88:17)
    at Socket._destroy.self.errorEmitted (net.js:329:14)
    at process.startup.processNextTick.process._tickCallback (node.js:244:9)
npm ERR! launchpad@0.0.1 start: `node server.js -e production`
npm ERR! `sh "-c" "node server.js -e production"` failed with 1
npm ERR! 
npm ERR! Failed at the launchpad@0.0.1 start script.
npm ERR! This is most likely a problem with the launchpad package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js -e production
npm ERR! You can get their info via:
npm ERR!     npm owner ls launchpad
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 11.4.0
npm ERR! command "node" "/usr/local/bin/npm" "start"
npm ERR! cwd /Users/sean/Projects/launchpad
npm ERR! node -v v0.8.3
npm ERR! npm -v 1.1.43
npm ERR! code ELIFECYCLE
npm ERR! stack Error: launchpad@0.0.1 start: `node server.js -e production`
npm ERR! stack `sh "-c" "node server.js -e production"` failed with 1
npm ERR! stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/exec.js:56:20)
npm ERR! stack     at ChildProcess.EventEmitter.emit (events.js:91:17)
npm ERR! stack     at Process._handle.onexit (child_process.js:674:10)
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/sean/Projects/launchpad/npm-debug.log
npm ERR! not ok code 0```

**Comment by lancejpollard** [comment]
This is going to take some time to fix.

What you don't want to do is make it so if you don't have mongodb installed/running it uses the memory store, because then it may be confusing/difficult to figure out how to start using mongodb. Don't want that barrier.

One workaround (what meteor does) is precompile mongodb/node into a .zip file, so when you install tower you get mongodb too. There are too many issues with this though (you have to start dealing with individual operating systems).

Will think about this some more, I think in the short term having clear documentation showing that you must install and run mongodb (or manually remove databases.coffee or something similiar, such as with a command-line flag), this will become a lot clearer.

**Comment by lancejpollard** [comment]
This is now fixed, try generating a new app and checking out the package.json. MongoDB, socket.io, and coffee-script are now only added to the generated app's package.json, so tower doesn't have those dependencies. If you don't want to use a database at all, then remove the generated `mongodb: ...` from `app/config/databases.coffee`, or set `default: 'memory'` (see the code here for how it works: [packages/tower-application/server/application.coffee#L112](https://github.com/viatropos/tower/blob/d8c43b38d04df8896e121cea5f9ecdacac2ad6c4/packages/tower-application/server/application.coffee#L112)). Cheers.

**Comment by sean** [comment]
Excellent! Thank you.
