### ISSUE TITLE
Problem with my installation

### ISSUE THREAD

**Issue by ravidsrk** [tower-archive/tower#88]
I tried installing tower using npm i am getting some error. 

I am long time Javascript and Rails Developer, I am new to nodejs. Please help me.

I have added my error below/

~ ○ → npm -g install tower
npm http GET https://registry.npmjs.org/tower
npm http 200 https://registry.npmjs.org/tower
npm http GET https://registry.npmjs.org/tower/-/tower-0.4.0-3.tgz
npm http GET https://registry.npmjs.org/underscore.string
npm http GET https://registry.npmjs.org/lingo
npm http GET https://registry.npmjs.org/mime
npm http GET https://registry.npmjs.org/underscore
npm http GET https://registry.npmjs.org/underscore.logger
npm http GET https://registry.npmjs.org/qs
npm http GET https://registry.npmjs.org/mint
npm http GET https://registry.npmjs.org/coffee-script
npm http GET https://registry.npmjs.org/pathfinder
npm http GET https://registry.npmjs.org/ejs
npm http GET https://registry.npmjs.org/coffeekup
npm http GET https://registry.npmjs.org/restler
npm http GET https://registry.npmjs.org/useragent
npm http GET https://registry.npmjs.org/URIjs
npm http GET https://registry.npmjs.org/commander
npm http GET https://registry.npmjs.org/moment
npm http GET https://registry.npmjs.org/node-uuid
npm http GET https://registry.npmjs.org/connect
npm http GET https://registry.npmjs.org/express
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/socket.io
npm http GET https://registry.npmjs.org/geolib
npm http GET https://registry.npmjs.org/accounting
npm http GET https://registry.npmjs.org/validator
npm http 304 https://registry.npmjs.org/underscore.string
npm http 304 https://registry.npmjs.org/mime
npm http 304 https://registry.npmjs.org/lingo
npm http 304 https://registry.npmjs.org/underscore
npm http 304 https://registry.npmjs.org/underscore.logger
npm http 304 https://registry.npmjs.org/qs
npm http 304 https://registry.npmjs.org/mint
npm http 304 https://registry.npmjs.org/coffee-script
npm http 304 https://registry.npmjs.org/pathfinder
npm http 304 https://registry.npmjs.org/ejs
npm http 304 https://registry.npmjs.org/coffeekup
npm http 304 https://registry.npmjs.org/restler
npm http 304 https://registry.npmjs.org/useragent
npm http 304 https://registry.npmjs.org/URIjs
npm http 304 https://registry.npmjs.org/commander
npm http 304 https://registry.npmjs.org/moment
npm http 304 https://registry.npmjs.org/node-uuid
npm http 304 https://registry.npmjs.org/express
npm http 304 https://registry.npmjs.org/async
npm http 304 https://registry.npmjs.org/socket.io
npm http 304 https://registry.npmjs.org/geolib
npm http 304 https://registry.npmjs.org/accounting
npm http 304 https://registry.npmjs.org/validator
npm http 200 https://registry.npmjs.org/connect
npm http GET https://registry.npmjs.org/connect/-/connect-2.1.2.tgz
npm http GET https://registry.npmjs.org/yamlparser/0.0.2
npm http GET https://registry.npmjs.org/request/2.2.9
npm http GET https://registry.npmjs.org/semver/1.0.12
npm http GET https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/detective
npm http GET https://registry.npmjs.org/findit
npm http GET https://registry.npmjs.org/connect
npm http GET https://registry.npmjs.org/mime/1.2.4
npm http GET https://registry.npmjs.org/mkdirp/0.3.0
npm http GET https://registry.npmjs.org/redis/0.6.7
npm http GET https://registry.npmjs.org/socket.io-client/0.9.5
npm http GET https://registry.npmjs.org/policyfile/0.0.4
npm http GET https://registry.npmjs.org/formidable/1.0.9
npm http GET https://registry.npmjs.org/debug
npm http GET https://registry.npmjs.org/crc/0.1.0
npm http 304 https://registry.npmjs.org/request/2.2.9
npm http 304 https://registry.npmjs.org/yamlparser/0.0.2
npm http 304 https://registry.npmjs.org/semver/1.0.12

> useragent@1.0.6 postinstall /usr/local/lib/node_modules/tower/node_modules/useragent
> node ./bin/update.js

npm http 304 https://registry.npmjs.org/findit
npm http 304 https://registry.npmjs.org/detective
npm http 304 https://registry.npmjs.org/connect
npm http 304 https://registry.npmjs.org/mime/1.2.4
npm http 304 https://registry.npmjs.org/mkdirp
npm http 304 https://registry.npmjs.org/mkdirp/0.3.0
npm http 304 https://registry.npmjs.org/redis/0.6.7
npm http 304 https://registry.npmjs.org/socket.io-client/0.9.5
npm http GET https://registry.npmjs.org/uglify-js
npm http 304 https://registry.npmjs.org/formidable/1.0.9
npm http 304 https://registry.npmjs.org/policyfile/0.0.4
npm WARN excluding symbolic link test/symlinks/dir1/dangling-symlink -> does-not-exist
npm http 304 https://registry.npmjs.org/debug
npm http 304 https://registry.npmjs.org/crc/0.1.0
npm http GET https://registry.npmjs.org/seq
npm WARN excluding symbolic link lib/socket.io-client.js -> io.js
npm http GET https://registry.npmjs.org/formidable
Successfully fetched and generated new parsers from the internets.
npm http GET https://registry.npmjs.org/uglify-js/1.2.5
npm http GET https://registry.npmjs.org/ws
npm http GET https://registry.npmjs.org/active-x-obfuscator/0.0.1
npm http GET https://registry.npmjs.org/xmlhttprequest/1.2.2
npm http 304 https://registry.npmjs.org/uglify-js
npm http 304 https://registry.npmjs.org/active-x-obfuscator/0.0.1
npm http 304 https://registry.npmjs.org/seq
npm http 304 https://registry.npmjs.org/xmlhttprequest/1.2.2
npm http GET https://registry.npmjs.org/chainsaw
npm http GET https://registry.npmjs.org/hashish
npm http 304 https://registry.npmjs.org/formidable
npm http 304 https://registry.npmjs.org/ws
npm http 304 https://registry.npmjs.org/hashish
npm http 304 https://registry.npmjs.org/uglify-js/1.2.5
npm http 304 https://registry.npmjs.org/chainsaw
npm http GET https://registry.npmjs.org/zeparser/0.0.5
npm http GET https://registry.npmjs.org/traverse
npm http GET https://registry.npmjs.org/traverse

> ws@0.4.12 preinstall /usr/local/lib/node_modules/tower/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws
> make

node-waf configure build
npm http 304 https://registry.npmjs.org/traverse
npm http 304 https://registry.npmjs.org/zeparser/0.0.5
npm http 304 https://registry.npmjs.org/traverse
Checking for program g++ or c++          : /usr/bin/g++ 
Checking for program cpp                 : /usr/bin/cpp 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for g++                         : ok  
Checking for node path                   : ok /usr/local/lib/node_modules 
Checking for node prefix                 : ok /usr/local 
'configure' finished successfully (0.600s)
Waf: Entering directory `/usr/local/lib/node_modules/tower/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws/build'
[1/4] cxx: src/validation.cc -> build/Release/src/validation_1.o
[2/4] cxx: src/bufferutil.cc -> build/Release/src/bufferutil_2.o
[3/4] cxx_link: build/Release/src/validation_1.o -> build/Release/validation.node
[4/4] cxx_link: build/Release/src/bufferutil_2.o -> build/Release/bufferutil.node
Waf: Leaving directory`/usr/local/lib/node_modules/tower/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws/build'
'build' finished successfully (1.493s)
npm http GET https://registry.npmjs.org/commander
npm http GET https://registry.npmjs.org/options
npm http 304 https://registry.npmjs.org/commander
npm http 304 https://registry.npmjs.org/options
npm ERR! cb() never called!
npm ERR!  
npm not ok

**Comment by lancejpollard** [comment]
Try clearing the cache and/or running with sudo:

```
[sudo] npm cache clean -g
[sudo] npm install tower -g
```

These random errors are usually b/c of the npm cache.

**Comment by ravidsrk** [comment]
Thanks for the quick reply. It worked like an chram.

Eagerly waiting to contribute something to this project.

This project is just awesome.

**Comment by aniston** [comment]
npm cache clean -g
Thanks, this worked for me too, had a similar problem, though not related to 'tower'
