### ISSUE TITLE
Models: Can't change Boolean value

### ISSUE THREAD

**Issue by sebastianhoitz** [tower-archive/tower#92]
This is my model:

``` coffee-script
class App.Photo extends Tower.Model
  @field "published", type: "Boolean", default: true
```

When I want to change the value from false to true on an instance like this:

``` coffee-script
App.Photo.find @params.id, (err, resource) =>
  resource.set("published", true")
  resource.save()
```

The changes don't get persisted to the database. The same happens, when I run this in the console.

**Comment by lancejpollard** [comment]
This seems to be working for me, do the tests run for you?

Just added these:

[https://github.com/viatropos/tower/tree/master/test/cases/model/attributesTest.coffee#L201](https://github.com/viatropos/tower/blob/e23df4a2934d82526c7c671eaf46be7ef74f331d/test/cases/model/attributesTest.coffee#L201)

**Comment by sebastianhoitz** [comment]
Yes, the tests run for me, too.

I did some further experiments and noticed, that when I change the field definition from 

``` coffeescript
@field "published", type: "Boolean", default: true
```

to

``` coffeescript
@field "published", type: "Boolean", default: false
```

everything works as expected.

I will add a model + test case for this and make a pull request.
