### ISSUE TITLE
Problem with assets:bundle?

### ISSUE THREAD

**Issue by au-phiware** [tower-archive/tower#93]
Forgive me if I've missed something obvious here but I'm unable to run the most basic tower app in both `development` and `production` with the same results. I it appears that `cake assets:bundle` is minifying bootstrap but not in it's entirety.

Here's the steps that I've followed:

```
tower new app
cd app
sudo npm install
node server
cake assets:bundle
node server -e production
```

![In the development environment...](https://img.skitch.com/20120414-bic74fxm34nf3t23pr27d7hrh5.jpg)
![In the production environment...](https://img.skitch.com/20120414-qqpp7sqw9nk3xjirx5ycft4jut.jpg)

Here's the results of `cake assets:stats`:

```
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━┓
┃ Path                                                       ┃ Compressed (kb)    ┃ Normal (kb)        ┃ %        ┃
┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╋━━━━━━━━━━━━━━━━━━━━╋━━━━━━━━━━━━━━━━━━━━╋━━━━━━━━━━┫
┃ public/assets/application.css                              ┃ 0.0                ┃ 0.0                ┃ 100.0%   ┃
┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╋━━━━━━━━━━━━━━━━━━━━╋━━━━━━━━━━━━━━━━━━━━╋━━━━━━━━━━┫
┃ public/assets/lib.css                                      ┃ 0.0                ┃ 0.0                ┃ NaN%     ┃
┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╋━━━━━━━━━━━━━━━━━━━━╋━━━━━━━━━━━━━━━━━━━━╋━━━━━━━━━━┫
┃ public/assets/vendor.css                                   ┃ 17.8               ┃ 93.5               ┃ 80.9%    ┃
┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╋━━━━━━━━━━━━━━━━━━━━╋━━━━━━━━━━━━━━━━━━━━╋━━━━━━━━━━┫
┃ public/assets/development.css                              ┃ 0.0                ┃ 0.0                ┃ NaN%     ┃
┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╋━━━━━━━━━━━━━━━━━━━━╋━━━━━━━━━━━━━━━━━━━━╋━━━━━━━━━━┫
┃ public/assets/application.js                               ┃ 0.6                ┃ 0.9                ┃ 27.5%    ┃
┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╋━━━━━━━━━━━━━━━━━━━━╋━━━━━━━━━━━━━━━━━━━━╋━━━━━━━━━━┫
┃ public/assets/lib.js                                       ┃ 0.0                ┃ 0.0                ┃ NaN%     ┃
┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╋━━━━━━━━━━━━━━━━━━━━╋━━━━━━━━━━━━━━━━━━━━╋━━━━━━━━━━┫
┃ public/assets/vendor.js                                    ┃ 317.5              ┃ 696.1              ┃ 54.4%    ┃
┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╋━━━━━━━━━━━━━━━━━━━━╋━━━━━━━━━━━━━━━━━━━━╋━━━━━━━━━━┫
┃ public/assets/development.js                               ┃ 55.0               ┃ 135.8              ┃ 59.5%    ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┻━━━━━━━━━━━━━━━━━━━━┻━━━━━━━━━━━━━━━━━━━━┻━━━━━━━━━━┛
```

80.9% ![really?](http://www.smileyvault.com/albums/userpics/10172/confused0078.gif)

**Comment by sebastianhoitz** [comment]
I noticed that tower seemed to have problems creating the folders and files for me.

However, after I ran towerJS for a while in development, I think all the files were created for me and I could use `cake assets:bundle` to create the production files.

What errors does your Chrome developer tab show you in your console?

**Comment by au-phiware** [comment]
From memory, there were no errors, but I'll double check (I was burning the midnight oil).

I did inspect the CSS rules applied to the `navbar` and compare the two, and production simply appeared to be missing some rules, eg. there was no background-color.

What's doing the CSS compression? Should I be updating that lib?

(Thanks for the quick reply.)

**Comment by au-phiware** [comment]
Ok, to answer my own question: `mint.yui`

I see that `public/assets/vendor.css` is passed through `mint.yui` to produce the final vendor stylesheet. By inspecting these two files I see that none of the rules after line 1171 made it into the final product. Removing that line resolves my problem... I'll make a pull request.

Also, this brings the compression of vendor.css down to 15.8%, which is way more reasonable for css.

**Comment by au-phiware** [comment]
Ok, so I made https://github.com/twitter/bootstrap/pull/3068 which fixes the issue ~~and added a test for yuicommpressor: https://github.com/stoyan/yuicompressor/pull/4~~

**Comment by au-phiware** [comment]
Ok, there's clearly a lot of history that I'm missing here but here goes...

Tower depends on [mint.js](https://github.com/viatropos/mint.js) (of the same author, @viatropos). Mint.js appears to use cssmin function from @stoyan's fork of [yuicompressor](https://github.com/stoyan/yuicompressor) (last updated 10 months ago). (BTW this fork breaks the tests.) @yui has a 12 month old [pull request](https://github.com/yui/yuicompressor/pull/1) making the js port node compatible. Considering, that @yui's js port is actually the most recent (7 months old) and that pull request has id=1 and not yet been closed, it appears that @yui has no interest in the node community :(

At risk of being shot down, I propose a [new node compatible port](https://github.com/yui/yuicompressor/pull/24) of cssmin that meets one simply goal: be forward compatible with future yuicompressor releases. See my fork of [yuicompressor](https://github.com/au-phiware/yuicompressor), which contains [a wrapper for node.js](https://github.com/au-phiware/yuicompressor/blob/master/ports/js/cssmin.node.js). I've made a pull request to include this into mint.js: [Update yuicompressor code](https://github.com/viatropos/mint.js/pull/4).

A good alternative would be to use @cloudhead's version of [cssmin](https://github.com/cloudhead/less.js/blob/master/lib/less/cssmin.js), which simply adds an `export` for the compressor object. This means a minor change to mint.js, also.

**Comment by kristianmandrup** [comment]
+1 " new node compatible port of cssmin"

**Comment by au-phiware** [comment]
It would seem that I spoke too soon...

http://search.npmjs.org/#/css-compressor

**Comment by kristianmandrup** [comment]
Excellent :)

**Comment by lancejpollard** [comment]
Thanks @au-phiware, merged your pull request into mint.js and bumped tower to 0.4.0-5 with a few other package.json updates.
