### ISSUE TITLE
All credentials in config dir are public??

### ISSUE THREAD

**Issue by nov** [tower-archive/tower#95]
Seems tower.js copies all files in config dir to public/javascripts/config.
It makes these credentials public...
http://towerjs.org/javascripts/config/session.js
http://towerjs.org/javascripts/config/credentials.js

**Comment by lancejpollard** [comment]
Fixed, thanks for pointing out!

For those of you with existing apps, make sure you update your `Watchfile`:

https://github.com/viatropos/tower/blob/master/lib/tower/server/generator/generators/tower/app/templates/watch#L15

Specifically those 2 javascript sections.

Also, delete the files in `./public/javascripts/config`.

**Comment by nov** [comment]
Cool.
Thanks for your quick fix ;)

**Comment by lancejpollard** [comment]
Should make this more bullet proof, in case the Watchfile is changed or anything strange happens where those files are put in public.  Maybe a regex or warning before `git commit` if there is a file in public matching a pattern.  Or add to gitignore... Will keep in mind.

**Comment by nov** [comment]
Or just make them JSON files?

**Comment by darthdeus** [comment]
:bomb: ... trollface.jpg
