### ISSUE TITLE
socket.io example?

### ISSUE THREAD

**Issue by avastou** [tower-archive/tower#97]
Does anyone got an example of using towerjs with socket.io server side (not client controller side) ?
I would like to add events or functionalities such as:

io.set ('authorization'
io.join ('room' ...

I tried in "config/application.coffee":

console.log @io

but without success.

Thank you.

**Comment by kristianmandrup** [comment]
Recently someone added some nice socket.io changes/features. I'm sure whoever did these commits could help you get on the right track...

**Comment by ludicast** [comment]
I use sockjs instead of socket.io (it's way better ;p), but all I needed to do was override its creation in the config/application.coffee's @configure method like:
@io = require('../lib/sockjsGenerator').generate @server
and this prevents tower from creating a socketio instance.

I imagine if you had your socket.io generator in there it would work its magic the same way, though I don't know if it would let you have socket callbacks in your controllers (I don't have need for that myself).

**Comment by kristianmandrup** [comment]
I searched on socket.io in the tower repo:

tower/server/application.js L194: 

``` coffeescript
      this.io || (this.io = require('socket.io').listen(this.server));
```

Looks like the use of the 'socket.io' library is currently hardcoded

But I'm sure you could make it more flexible... perhaps something like:

``` coffeescript
Tower.libs.register('socket') = require('socket.io')

# much later

this.io || (this.io = Tower.lib('socket').listen(this.server));
```

Just some wild ideas :P

Note: This libs infrastructure is NOT in place, just an idea...

**Comment by avastou** [comment]
I got to run with this sample code base.
I do not know if this is the best practice, but it works.

#client side controller
class App.ApplicationController extends Tower.Controller
    #ui event
    @on "click .btnSend", "sendMessage"

```
#socket.io event  
@on "displayMessage", "displayMessage", type: 'socket'

sendMessage: (event) ->
    console.log("add message with socket.io")
    message = frames[0].document.body.innerHTML
    socket = io.connect()
    room = socket.of('/Applications')
    room.emit("addMessage", { msg: message })

displayMessage: (event)->
    console.log("SOCKET RECEIVED: SHow MESSAGE")
    message =  @params.msg
    console.log message
```

#server side controller
class App.ApplicationController extends Tower.Controller
    #socket.io event  
    @on "addMessage", "addMessage", type: 'socket'

```
addMessage: (event)->
    console.log "ADD MESSAGE"
    message = @params.msg
    # server side socket, add in bdd and notify
    socket = Tower.Application.instance().io
    room = socket.of('/Applications')
    room.emit("displayMessage", { msg: message })
```

**Comment by avastou** [comment]
any suggestion for use session in socket.io ?

Thanks.

**Comment by sebastianhoitz** [comment]
I will add some examples on how to use socket.io in TowerJS soon. 

Here is the email I sent @avastou, which contains some (limited) information:

> Hi!
> 
> Actually, you can use it pretty much according to the documentation.
> 
> The server-side controller can listen to socket events by calling
> 
> ``` coffeescript
> @on "socket_event", "onEvent"
> onEvent: -> console.log arguments
> ```
> 
> One thing you should do, is to add the current @socket instance, like this:
> 
> ``` coffeescript
> @on "connection", "registerHandler"
> 
> registerHandler: (socket) ->
>   @socket = socket
> ```
> 
> that way, you can later in a method send messages to your client like this:
> 
> ``` coffeescript
> @socket.emit "myMessage", foo: "bar"
> ```
> 
> Does that sound good? ;)
> 
> viatropos added some unit test cases for the socket.io stuff. You can check that out to see some implementation examples.
> 
> Greetings,
> Sebastian

**Comment by kristianmandrup** [comment]
Would it be possible to create some kind of Tower adapter to encapsulate the main API of different socket solutions?

**Comment by sebastianhoitz** [comment]
Actually I think that is whats planned. You have a controller trait, that currently has method stubs for sockets.

Check out src/tower/server/controller/sockets.coffee

We will have to implement functionality in there, in order to get this to work. That is one of the outstanding tasks I want to implement.

**Comment by kristianmandrup** [comment]
Sweet :)

**Comment by sebastianhoitz** [comment]
I just want to get some more unit testing in place before I do this.

However, for some reason I have problems using socketio for unit tests. As soon as I have more than 1 test, they time out.

You can look at that here: https://github.com/viatropos/tower/blob/development/test/cases/server/controller/socketsTest.coffee

Once you copy the test, the second test will fail. I couldn't figure yet out why that is happening.

**Comment by avastou** [comment]
thanks @sebastianhoitz.
I'll post a few lines of code soon to illustrate concretely the use of socket with towerjs

**Comment by edubkendo** [comment]
@avastou @sebastianhoitz did either of you guys ever get an example of this together? I really can't seem to make heads/tails of this at present although I haven't been at it long. Currently looking through the source code to try to figure out how it's implemented, because so far, in my controllers, I'm basically getting "undefined" on anything I try to do to access the socket. Always comes up undefined. Would LOVE an example that showed what to put in each file and where to put it just to get some very basic functionality. I can build from there.

**Comment by sebastianhoitz** [comment]
I haven't tried the most current version. It seems like @avastou did a lot of refactoring in there.

We are currently using a version off of our own branch: https://github.com/komola/tower/tree/komola

You can register a socket object in your controller by doing this:

``` coffeescript
@on "connection", "registerConnection"

registerConnection: (@sockets) ->
  console.log "I am connected", @sockets
```

Then you can do `@sockets.emit "test"` and in your clients listen to this using `@on "test", "testHandler"`

**Comment by edubkendo** [comment]
Hmm, tried using your version and that exact bit of code in my controller. But still getting an error. Is there some other place where I need to require or configure something? Or should this work dropped right into a fresh tower project?

**Comment by thehydroimpulse** [comment]
did anyone find a solution to this yet?

**Comment by edubkendo** [comment]
Looks like @viatropos gave you a pretty thorough rundown in a different issue, so yeah. If you aren't making anything proprietary, I'd love to peep your example code when you get this running @TheHydroImpulse

**Comment by thehydroimpulse** [comment]
@edubkendo Yeah! When I have something working I'll for sure let you and everyone else know.
